/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import * as zod from 'zod';


/**
 * 統合回帰分析エンドポイント

typeフィールドに応じて適切な分析手法を選択し、実行します。

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : RegressionRequestBody
    統合回帰分析リクエスト
    - type: 分析タイプ (ols, logit, probit, tobit, fe, re, iv,
      feiv, lasso, ridge)
    - tableName: 対象テーブル名
    - dependentVariable: 被説明変数
    - explanatoryVariables: 説明変数のリスト
    - その他分析固有のパラメータ

Returns
-------
JSONResponse
    分析結果またはエラーメッセージ
 * @summary Regression
 */
export const RegressionHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})


export const regressionBodyResultNameDefault = ``;
export const regressionBodyResultNameMax = 128;

export const regressionBodyDescriptionDefault = ``;
export const regressionBodyDescriptionMax = 512;



export const regressionBodyHasConstDefault = true;
export const regressionBodyMissingValueHandlingDefault = `remove`;
export const regressionBodyAnalysisTwoAlphaDefault = 1;
export const regressionBodyAnalysisTwoAlphaMin = 0;

export const regressionBodyAnalysisTwoAlphaConventionDefault = `glmnet`;
export const regressionBodyAnalysisTwoMaxIterDefault = 1000;
export const regressionBodyAnalysisTwoMaxIterMax = 100000;

export const regressionBodyAnalysisTwoCalculateSeDefault = false;
export const regressionBodyAnalysisTwoBootstrapIterationsDefault = 1000;
export const regressionBodyAnalysisTwoBootstrapIterationsMin = 100;
export const regressionBodyAnalysisTwoBootstrapIterationsMax = 10000;

export const regressionBodyAnalysisTwoMethodDefault = `lasso`;
export const regressionBodyAnalysisThreeAlphaDefault = 1;
export const regressionBodyAnalysisThreeAlphaMin = 0;

export const regressionBodyAnalysisThreeAlphaConventionDefault = `glmnet`;
export const regressionBodyAnalysisThreeMaxIterDefault = 1000;
export const regressionBodyAnalysisThreeMaxIterMax = 100000;

export const regressionBodyAnalysisThreeCalculateSeDefault = false;
export const regressionBodyAnalysisThreeBootstrapIterationsDefault = 1000;
export const regressionBodyAnalysisThreeBootstrapIterationsMin = 100;
export const regressionBodyAnalysisThreeBootstrapIterationsMax = 10000;

export const regressionBodyAnalysisThreeMethodDefault = `ridge`;
export const regressionBodyAnalysisFourRegularizationOneTypeDefault = `l1`;
export const regressionBodyAnalysisFourRegularizationOneAlphaDefault = 1;
export const regressionBodyAnalysisFourRegularizationOneAlphaMin = 0;

export const regressionBodyAnalysisFourCalculateMarginalEffectsDefault = false;
export const regressionBodyAnalysisFourBinaryResidualTypeDefault = `raw`;
export const regressionBodyAnalysisFourMethodDefault = `logit`;
export const regressionBodyAnalysisFiveRegularizationOneTypeDefault = `l1`;
export const regressionBodyAnalysisFiveRegularizationOneAlphaDefault = 1;
export const regressionBodyAnalysisFiveRegularizationOneAlphaMin = 0;

export const regressionBodyAnalysisFiveCalculateMarginalEffectsDefault = false;
export const regressionBodyAnalysisFiveBinaryResidualTypeDefault = `raw`;
export const regressionBodyAnalysisFiveMethodDefault = `probit`;
export const regressionBodyAnalysisSixIvMethodDefault = `2sls`;

export const regressionBodyAnalysisSixGmmWeightMatrixDefault = `robust`;

export const regressionBodyAnalysisSevenMethodDefault = `fe`;

export const regressionBodyAnalysisEightMethodDefault = `re`;
export const regressionBodyAnalysisNineLeftCensoringLimitDefault = 0;
export const regressionBodyAnalysisOnezeroMethodDefault = `feiv`;



export const regressionBodyAnalysisOnezeroGmmWeightMatrixDefault = `robust`;
export const regressionBodyAnalysisOneoneMethodDefault = `wls`;
export const regressionBodyAnalysisOnetwoMethodDefault = `gls`;
export const regressionBodyAnalysisOnethreeMethodDefault = `fgls`;
export const regressionBodyAnalysisOnethreeFglsMethodDefault = `heteroskedastic`;
export const regressionBodyAnalysisOnethreeMaxIterDefault = 10;
export const regressionBodyAnalysisOnethreeMaxIterMax = 100;

export const regressionBodyStandardErrorOneMethodDefault = `nonrobust`;
export const regressionBodyStandardErrorTwoMethodDefault = `robust`;
export const regressionBodyStandardErrorTwoHcTypeDefault = `HC1`;
export const regressionBodyStandardErrorThreeMethodDefault = `cluster`;
export const regressionBodyStandardErrorThreeUseCorrectionDefault = true;
export const regressionBodyStandardErrorFourMethodDefault = `hac`;
export const regressionBodyStandardErrorFourMaxlagsMin = 0;

export const regressionBodyStandardErrorFourKernelDefault = `bartlett`;
export const regressionBodyStandardErrorFourUseCorrectionDefault = true;

export const RegressionBody = zod.object({
  "tableName": zod.string().min(1).describe('分析対象のテーブル名。ワークスペース内に存在するテーブル名を指定してください。'),
  "resultName": zod.string().max(regressionBodyResultNameMax).default(regressionBodyResultNameDefault).describe('分析結果の名前（省略時は自動生成）'),
  "description": zod.string().max(regressionBodyDescriptionMax).default(regressionBodyDescriptionDefault).describe('分析結果の説明メモ'),
  "dependentVariable": zod.string().min(1).describe('被説明変数（目的変数）の列名。テーブル内に存在するカラム名を指定してください。'),
  "explanatoryVariables": zod.array(zod.string().min(1).describe('カラム名')).describe('説明変数の列名のリスト。テーブル内に存在するカラム名を指定してください。'),
  "hasConst": zod.boolean().default(regressionBodyHasConstDefault).describe('定数項を設計行列に追加するかどうか'),
  "missingValueHandling": zod.enum(['ignore', 'remove', 'error']).default(regressionBodyMissingValueHandlingDefault).describe('欠損値の処理方法（remove: 該当行を削除、ignore: そのまま使用、error: エラーとして扱う）'),
  "analysis": zod.union([zod.object({
  "method": zod.enum(['ols'])
}),zod.object({
  "alpha": zod.number().min(regressionBodyAnalysisTwoAlphaMin).default(regressionBodyAnalysisTwoAlphaDefault).describe('正則化強度のパラメータ'),
  "alphaConvention": zod.enum(['glmnet', 'sklearn']).default(regressionBodyAnalysisTwoAlphaConventionDefault).describe('alpha の規約。\'glmnet\': R の glmnet パッケージ準拠（計量経済学・統計学のデフォルト）。\'sklearn\': scikit-learn 準拠。'),
  "maxIter": zod.number().min(1).max(regressionBodyAnalysisTwoMaxIterMax).default(regressionBodyAnalysisTwoMaxIterDefault).describe('座標降下法の最大反復回数。収束しない場合は増やしてください。'),
  "calculateSe": zod.boolean().default(regressionBodyAnalysisTwoCalculateSeDefault).describe('ブートストラップ法による標準誤差を計算するかどうか'),
  "bootstrapIterations": zod.number().min(regressionBodyAnalysisTwoBootstrapIterationsMin).max(regressionBodyAnalysisTwoBootstrapIterationsMax).default(regressionBodyAnalysisTwoBootstrapIterationsDefault).describe('ブートストラップ法のイテレーション回数'),
  "randomState": zod.union([zod.number(),zod.null()]).optional().describe('ブートストラップの乱数シード。None の場合は固定しない。'),
  "method": zod.enum(['lasso']).default(regressionBodyAnalysisTwoMethodDefault)
}),zod.object({
  "alpha": zod.number().min(regressionBodyAnalysisThreeAlphaMin).default(regressionBodyAnalysisThreeAlphaDefault).describe('正則化強度のパラメータ'),
  "alphaConvention": zod.enum(['glmnet', 'sklearn']).default(regressionBodyAnalysisThreeAlphaConventionDefault).describe('alpha の規約。\'glmnet\': R の glmnet パッケージ準拠（計量経済学・統計学のデフォルト）。\'sklearn\': scikit-learn 準拠。'),
  "maxIter": zod.number().min(1).max(regressionBodyAnalysisThreeMaxIterMax).default(regressionBodyAnalysisThreeMaxIterDefault).describe('座標降下法の最大反復回数。収束しない場合は増やしてください。'),
  "calculateSe": zod.boolean().default(regressionBodyAnalysisThreeCalculateSeDefault).describe('ブートストラップ法による標準誤差を計算するかどうか'),
  "bootstrapIterations": zod.number().min(regressionBodyAnalysisThreeBootstrapIterationsMin).max(regressionBodyAnalysisThreeBootstrapIterationsMax).default(regressionBodyAnalysisThreeBootstrapIterationsDefault).describe('ブートストラップ法のイテレーション回数'),
  "randomState": zod.union([zod.number(),zod.null()]).optional().describe('ブートストラップの乱数シード。None の場合は固定しない。'),
  "method": zod.enum(['ridge']).default(regressionBodyAnalysisThreeMethodDefault)
}),zod.object({
  "regularization": zod.union([zod.object({
  "type": zod.enum(['l1', 'l2']).default(regressionBodyAnalysisFourRegularizationOneTypeDefault),
  "alpha": zod.number().min(regressionBodyAnalysisFourRegularizationOneAlphaMin).default(regressionBodyAnalysisFourRegularizationOneAlphaDefault)
}),zod.null()]).optional(),
  "calculateMarginalEffects": zod.boolean().default(regressionBodyAnalysisFourCalculateMarginalEffectsDefault).describe('平均限界効果(AME)を計算するかどうか'),
  "binaryResidualType": zod.enum(['raw', 'deviance']).default(regressionBodyAnalysisFourBinaryResidualTypeDefault).describe('残差種別。raw: 生残差 (y - p̂)、deviance: デビアンス残差。'),
  "method": zod.enum(['logit']).default(regressionBodyAnalysisFourMethodDefault)
}),zod.object({
  "regularization": zod.union([zod.object({
  "type": zod.enum(['l1', 'l2']).default(regressionBodyAnalysisFiveRegularizationOneTypeDefault),
  "alpha": zod.number().min(regressionBodyAnalysisFiveRegularizationOneAlphaMin).default(regressionBodyAnalysisFiveRegularizationOneAlphaDefault)
}),zod.null()]).optional(),
  "calculateMarginalEffects": zod.boolean().default(regressionBodyAnalysisFiveCalculateMarginalEffectsDefault).describe('平均限界効果(AME)を計算するかどうか'),
  "binaryResidualType": zod.enum(['raw', 'deviance']).default(regressionBodyAnalysisFiveBinaryResidualTypeDefault).describe('残差種別。raw: 生残差 (y - p̂)、deviance: デビアンス残差。'),
  "method": zod.enum(['probit']).default(regressionBodyAnalysisFiveMethodDefault)
}),zod.object({
  "method": zod.enum(['iv']),
  "ivMethod": zod.enum(['2sls', 'gmm']).default(regressionBodyAnalysisSixIvMethodDefault).describe('推定アルゴリズム。過剰識別かつ異分散がある場合はGMMを推奨'),
  "instrumentalVariables": zod.array(zod.string().min(1).describe('カラム名')),
  "endogenousVariables": zod.array(zod.string().min(1).describe('カラム名')),
  "gmmWeightMatrix": zod.enum(['uncentered', 'robust', 'hac']).default(regressionBodyAnalysisSixGmmWeightMatrixDefault)
}),zod.object({
  "entityIdColumn": zod.string().min(1).describe('個体ID列名'),
  "timeColumn": zod.union([zod.string().min(1).describe('カラム名'),zod.null()]).optional().describe('時間列名'),
  "method": zod.enum(['fe']).default(regressionBodyAnalysisSevenMethodDefault)
}),zod.object({
  "entityIdColumn": zod.string().min(1).describe('個体ID列名'),
  "timeColumn": zod.union([zod.string().min(1).describe('カラム名'),zod.null()]).optional().describe('時間列名'),
  "method": zod.enum(['re']).default(regressionBodyAnalysisEightMethodDefault)
}),zod.object({
  "method": zod.enum(['tobit']),
  "leftCensoringLimit": zod.union([zod.number(),zod.null()]).default(regressionBodyAnalysisNineLeftCensoringLimitDefault).describe('左側打ち切り値。この値以下のデータが打ち切られていると見なす'),
  "rightCensoringLimit": zod.union([zod.number(),zod.null()]).optional().describe('右側打ち切り値')
}),zod.object({
  "method": zod.enum(['feiv']).default(regressionBodyAnalysisOnezeroMethodDefault),
  "entityIdColumn": zod.string().min(1).describe('個体ID列名'),
  "timeColumn": zod.union([zod.string().min(1).describe('カラム名'),zod.null()]).optional().describe('時間列名'),
  "instrumentalVariables": zod.array(zod.string().min(1).describe('カラム名')),
  "endogenousVariables": zod.array(zod.string().min(1).describe('カラム名')),
  "gmmWeightMatrix": zod.enum(['uncentered', 'robust', 'hac']).default(regressionBodyAnalysisOnezeroGmmWeightMatrixDefault)
}),zod.object({
  "method": zod.enum(['wls']).default(regressionBodyAnalysisOneoneMethodDefault),
  "weightsColumn": zod.string().min(1).describe('観測値ごとの重み (1\/σ²ᵢ) を格納した列名。正の数値型列が必要（全値 > 0）。')
}),zod.object({
  "method": zod.enum(['gls']).default(regressionBodyAnalysisOnetwoMethodDefault),
  "sigmaTableName": zod.string().min(1).describe('n×n 正定値分散共分散行列を格納したテーブル名。分析テーブルの行数と次元が一致する正方行列が必要。GLS 使用時は欠損値処理が \'error\' 固定となる。')
}),zod.object({
  "method": zod.enum(['fgls']).default(regressionBodyAnalysisOnethreeMethodDefault),
  "fglsMethod": zod.enum(['heteroskedastic', 'ar1']).default(regressionBodyAnalysisOnethreeFglsMethodDefault).describe('FGLS の推定手法。\'heteroskedastic\': OLS残差を用いた1ステップFGLS（不均一分散対応）。\'ar1\': AR(1)誤差構造を仮定した反復FGLS（GLSAR）。'),
  "maxIter": zod.number().min(1).max(regressionBodyAnalysisOnethreeMaxIterMax).default(regressionBodyAnalysisOnethreeMaxIterDefault).describe('ar1 選択時の収束判定イテレーション上限。heteroskedastic 選択時は無視される。')
})]).describe('回帰分析手法の詳細パラメータ。method フィールドで手法（ols, fe, re, iv 等）を指定します。'),
  "standardError": zod.union([zod.object({
  "method": zod.enum(['nonrobust']).default(regressionBodyStandardErrorOneMethodDefault)
}),zod.object({
  "method": zod.enum(['robust']).default(regressionBodyStandardErrorTwoMethodDefault),
  "hcType": zod.enum(['HC0', 'HC1', 'HC2', 'HC3']).default(regressionBodyStandardErrorTwoHcTypeDefault)
}),zod.object({
  "method": zod.enum(['cluster']).default(regressionBodyStandardErrorThreeMethodDefault),
  "groups": zod.array(zod.string().min(1).describe('カラム名')).describe('クラスターを構成する列名'),
  "useCorrection": zod.boolean().default(regressionBodyStandardErrorThreeUseCorrectionDefault).describe('小標本補正を行うか')
}),zod.object({
  "method": zod.enum(['hac']).default(regressionBodyStandardErrorFourMethodDefault),
  "maxlags": zod.number().min(regressionBodyStandardErrorFourMaxlagsMin).describe('考慮する最大ラグ数'),
  "kernel": zod.string().default(regressionBodyStandardErrorFourKernelDefault).describe('カーネルの種類'),
  "useCorrection": zod.boolean().default(regressionBodyStandardErrorFourUseCorrectionDefault).describe('小標本補正を行うか')
})]).describe('標準誤差の計算方法設定。nonrobust, robust（HC）, cluster, hac（Newey-West）から選択します。')
}).describe('統合回帰分析リクエスト\n\n全ての回帰分析タイプを単一のエンドポイントで扱うための\n統合スキーマです。')

export const regressionResponseCodeDefault = `OK`;

export const RegressionResponse = zod.object({
  "code": zod.string().default(regressionResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "resultId": zod.string().describe('保存された分析結果の一意 ID')
}).describe('処理結果')
})

/**
 * 推定済みモデルから予測値・残差を抽出してテーブルに列追加する

指定された分析結果 ID に対応するモデルをロードし、予測値・残差などの
診断列を元のテーブルに追加します。

Parameters
----------
request : Request
    FastAPI のリクエストオブジェクト
body : AddDiagnosticColumnsRequestBody
    - tableName: 追加先テーブル名
    - resultId: 分析結果の UUID
    - target: "fitted" / "residual" / "both"
    - standardized: 標準化残差を含めるか（OLS 系のみ有効）
    - includeInterval: 95%信頼区間を含めるか
    - feType: "total" または "within"（FE/RE のみ有効）

Returns
-------
JSONResponse
    追加したテーブル名と列名リスト
 * @summary Add Diagnostic Columns
 */
export const AddDiagnosticColumnsHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})


export const addDiagnosticColumnsBodyStandardizedDefault = false;
export const addDiagnosticColumnsBodyIncludeIntervalDefault = false;
export const addDiagnosticColumnsBodyFeTypeDefault = `total`;
export const addDiagnosticColumnsBodyBinaryResidualTypeDefault = `raw`;
export const addDiagnosticColumnsBodyTobitFittedTypeDefault = `latent`;

export const AddDiagnosticColumnsBody = zod.object({
  "tableName": zod.string().min(1).describe('追加先テーブル名。ワークスペース内に存在するテーブル名を指定してください。'),
  "resultId": zod.string().describe('対象の分析結果 ID（AnalysisResult の UUID）'),
  "target": zod.enum(['fitted', 'residual', 'both']).describe('追加する値の種類。fitted: 予測値のみ、residual: 残差のみ、both: 両方'),
  "standardized": zod.boolean().default(addDiagnosticColumnsBodyStandardizedDefault).describe('True の場合、標準化残差（studentized internal）を追加する。OLS\/Logit\/Probit のみ有効。'),
  "includeInterval": zod.boolean().default(addDiagnosticColumnsBodyIncludeIntervalDefault).describe('True の場合、予測値の 95%信頼区間列を追加する。OLS\/FE\/RE\/IV で有効。'),
  "feType": zod.enum(['total', 'within']).default(addDiagnosticColumnsBodyFeTypeDefault).describe('FE\/RE モデルの予測値タイプ。total: 固定効果を含む予測（effects=True）、within: 固定効果を除いた変動成分（effects=False）。FE\/RE 以外では無視される。'),
  "binaryResidualType": zod.enum(['raw', 'deviance']).default(addDiagnosticColumnsBodyBinaryResidualTypeDefault).describe('Logit\/Probit の残差種別。raw: 生残差 (y - p̂)、deviance: デビアンス残差 sign(y-p̂)√(-2[y·log(p̂)+(1-y)·log(1-p̂)])。OLS などその他のモデルでは無視される。'),
  "tobitFittedType": zod.enum(['latent', 'observable']).default(addDiagnosticColumnsBodyTobitFittedTypeDefault).describe('Tobit モデルの予測値種別。latent: 潜在変数の予測値 x\'β（デフォルト）、observable: 観測値の無条件期待値 E[y|x]（打ち切りを考慮した期待値）。Tobit 以外のモデルでは無視される。')
}).describe('推定済みモデルから予測値・残差を抽出してテーブルに列追加するリクエスト')

export const addDiagnosticColumnsResponseCodeDefault = `OK`;

export const AddDiagnosticColumnsResponse = zod.object({
  "code": zod.string().default(addDiagnosticColumnsResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('更新されたテーブル名'),
  "addedColumns": zod.array(zod.string()).describe('追加された列名のリスト')
}).describe('処理結果')
})

/**
 * ヘックマン2段階推定エンドポイント

Step 1 で Probit により選択方程式を推定し逆ミルズ比 (IMR)
を計算します。Step 2 で IMR を追加した OLS により結果方程式
を推定し、セレクションバイアスを補正します。

Parameters
----------
request : Request
    FastAPI のリクエストオブジェクト
body : HeckmanRequestBody
    - tableName: 対象テーブル名
    - dependentVariable: 被説明変数（結果方程式）
    - explanatoryVariables: 説明変数（結果方程式）
    - selectionColumn: 選択ダミー列（0/1）
    - selectionVariables: 説明変数（選択方程式）
    - reportFirstStage: 第1段階結果を含めるか

Returns
-------
JSONResponse
    分析結果 ID またはエラーメッセージ
 * @summary Heckman Regression
 */
export const HeckmanRegressionHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})


export const heckmanRegressionBodyResultNameDefault = ``;
export const heckmanRegressionBodyResultNameMax = 128;

export const heckmanRegressionBodyDescriptionDefault = ``;
export const heckmanRegressionBodyDescriptionMax = 512;





export const heckmanRegressionBodyHasConstDefault = true;
export const heckmanRegressionBodyMissingValueHandlingDefault = `remove`;
export const heckmanRegressionBodyReportFirstStageDefault = true;

export const HeckmanRegressionBody = zod.object({
  "tableName": zod.string().min(1).describe('分析対象のテーブル名。ワークスペース内に存在するテーブル名を指定してください。'),
  "resultName": zod.string().max(heckmanRegressionBodyResultNameMax).default(heckmanRegressionBodyResultNameDefault).describe('分析結果の名前（省略時は自動生成）'),
  "description": zod.string().max(heckmanRegressionBodyDescriptionMax).default(heckmanRegressionBodyDescriptionDefault).describe('分析結果の説明メモ'),
  "dependentVariable": zod.string().min(1).describe('結果方程式の被説明変数列名。選択サンプル（selectionColumn=1）のみで推定されます。'),
  "explanatoryVariables": zod.array(zod.string().min(1).describe('カラム名')).describe('結果方程式の説明変数列名リスト。'),
  "selectionColumn": zod.string().min(1).describe('選択ダミー列名（0\/1）。1 = 結果変数が観測されるサンプル。'),
  "selectionVariables": zod.array(zod.string().min(1).describe('カラム名')).describe('選択方程式（Probit）の説明変数列名リスト。除外制約として explanatoryVariables にない変数を 1 つ以上含む必要があります。'),
  "hasConst": zod.boolean().default(heckmanRegressionBodyHasConstDefault).describe('結果方程式（Step 2 OLS）に定数項を追加するか。'),
  "missingValueHandling": zod.enum(['ignore', 'remove', 'error']).default(heckmanRegressionBodyMissingValueHandlingDefault).describe('欠損値の処理方法（remove: 削除, ignore: 無視, error: エラー）'),
  "reportFirstStage": zod.boolean().default(heckmanRegressionBodyReportFirstStageDefault).describe('1 段階目（Probit）の推定結果をレスポンスの firstStage に含めるか。')
}).describe('ヘックマン2段階推定リクエスト\n\n選択方程式（Probit）と結果方程式（OLS）の2段階推定\nによりサンプルセレクションバイアスを補正します。')

export const heckmanRegressionResponseCodeDefault = `OK`;

export const HeckmanRegressionResponse = zod.object({
  "code": zod.string().default(heckmanRegressionResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "resultId": zod.string().describe('保存された分析結果の一意 ID')
}).describe('処理結果')
})

/**
 * 差の差（DID）分析エンドポイント

Two-Way Fixed Effects（TWFE）による DID 推定を実行します。
交差項（treated × post）はサービス層で自動生成されます。
include_event_study=true の場合、各時点の処置効果係数も推定します。

Parameters
----------
request : Request
    FastAPI のリクエストオブジェクト
body : DIDRequestBody
    DID 分析リクエスト
    - tableName: 対象テーブル名
    - dependentVariable: 被説明変数
    - treatmentColumn: 処置群ダミー（treated_i）
    - postColumn: 処置後ダミー（post_t）
    - timeColumn: 時点列
    - entityIdColumn: 個体 ID 列
    - explanatoryVariables: 追加共変量（省略可）
    - includeEventStudy: Event Study 実行フラグ
    - basePeriod: Event Study 基準期（省略時は自動選択）
    - standardError: 標準誤差の種別（cluster 推奨）
    - confidenceLevel: 信頼区間水準

Returns
-------
JSONResponse
    {"code": "OK", "result": {"resultId": "<uuid>"}}
    分析結果は GET /analysis/results/{resultId} で取得可能。
 * @summary Did Analysis
 */
export const DidAnalysisHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})


export const didAnalysisBodyResultNameDefault = ``;
export const didAnalysisBodyResultNameMax = 128;

export const didAnalysisBodyDescriptionDefault = ``;
export const didAnalysisBodyDescriptionMax = 512;







export const didAnalysisBodyIncludeEventStudyDefault = false;

export const didAnalysisBodyMissingValueHandlingDefault = `remove`;
export const didAnalysisBodyStandardErrorOneMethodDefault = `nonrobust`;
export const didAnalysisBodyStandardErrorTwoMethodDefault = `robust`;
export const didAnalysisBodyStandardErrorTwoHcTypeDefault = `HC1`;
export const didAnalysisBodyStandardErrorThreeMethodDefault = `cluster`;
export const didAnalysisBodyStandardErrorThreeUseCorrectionDefault = true;
export const didAnalysisBodyStandardErrorFourMethodDefault = `hac`;
export const didAnalysisBodyStandardErrorFourMaxlagsMin = 0;

export const didAnalysisBodyStandardErrorFourKernelDefault = `bartlett`;
export const didAnalysisBodyStandardErrorFourUseCorrectionDefault = true;
export const didAnalysisBodyConfidenceLevelDefault = 0.95;
export const didAnalysisBodyConfidenceLevelMin = 0.5;
export const didAnalysisBodyConfidenceLevelMax = 0.999;



export const DidAnalysisBody = zod.object({
  "tableName": zod.string().min(1).describe('分析対象のテーブル名。ワークスペース内に存在するテーブル名を指定してください。'),
  "resultName": zod.string().max(didAnalysisBodyResultNameMax).default(didAnalysisBodyResultNameDefault).describe('分析結果の名前（省略時は自動生成）'),
  "description": zod.string().max(didAnalysisBodyDescriptionMax).default(didAnalysisBodyDescriptionDefault).describe('分析結果の説明メモ'),
  "dependentVariable": zod.string().min(1).describe('被説明変数（目的変数）の列名。テーブル内に存在する数値型カラムを指定してください。'),
  "explanatoryVariables": zod.array(zod.string().min(1).describe('カラム名')).optional().describe('追加の共変量（コントロール変数）の列名リスト。treatment_column \/ post_column との重複は不可。'),
  "treatmentColumn": zod.string().min(1).describe('処置群ダミー列名（treated_i）。個体レベルの 0\/1 変数。処置群=1、対照群=0。'),
  "postColumn": zod.string().min(1).describe('処置後ダミー列名（post_t）。時点レベルの 0\/1 変数。処置後=1、処置前=0。'),
  "timeColumn": zod.string().min(1).describe('時点列名。数値型または Date 型。Event Study 実行時は整数型を推奨します。'),
  "entityIdColumn": zod.string().min(1).describe('個体 ID 列名。TWFE の個体固定効果に使用します。'),
  "includeEventStudy": zod.boolean().default(didAnalysisBodyIncludeEventStudyDefault).describe('Event Study を実行するかどうか。True の場合、各時点の処置効果係数（δ_k）を推定します。'),
  "basePeriod": zod.union([zod.number(),zod.null()]).optional().describe('Event Study の基準期（処置効果をゼロに固定する時点）。null の場合は処置直前期（通常 -1）を自動選択します。include_event_study=true のときのみ有効です。'),
  "maxPrePeriods": zod.union([zod.number().min(1),zod.null()]).optional().describe('Event Study で表示する処置前の最大期間数。null の場合はデータ内の全処置前期間を使用します。'),
  "maxPostPeriods": zod.union([zod.number().min(1),zod.null()]).optional().describe('Event Study で表示する処置後の最大期間数。null の場合はデータ内の全処置後期間を使用します。'),
  "missingValueHandling": zod.enum(['ignore', 'remove', 'error']).default(didAnalysisBodyMissingValueHandlingDefault).describe('欠損値の処理方法。remove: 該当行を削除、ignore: そのまま使用、error: エラーとして扱う。'),
  "standardError": zod.union([zod.object({
  "method": zod.enum(['nonrobust']).default(didAnalysisBodyStandardErrorOneMethodDefault)
}),zod.object({
  "method": zod.enum(['robust']).default(didAnalysisBodyStandardErrorTwoMethodDefault),
  "hcType": zod.enum(['HC0', 'HC1', 'HC2', 'HC3']).default(didAnalysisBodyStandardErrorTwoHcTypeDefault)
}),zod.object({
  "method": zod.enum(['cluster']).default(didAnalysisBodyStandardErrorThreeMethodDefault),
  "groups": zod.array(zod.string().min(1).describe('カラム名')).describe('クラスターを構成する列名'),
  "useCorrection": zod.boolean().default(didAnalysisBodyStandardErrorThreeUseCorrectionDefault).describe('小標本補正を行うか')
}),zod.object({
  "method": zod.enum(['hac']).default(didAnalysisBodyStandardErrorFourMethodDefault),
  "maxlags": zod.number().min(didAnalysisBodyStandardErrorFourMaxlagsMin).describe('考慮する最大ラグ数'),
  "kernel": zod.string().default(didAnalysisBodyStandardErrorFourKernelDefault).describe('カーネルの種類'),
  "useCorrection": zod.boolean().default(didAnalysisBodyStandardErrorFourUseCorrectionDefault).describe('小標本補正を行うか')
})]).describe('標準誤差の計算方法。DID では個体レベルのクラスタ標準誤差（cluster）を推奨します。'),
  "confidenceLevel": zod.number().min(didAnalysisBodyConfidenceLevelMin).max(didAnalysisBodyConfidenceLevelMax).default(didAnalysisBodyConfidenceLevelDefault).describe('信頼区間の水準（デフォルト: 0.95）')
}).describe('差の差（DID）分析リクエスト\n\nTwo-Way Fixed Effects（TWFE）による差の差推定と、\nオプションで Event Study を実行します。\n交差項（treated × post）はサービス層で自動生成します。')

export const didAnalysisResponseCodeDefault = `OK`;

export const DidAnalysisResponse = zod.object({
  "code": zod.string().default(didAnalysisResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "resultId": zod.string().describe('保存された分析結果の一意 ID')
}).describe('処理結果')
})

/**
 * 回帰不連続デザイン（RDD）分析エンドポイント

rdrobust による局所多項式推定で RDD の LATE を推定します。
バイアス補正済み推定・McCrary 密度検定・プラシーボ検定を包括的に返します。

Parameters
----------
request : Request
    FastAPI のリクエストオブジェクト
body : RDDRequestBody
    RDD 分析リクエスト
    - tableName: 対象テーブル名
    - outcomeVariable: 結果変数
    - runningVariable: 実行変数（強制変数）
    - cutoff: カットオフ値（デフォルト: 0）
    - kernel: カーネル関数 ('triangular' / 'epanechnikov' / 'uniform')
    - bwSelect: バンド幅自動選択アルゴリズム
    - h: 手動バンド幅（null の場合は自動選択）
    - p: 多項式次数（1: 線形, 2: 2次式）
    - vce: 標準誤差の計算方法
    - confidenceLevel: 信頼区間水準（デフォルト: 0.95）
    - nBins: 散布図用ビン数（デフォルト: 30）
    - placeboCutoffs: プラシーボ境界値リスト（null で自動生成）

Returns
-------
JSONResponse
    {"code": "OK", "result": {"resultId": "<uuid>"}}
    分析結果は GET /analysis/results/{resultId} で取得可能。
 * @summary Rdd Analysis
 */
export const RddAnalysisHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})


export const rddAnalysisBodyResultNameDefault = ``;
export const rddAnalysisBodyResultNameMax = 128;

export const rddAnalysisBodyDescriptionDefault = ``;
export const rddAnalysisBodyDescriptionMax = 512;



export const rddAnalysisBodyCutoffDefault = 0;
export const rddAnalysisBodyKernelDefault = `triangular`;
export const rddAnalysisBodyBwSelectDefault = `mserd`;
export const rddAnalysisBodyHOneExclusiveMin = 0;

export const rddAnalysisBodyPDefault = 1;
export const rddAnalysisBodyPMax = 4;

export const rddAnalysisBodyVceDefault = `hc1`;
export const rddAnalysisBodyConfidenceLevelDefault = 0.95;
export const rddAnalysisBodyConfidenceLevelMin = 0.5;
export const rddAnalysisBodyConfidenceLevelMax = 0.999;

export const rddAnalysisBodyNBinsDefault = 30;
export const rddAnalysisBodyNBinsMin = 10;
export const rddAnalysisBodyNBinsMax = 200;

export const rddAnalysisBodyPlaceboCutoffsOneMax = 10;



export const RddAnalysisBody = zod.object({
  "tableName": zod.string().min(1).describe('分析対象のテーブル名。ワークスペース内に存在するテーブル名を指定してください。'),
  "resultName": zod.string().max(rddAnalysisBodyResultNameMax).default(rddAnalysisBodyResultNameDefault).describe('分析結果の名前（省略時は自動生成）'),
  "description": zod.string().max(rddAnalysisBodyDescriptionMax).default(rddAnalysisBodyDescriptionDefault).describe('分析結果の説明メモ'),
  "outcomeVariable": zod.string().min(1).describe('結果変数（y）の列名。数値型カラムを指定してください。'),
  "runningVariable": zod.string().min(1).describe('実行変数（score \/ forcing variable）の列名。カットオフ前後で処置割り当てが決まる連続変数。数値型カラムを指定してください。'),
  "cutoff": zod.number().default(rddAnalysisBodyCutoffDefault).describe('カットオフ値。実行変数がこの値以上の観測を処置群とみなします。デフォルトは 0。'),
  "kernel": zod.enum(['triangular', 'epanechnikov', 'uniform']).default(rddAnalysisBodyKernelDefault).describe('カーネル重み付け関数。triangular（デフォルト）\/ epanechnikov \/ uniform。'),
  "bwSelect": zod.enum(['mserd', 'msetwo', 'msesum', 'msecomb1', 'msecomb2', 'cerrd', 'certwo', 'cersum', 'cercomb1', 'cercomb2']).default(rddAnalysisBodyBwSelectDefault).describe('バンド幅の自動選定アルゴリズム。mserd（デフォルト）: MSE 最小化・左右共通バンド幅。msetwo: MSE 最小化・左右独立バンド幅。cerrd\/certwo: CER（Coverage Error Rate）最小化。'),
  "h": zod.union([zod.number().gt(rddAnalysisBodyHOneExclusiveMin),zod.null()]).optional().describe('手動バンド幅。指定した場合 bwSelect による自動選択より優先されます。null の場合は bwSelect で自動選択します。'),
  "p": zod.number().min(1).max(rddAnalysisBodyPMax).default(rddAnalysisBodyPDefault).describe('局所多項式の次数、1（線形、デフォルト）または2（2次式）を推奨。バイアス補正バンド幅には p+1 次多項式が使用されます。'),
  "vce": zod.enum(['nn', 'hc1', 'hc3', 'cluster', 'nncluster']).default(rddAnalysisBodyVceDefault).describe('分散共分散行列の推定方式（標準誤差の計算方法）。nn: 最近傍法（デフォルト）。hc1 \/ hc3: HC 不均一分散一致推定量。cluster: クラスタ標準誤差。nncluster: 最近傍クラスタ標準誤差。'),
  "confidenceLevel": zod.number().min(rddAnalysisBodyConfidenceLevelMin).max(rddAnalysisBodyConfidenceLevelMax).default(rddAnalysisBodyConfidenceLevelDefault).describe('信頼区間の水準（デフォルト: 0.95 → 95%）'),
  "nBins": zod.number().min(rddAnalysisBodyNBinsMin).max(rddAnalysisBodyNBinsMax).default(rddAnalysisBodyNBinsDefault).describe('散布図用ビン数（左右合計）。デフォルト: 30（左右各 15 本）。'),
  "placeboCutoffs": zod.union([zod.array(zod.number()).max(rddAnalysisBodyPlaceboCutoffsOneMax),zod.null()]).optional().describe('プラシーボ検定用の偽境界値リスト。null の場合は実行変数の範囲に基づきカットオフ左右 ±5% 相当の 2 点を自動生成します。')
}).describe('回帰不連続デザイン（RDD）分析リクエスト\n\nrdrobust を使用したシャープ RDD 推定と診断を実行します。\nバイアス補正済み推定・密度検定・プラシーボ検定を包括的に返します。')

export const rddAnalysisResponseCodeDefault = `OK`;

export const RddAnalysisResponse = zod.object({
  "code": zod.string().default(rddAnalysisResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "resultId": zod.string().describe('保存された分析結果の一意 ID')
}).describe('処理結果')
})

/**
 * すべての分析結果のサマリーを取得

Returns
-------
JSONResponse
    分析結果のサマリーリスト
 * @summary Get All Analysis Results
 */
export const GetAllAnalysisResultsHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})

export const getAllAnalysisResultsResponseCodeDefault = `OK`;

export const GetAllAnalysisResultsResponse = zod.object({
  "code": zod.string().default(getAllAnalysisResultsResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "results": zod.array(zod.object({
  "id": zod.string().describe('分析結果の一意 ID'),
  "name": zod.string().describe('分析結果名'),
  "description": zod.string().describe('分析結果の説明メモ'),
  "createdAt": zod.string().describe('作成日時（ISO 8601 形式）')
}).describe('分析結果サマリー（一覧取得用の各要素）')).describe('分析結果のサマリーリスト')
}).describe('処理結果')
})

/**
 * すべての分析結果を削除

Returns
-------
JSONResponse
    削除成功メッセージ
 * @summary Clear All Analysis Results
 */
export const ClearAllAnalysisResultsHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})

export const clearAllAnalysisResultsResponseCodeDefault = `OK`;

export const ClearAllAnalysisResultsResponse = zod.object({
  "code": zod.string().default(clearAllAnalysisResultsResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "message": zod.string().describe('処理結果メッセージ')
}).describe('処理結果')
})

/**
 * 指定されたIDの分析結果を取得

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
result_id : str
    結果のID

Returns
-------
JSONResponse
    分析結果の詳細
 * @summary Get Analysis Result
 */
export const GetAnalysisResultParams = zod.object({
  "result_id": zod.string()
})

export const GetAnalysisResultHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})

export const getAnalysisResultResponseCodeDefault = `OK`;

export const GetAnalysisResultResponse = zod.object({
  "code": zod.string().default(getAnalysisResultResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "result": zod.object({
  "id": zod.string().describe('分析結果の一意 ID'),
  "name": zod.string().describe('分析結果名'),
  "description": zod.string().describe('分析結果の説明メモ'),
  "tableName": zod.string().describe('分析対象テーブル名'),
  "resultType": zod.string().describe('分析種別文字列（regression \/ confidence_interval \/ descriptive_statistics \/ statistical_test 等）'),
  "resultData": zod.record(zod.string(), zod.unknown()).describe('分析結果の詳細データ。分析種別（result_type）により含まれるキーが異なる。'),
  "createdAt": zod.string().describe('作成日時（ISO 8601 形式）'),
  "modelPath": zod.union([zod.string(),zod.null()]).describe('保存済みモデルファイルのパス（None の場合は未保存）'),
  "modelType": zod.union([zod.string(),zod.null()]).describe('モデルの種別文字列（ols \/ fe \/ re \/ iv 等）'),
  "entityIdColumn": zod.union([zod.string(),zod.null()]).describe('パネルデータ分析における個体 ID 列名'),
  "timeColumn": zod.union([zod.string(),zod.null()]).describe('パネルデータ分析における時間列名')
}).describe('分析結果の詳細データ')
}).describe('処理結果')
})

/**
 * 指定されたIDの分析結果を削除

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
result_id : str
    削除する結果のID

Returns
-------
JSONResponse
    削除成功メッセージ
 * @summary Delete Analysis Result
 */
export const DeleteAnalysisResultParams = zod.object({
  "result_id": zod.string()
})

export const DeleteAnalysisResultHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})

export const deleteAnalysisResultResponseCodeDefault = `OK`;

export const DeleteAnalysisResultResponse = zod.object({
  "code": zod.string().default(deleteAnalysisResultResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "deletedResultId": zod.string().describe('削除した分析結果の ID')
}).describe('処理結果')
})

/**
 * 推定結果をテキスト / Markdown / LaTeX 形式で整形出力する

指定した分析結果 ID のリストから係数表などを生成します。
複数 ID を指定するとモデル比較表を生成します。

Parameters
----------
request : Request
    FastAPI のリクエストオブジェクト
body : OutputResultRequest
    - resultIds: 出力する分析結果 ID のリスト（1件以上）
    - format: 出力形式（text / markdown / latex）
    - statInParentheses: 括弧内統計量（se / t / p / none）
    - significanceStars: 有意性記号の設定（省略時はデフォルト）
    - variableLabels: 変数名の表示ラベル辞書
    - constAtBottom: 定数項を最下部に表示するか

Returns
-------
JSONResponse
    整形済み出力テキストを含む成功レスポンス
 * @summary Output Result
 */
export const OutputResultHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})


export const outputResultBodyStatInParenthesesDefault = `se`;
export const outputResultBodyConstAtBottomDefault = true;

export const OutputResultBody = zod.object({
  "resultIds": zod.array(zod.string()).min(1).describe('出力する分析結果 ID のリスト（1件以上）'),
  "format": zod.enum(['latex', 'markdown', 'text']).describe('出力フォーマット。latex: LaTeX tabular、markdown: Markdown テーブル、text: 固定幅テキスト'),
  "statInParentheses": zod.enum(['se', 't', 'p', 'none']).default(outputResultBodyStatInParenthesesDefault).describe('括弧内に表示する統計量。se: 標準誤差、t: t 値、p: p 値、none: 括弧行なし'),
  "significanceStars": zod.union([zod.array(zod.object({
  "threshold": zod.number().describe('有意水準の閾値（例: 0.05）'),
  "symbol": zod.string().describe('有意性を示す記号（例: \'\*\*\'）')
}).describe('有意性記号の設定')),zod.null()]).optional().describe('有意性記号の設定リスト。None の場合はデフォルト設定を使用 (0.01:\*\*\*, 0.05:\*\*, 0.1:\*)'),
  "variableLabels": zod.union([zod.record(zod.string(), zod.string()),zod.null()]).optional().describe('変数名から表示ラベルへのマッピング辞書。未設定の変数は変数名をそのまま使用。'),
  "constAtBottom": zod.boolean().default(outputResultBodyConstAtBottomDefault).describe('True の場合、定数項を変数リストの最下部に配置する。'),
  "variableOrder": zod.union([zod.array(zod.string()),zod.null()]).optional().describe('変数の表示順序を明示的に指定するリスト。指定した変数は先頭から順に表示される。リストに含まれない変数はその後ろに追加される。None の場合は推定結果への登場順を使用。')
}).describe('推定結果フォーマット出力リクエスト\n\n複数の分析結果を LaTeX \/ Markdown \/ Text 形式に整形します。')

export const outputResultResponseCodeDefault = `OK`;

export const OutputResultResponse = zod.object({
  "code": zod.string().default(outputResultResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "content": zod.string().describe('フォーマット済み出力テキスト'),
  "format": zod.string().describe('出力フォーマット (latex \/ markdown \/ text)')
}).describe('処理結果')
})

