/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * 統合回帰分析エンドポイント

typeフィールドに応じて適切な分析手法を選択し、実行します。

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : RegressionRequestBody
    統合回帰分析リクエスト
    - type: 分析タイプ (ols, logit, probit, tobit, fe, re, iv,
      feiv, lasso, ridge)
    - tableName: 対象テーブル名
    - dependentVariable: 被説明変数
    - explanatoryVariables: 説明変数のリスト
    - その他分析固有のパラメータ

Returns
-------
JSONResponse
    分析結果またはエラーメッセージ
 * @summary Regression
 */
export const RegressionHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})


export const regressionBodyResultNameDefault = ``;
export const regressionBodyResultNameMax = 128;

export const regressionBodyDescriptionDefault = ``;
export const regressionBodyDescriptionMax = 512;



export const regressionBodyHasConstDefault = true;
export const regressionBodyMissingValueHandlingDefault = `remove`;
export const regressionBodyAnalysisTwoAlphaDefault = 1;
export const regressionBodyAnalysisTwoAlphaMin = 0;

export const regressionBodyAnalysisTwoCalculateSeDefault = false;
export const regressionBodyAnalysisTwoBootstrapIterationsDefault = 1000;
export const regressionBodyAnalysisTwoBootstrapIterationsMin = 100;
export const regressionBodyAnalysisTwoBootstrapIterationsMax = 10000;

export const regressionBodyAnalysisThreeRegularizationOneTypeDefault = `l1`;
export const regressionBodyAnalysisThreeRegularizationOneAlphaDefault = 1;
export const regressionBodyAnalysisThreeRegularizationOneAlphaMin = 0;

export const regressionBodyAnalysisThreeCalculateMarginalEffectsDefault = false;
export const regressionBodyAnalysisThreeBinaryResidualTypeDefault = `raw`;
export const regressionBodyAnalysisFourIvMethodDefault = `2sls`;

export const regressionBodyAnalysisFourGmmWeightMatrixDefault = `robust`;

export const regressionBodyAnalysisSixLeftCensoringLimitDefault = 0;



export const regressionBodyAnalysisSevenGmmWeightMatrixDefault = `robust`;
export const regressionBodyStandardErrorOneMethodDefault = `nonrobust`;
export const regressionBodyStandardErrorTwoMethodDefault = `robust`;
export const regressionBodyStandardErrorTwoHcTypeDefault = `HC1`;
export const regressionBodyStandardErrorThreeMethodDefault = `cluster`;
export const regressionBodyStandardErrorThreeUseCorrectionDefault = true;
export const regressionBodyStandardErrorFourMethodDefault = `hac`;
export const regressionBodyStandardErrorFourMaxlagsMin = 0;

export const regressionBodyStandardErrorFourKernelDefault = `bartlett`;
export const regressionBodyStandardErrorFourUseCorrectionDefault = true;

export const RegressionBody = zod.object({
  "tableName": zod.string().min(1).describe('分析対象のテーブル名。ワークスペース内に存在するテーブル名を指定してください。'),
  "resultName": zod.string().max(regressionBodyResultNameMax).default(regressionBodyResultNameDefault).describe('分析結果の名前（省略時は被説明変数名を使用）'),
  "description": zod.string().max(regressionBodyDescriptionMax).default(regressionBodyDescriptionDefault).describe('分析結果の説明メモ'),
  "dependentVariable": zod.string().min(1).describe('被説明変数（目的変数）の列名。テーブル内に存在するカラム名を指定してください。'),
  "explanatoryVariables": zod.array(zod.string().min(1).describe('カラム名')).describe('説明変数の列名のリスト。テーブル内に存在するカラム名を指定してください。'),
  "hasConst": zod.boolean().default(regressionBodyHasConstDefault).describe('定数項を設計行列に追加するかどうか'),
  "missingValueHandling": zod.enum(['ignore', 'remove', 'error']).default(regressionBodyMissingValueHandlingDefault).describe('欠損値の処理方法（remove: 該当行を削除、ignore: そのまま使用、error: エラーとして扱う）'),
  "analysis": zod.union([zod.object({
  "method": zod.enum(['ols'])
}),zod.object({
  "method": zod.enum(['lasso', 'ridge']),
  "alpha": zod.number().min(regressionBodyAnalysisTwoAlphaMin).default(regressionBodyAnalysisTwoAlphaDefault).describe('正則化強度のパラメータ'),
  "calculateSe": zod.boolean().default(regressionBodyAnalysisTwoCalculateSeDefault).describe('ブートストラップ法による標準誤差を計算するかどうか'),
  "bootstrapIterations": zod.number().min(regressionBodyAnalysisTwoBootstrapIterationsMin).max(regressionBodyAnalysisTwoBootstrapIterationsMax).default(regressionBodyAnalysisTwoBootstrapIterationsDefault).describe('ブートストラップ法のイテレーション回数'),
  "randomState": zod.union([zod.number(),zod.null()]).optional().describe('ブートストラップの乱数シード。None の場合は固定しない。実験の再現性を確保する場合は整数値を指定する。')
}),zod.object({
  "method": zod.enum(['logit', 'probit']),
  "regularization": zod.union([zod.object({
  "type": zod.enum(['l1', 'l2']).default(regressionBodyAnalysisThreeRegularizationOneTypeDefault),
  "alpha": zod.number().min(regressionBodyAnalysisThreeRegularizationOneAlphaMin).default(regressionBodyAnalysisThreeRegularizationOneAlphaDefault)
}),zod.null()]).optional(),
  "calculateMarginalEffects": zod.boolean().default(regressionBodyAnalysisThreeCalculateMarginalEffectsDefault).describe('平均限界効果(AME)を計算するかどうか'),
  "binaryResidualType": zod.enum(['raw', 'deviance']).default(regressionBodyAnalysisThreeBinaryResidualTypeDefault).describe('残差種別。raw: 生残差 (y - p̂)、deviance: デビアンス残差。Logit\/Probit のみ有効。')
}),zod.object({
  "method": zod.enum(['iv']),
  "ivMethod": zod.enum(['2sls', 'gmm']).default(regressionBodyAnalysisFourIvMethodDefault).describe('推定アルゴリズム。過剰識別かつ異分散がある場合はGMMを推奨'),
  "instrumentalVariables": zod.array(zod.string().min(1).describe('カラム名')),
  "endogenousVariables": zod.array(zod.string().min(1).describe('カラム名')),
  "gmmWeightMatrix": zod.enum(['uncentered', 'robust', 'hac']).default(regressionBodyAnalysisFourGmmWeightMatrixDefault)
}),zod.object({
  "method": zod.enum(['fe', 're']),
  "entityIdColumn": zod.string().min(1).describe('個体ID列名'),
  "timeColumn": zod.union([zod.string().min(1).describe('カラム名'),zod.null()]).optional().describe('時間列名')
}),zod.object({
  "method": zod.enum(['tobit']),
  "leftCensoringLimit": zod.union([zod.number(),zod.null()]).default(regressionBodyAnalysisSixLeftCensoringLimitDefault).describe('左側打ち切り値。この値以下のデータが打ち切られていると見なす'),
  "rightCensoringLimit": zod.union([zod.number(),zod.null()]).optional().describe('右側打ち切り値')
}),zod.object({
  "method": zod.enum(['feiv']),
  "entityIdColumn": zod.string().min(1).describe('個体ID列名'),
  "timeColumn": zod.union([zod.string().min(1).describe('カラム名'),zod.null()]).optional().describe('時間列名'),
  "instrumentalVariables": zod.array(zod.string().min(1).describe('カラム名')),
  "endogenousVariables": zod.array(zod.string().min(1).describe('カラム名')),
  "gmmWeightMatrix": zod.enum(['uncentered', 'robust', 'hac']).default(regressionBodyAnalysisSevenGmmWeightMatrixDefault)
})]).describe('回帰分析手法の詳細パラメータ。method フィールドで手法（ols, fe, re, iv 等）を指定します。'),
  "standardError": zod.union([zod.object({
  "method": zod.enum(['nonrobust']).default(regressionBodyStandardErrorOneMethodDefault)
}),zod.object({
  "method": zod.enum(['robust']).default(regressionBodyStandardErrorTwoMethodDefault),
  "hcType": zod.enum(['HC0', 'HC1', 'HC2', 'HC3']).default(regressionBodyStandardErrorTwoHcTypeDefault)
}),zod.object({
  "method": zod.enum(['cluster']).default(regressionBodyStandardErrorThreeMethodDefault),
  "groups": zod.array(zod.string().min(1).describe('カラム名')).describe('クラスターを構成する列名'),
  "useCorrection": zod.boolean().default(regressionBodyStandardErrorThreeUseCorrectionDefault).describe('小標本補正を行うか')
}),zod.object({
  "method": zod.enum(['hac']).default(regressionBodyStandardErrorFourMethodDefault),
  "maxlags": zod.number().min(regressionBodyStandardErrorFourMaxlagsMin).describe('考慮する最大ラグ数'),
  "kernel": zod.string().default(regressionBodyStandardErrorFourKernelDefault).describe('カーネルの種類'),
  "useCorrection": zod.boolean().default(regressionBodyStandardErrorFourUseCorrectionDefault).describe('小標本補正を行うか')
})]).describe('標準誤差の計算方法設定。nonrobust, robust（HC）, cluster, hac（Newey-West）から選択します。')
}).describe('統合回帰分析リクエスト\n\n全ての回帰分析タイプを単一のエンドポイントで扱うための\n統合スキーマです。')

export const RegressionResponse = zod.unknown()

/**
 * すべての分析結果のサマリーを取得

Returns
-------
JSONResponse
    分析結果のサマリーリスト
 * @summary Get All Analysis Results
 */
export const GetAllAnalysisResultsHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})

export const GetAllAnalysisResultsResponse = zod.unknown()

/**
 * すべての分析結果を削除

Returns
-------
JSONResponse
    削除成功メッセージ
 * @summary Clear All Analysis Results
 */
export const ClearAllAnalysisResultsHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})

export const ClearAllAnalysisResultsResponse = zod.unknown()

/**
 * 指定されたIDの分析結果を取得

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
result_id : str
    結果のID

Returns
-------
JSONResponse
    分析結果の詳細
 * @summary Get Analysis Result
 */
export const GetAnalysisResultParams = zod.object({
  "result_id": zod.string()
})

export const GetAnalysisResultHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})

export const GetAnalysisResultResponse = zod.unknown()

/**
 * 指定されたIDの分析結果を削除

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
result_id : str
    削除する結果のID

Returns
-------
JSONResponse
    削除成功メッセージ
 * @summary Delete Analysis Result
 */
export const DeleteAnalysisResultParams = zod.object({
  "result_id": zod.string()
})

export const DeleteAnalysisResultHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})

export const DeleteAnalysisResultResponse = zod.unknown()

/**
 * 推定済みモデルから予測値・残差を抽出してテーブルに列追加する

指定された分析結果 ID に対応するモデルをロードし、予測値・残差などの
診断列を元のテーブルに追加します。

Parameters
----------
request : Request
    FastAPI のリクエストオブジェクト
body : AddDiagnosticColumnsRequestBody
    - tableName: 追加先テーブル名
    - resultId: 分析結果の UUID
    - target: "fitted" / "residual" / "both"
    - standardized: 標準化残差を含めるか（OLS 系のみ有効）
    - includeInterval: 95%信頼区間を含めるか
    - feType: "total" または "within"（FE/RE のみ有効）

Returns
-------
JSONResponse
    追加したテーブル名と列名リスト
 * @summary Add Diagnostic Columns
 */
export const AddDiagnosticColumnsHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})


export const addDiagnosticColumnsBodyStandardizedDefault = false;
export const addDiagnosticColumnsBodyIncludeIntervalDefault = false;
export const addDiagnosticColumnsBodyFeTypeDefault = `total`;
export const addDiagnosticColumnsBodyBinaryResidualTypeDefault = `raw`;
export const addDiagnosticColumnsBodyTobitFittedTypeDefault = `latent`;

export const AddDiagnosticColumnsBody = zod.object({
  "tableName": zod.string().min(1).describe('追加先テーブル名。ワークスペース内に存在するテーブル名を指定してください。'),
  "resultId": zod.string().describe('対象の分析結果 ID（AnalysisResult の UUID）'),
  "target": zod.enum(['fitted', 'residual', 'both']).describe('追加する値の種類。fitted: 予測値のみ、residual: 残差のみ、both: 両方'),
  "standardized": zod.boolean().default(addDiagnosticColumnsBodyStandardizedDefault).describe('True の場合、標準化残差（studentized internal）を追加する。OLS\/Logit\/Probit のみ有効。'),
  "includeInterval": zod.boolean().default(addDiagnosticColumnsBodyIncludeIntervalDefault).describe('True の場合、予測値の 95%信頼区間列を追加する。OLS\/FE\/RE\/IV で有効。'),
  "feType": zod.enum(['total', 'within']).default(addDiagnosticColumnsBodyFeTypeDefault).describe('FE\/RE モデルの予測値タイプ。total: 固定効果を含む予測（effects=True）、within: 固定効果を除いた変動成分（effects=False）。FE\/RE 以外では無視される。'),
  "binaryResidualType": zod.enum(['raw', 'deviance']).default(addDiagnosticColumnsBodyBinaryResidualTypeDefault).describe('Logit\/Probit の残差種別。raw: 生残差 (y - p̂)、deviance: デビアンス残差 sign(y-p̂)√(-2[y·log(p̂)+(1-y)·log(1-p̂)])。OLS などその他のモデルでは無視される。'),
  "tobitFittedType": zod.enum(['latent', 'observable']).default(addDiagnosticColumnsBodyTobitFittedTypeDefault).describe('Tobit モデルの予測値種別。latent: 潜在変数の予測値 x\'β（デフォルト）、observable: 観測値の無条件期待値 E[y|x]（打ち切りを考慮した期待値）。Tobit 以外のモデルでは無視される。')
}).describe('推定済みモデルから予測値・残差を抽出してテーブルに列追加するリクエスト')

export const AddDiagnosticColumnsResponse = zod.unknown()

/**
 * 推定結果をテキスト / Markdown / LaTeX 形式で整形出力する

指定した分析結果 ID のリストから係数表などを生成します。
複数 ID を指定するとモデル比較表を生成します。

Parameters
----------
request : Request
    FastAPI のリクエストオブジェクト
body : OutputResultRequest
    - resultIds: 出力する分析結果 ID のリスト（1件以上）
    - format: 出力形式（text / markdown / latex）
    - statInParentheses: 括弧内統計量（se / t / p / none）
    - significanceStars: 有意性記号の設定（省略時はデフォルト）
    - variableLabels: 変数名の表示ラベル辞書
    - constAtBottom: 定数項を最下部に表示するか

Returns
-------
JSONResponse
    整形済み出力テキストを含む成功レスポンス
 * @summary Output Result
 */
export const OutputResultHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})


export const outputResultBodyStatInParenthesesDefault = `se`;
export const outputResultBodyConstAtBottomDefault = true;

export const OutputResultBody = zod.object({
  "resultIds": zod.array(zod.string()).min(1).describe('出力する分析結果 ID のリスト（1件以上）'),
  "format": zod.enum(['latex', 'markdown', 'text']).describe('出力フォーマット。latex: LaTeX tabular、markdown: Markdown テーブル、text: 固定幅テキスト'),
  "statInParentheses": zod.enum(['se', 't', 'p', 'none']).default(outputResultBodyStatInParenthesesDefault).describe('括弧内に表示する統計量。se: 標準誤差、t: t 値、p: p 値、none: 括弧行なし'),
  "significanceStars": zod.union([zod.array(zod.object({
  "threshold": zod.number().describe('有意水準の閾値（例: 0.05）'),
  "symbol": zod.string().describe('有意性を示す記号（例: \'\*\*\'）')
}).describe('有意性記号の設定')),zod.null()]).optional().describe('有意性記号の設定リスト。None の場合はデフォルト設定を使用 (0.01:\*\*\*, 0.05:\*\*, 0.1:\*)'),
  "variableLabels": zod.union([zod.record(zod.string(), zod.string()),zod.null()]).optional().describe('変数名から表示ラベルへのマッピング辞書。未設定の変数は変数名をそのまま使用。'),
  "constAtBottom": zod.boolean().default(outputResultBodyConstAtBottomDefault).describe('True の場合、定数項を変数リストの最下部に配置する。'),
  "variableOrder": zod.union([zod.array(zod.string()),zod.null()]).optional().describe('変数の表示順序を明示的に指定するリスト。指定した変数は先頭から順に表示される。リストに含まれない変数はその後ろに追加される。None の場合は推定結果への登場順を使用。')
}).describe('推定結果フォーマット出力リクエスト\n\n複数の分析結果を LaTeX \/ Markdown \/ Text 形式に整形します。')

export const OutputResultResponse = zod.unknown()

