/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * カラムを追加するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : AddColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Add Column Endpoint
 */
export const addColumnEndpointBodyTableNameMax = 255;

export const addColumnEndpointBodyNewColumnNameMax = 255;

export const addColumnEndpointBodyAddPositionColumnMax = 255;



export const AddColumnEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(addColumnEndpointBodyTableNameMax).describe('テーブル名'),
  "newColumnName": zod.string().min(1).max(addColumnEndpointBodyNewColumnNameMax).describe('新しいカラム名'),
  "addPositionColumn": zod.string().min(1).max(addColumnEndpointBodyAddPositionColumnMax).describe('追加位置のカラム名')
}).describe('カラム追加リクエスト')

export const addColumnEndpointResponseCodeDefault = `OK`;

export const AddColumnEndpointResponse = zod.object({
  "code": zod.string().default(addColumnEndpointResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string(),
  "columnName": zod.string()
}).describe('カラム追加レスポンス')
})

/**
 * ダミー変数カラムを追加するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : AddDummyColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Add Dummy Column Endpoint
 */
export const addDummyColumnEndpointBodyTableNameMax = 255;

export const addDummyColumnEndpointBodySourceColumnNameMax = 255;

export const addDummyColumnEndpointBodyDummyColumnNameMax = 255;



export const AddDummyColumnEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(addDummyColumnEndpointBodyTableNameMax).describe('テーブル名'),
  "sourceColumnName": zod.string().min(1).max(addDummyColumnEndpointBodySourceColumnNameMax).describe('元となるカラム名'),
  "dummyColumnName": zod.string().min(1).max(addDummyColumnEndpointBodyDummyColumnNameMax).describe('ダミー変数カラム名'),
  "targetValue": zod.string().describe('1にする対象の値')
}).describe('ダミー変数カラム追加リクエスト')

export const AddDummyColumnEndpointResponse = zod.unknown()

/**
 * カラムを削除するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DeleteColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Delete Column Endpoint
 */
export const deleteColumnEndpointBodyTableNameMax = 255;

export const deleteColumnEndpointBodyColumnNameMax = 255;



export const DeleteColumnEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(deleteColumnEndpointBodyTableNameMax).describe('テーブル名'),
  "columnName": zod.string().min(1).max(deleteColumnEndpointBodyColumnNameMax).describe('カラム名')
}).describe('カラム削除リクエスト')

export const DeleteColumnEndpointResponse = zod.unknown()

/**
 * 列名変更エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : RenameColumnNameRequest
    リクエストボディ
    - tableName: テーブル名
    - oldColumnName: 旧列名
    - newColumnName: 新列名

Returns
-------
JSONResponse
    処理結果
 * @summary Rename Column Endpoint
 */
export const renameColumnEndpointBodyTableNameMax = 255;

export const renameColumnEndpointBodyOldColumnNameMax = 255;

export const renameColumnEndpointBodyNewColumnNameMax = 255;



export const RenameColumnEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(renameColumnEndpointBodyTableNameMax).describe('テーブル名'),
  "oldColumnName": zod.string().min(1).max(renameColumnEndpointBodyOldColumnNameMax).describe('元のカラム名'),
  "newColumnName": zod.string().min(1).max(renameColumnEndpointBodyNewColumnNameMax).describe('新しいカラム名')
}).describe('カラム名変更リクエスト')

export const RenameColumnEndpointResponse = zod.unknown()

/**
 * ラグ・リードカラムを追加するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : AddLagLeadColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Add Lag Lead Column Endpoint
 */
export const addLagLeadColumnEndpointBodyTableNameMax = 255;

export const addLagLeadColumnEndpointBodySourceColumnMax = 255;

export const addLagLeadColumnEndpointBodyNewColumnNameMax = 255;



export const AddLagLeadColumnEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(addLagLeadColumnEndpointBodyTableNameMax).describe('テーブル名'),
  "sourceColumn": zod.string().min(1).max(addLagLeadColumnEndpointBodySourceColumnMax).describe('元となるカラム名'),
  "newColumnName": zod.string().min(1).max(addLagLeadColumnEndpointBodyNewColumnNameMax).describe('新しいカラム名'),
  "periods": zod.number().describe('ラグ・リード期間'),
  "groupColumns": zod.array(zod.string()).optional().describe('グループ化するカラムのリスト')
}).describe('ラグ・リードカラム追加リクエスト')

export const AddLagLeadColumnEndpointResponse = zod.unknown()

/**
 * シミュレーションカラムを追加するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : AddSimulationColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Add Simulation Column Endpoint
 */
export const addSimulationColumnEndpointBodyTableNameMax = 255;

export const addSimulationColumnEndpointBodyNewColumnNameMax = 255;




export const AddSimulationColumnEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(addSimulationColumnEndpointBodyTableNameMax).describe('テーブル名'),
  "newColumnName": zod.string().min(1).max(addSimulationColumnEndpointBodyNewColumnNameMax).describe('新しいカラム名'),
  "distributionType": zod.string().min(1).describe('分布の種類'),
  "distributionParams": zod.record(zod.string(), zod.unknown()).describe('分布のパラメータ')
}).describe('シミュレーションカラム追加リクエスト')

export const AddSimulationColumnEndpointResponse = zod.unknown()

/**
 * カラム計算を実行するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : StatisticsCalculateColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Calculate Column Endpoint
 */
export const calculateColumnEndpointBodyTableNameMax = 255;

export const calculateColumnEndpointBodyNewColumnNameMax = 255;




export const CalculateColumnEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(calculateColumnEndpointBodyTableNameMax).describe('テーブル名'),
  "newColumnName": zod.string().min(1).max(calculateColumnEndpointBodyNewColumnNameMax).describe('新しいカラム名'),
  "calculationExpression": zod.string().min(1).describe('計算式')
}).describe('カラム計算リクエスト')

export const CalculateColumnEndpointResponse = zod.unknown()

/**
 * カラムを複製するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DataDuplicateColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Duplicate Column Endpoint
 */
export const duplicateColumnEndpointBodyTableNameMax = 255;

export const duplicateColumnEndpointBodySourceColumnNameMax = 255;

export const duplicateColumnEndpointBodyNewColumnNameMax = 255;



export const DuplicateColumnEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(duplicateColumnEndpointBodyTableNameMax).describe('テーブル名'),
  "sourceColumnName": zod.string().min(1).max(duplicateColumnEndpointBodySourceColumnNameMax).describe('元のカラム名'),
  "newColumnName": zod.string().min(1).max(duplicateColumnEndpointBodyNewColumnNameMax).describe('新しいカラム名')
}).describe('カラム複製リクエスト')

export const DuplicateColumnEndpointResponse = zod.unknown()

/**
 * 列の変換処理エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : TransformColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Transform Column Endpoint
 */
export const transformColumnEndpointBodyTableNameMax = 255;

export const transformColumnEndpointBodySourceColumnNameMax = 255;

export const transformColumnEndpointBodyNewColumnNameMax = 255;




export const TransformColumnEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(transformColumnEndpointBodyTableNameMax).describe('テーブル名'),
  "sourceColumnName": zod.string().min(1).max(transformColumnEndpointBodySourceColumnNameMax).describe('元となるカラム名'),
  "newColumnName": zod.string().min(1).max(transformColumnEndpointBodyNewColumnNameMax).describe('新しい列名'),
  "transformMethod": zod.string().min(1).describe('変換メソッド'),
  "logBase": zod.union([zod.number(),zod.null()]).optional().describe('対数の底（オプション）'),
  "exponent": zod.union([zod.number(),zod.null()]).optional().describe('指数（オプション）'),
  "rootIndex": zod.union([zod.number(),zod.null()]).optional().describe('累乗根の次数（オプション）')
}).describe('カラム変換リクエスト')

export const TransformColumnEndpointResponse = zod.unknown()

/**
 * カラムリストを取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : GetColumnListRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Get Column List Endpoint
 */
export const getColumnListEndpointBodyTableNameMax = 255;

export const getColumnListEndpointBodyIsNumberOnlyDefault = `false`;

export const GetColumnListEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(getColumnListEndpointBodyTableNameMax).describe('対象テーブル名'),
  "isNumberOnly": zod.string().default(getColumnListEndpointBodyIsNumberOnlyDefault).describe('数値カラムのみ取得')
}).describe('カラムリスト取得リクエスト')

export const GetColumnListEndpointResponse = zod.unknown()

/**
 * 列のソート処理エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : SortColumnsRequest
    リクエストボディ
    - tableName: テーブル名
    - sortColumns: ソート列情報

Returns
-------
JSONResponse
    処理結果
 * @summary Sort Columns Endpoint
 */
export const sortColumnsEndpointBodyTableNameMax = 255;




export const SortColumnsEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(sortColumnsEndpointBodyTableNameMax).describe('テーブル名'),
  "sortColumns": zod.array(zod.record(zod.string(), zod.string())).min(1).describe('ソート設定のリスト')
}).describe('カラムソートリクエスト')

export const SortColumnsEndpointResponse = zod.unknown()

