/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */
import * as zod from 'zod';


/**
 * ダミー変数カラムを追加するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : AddDummyColumnRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Add Dummy Column
 */
export const AddDummyColumnHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})




export const addDummyColumnBodyModeDefault = `single`;
export const addDummyColumnBodyDummyColumnNameOneMax = 128;


export const addDummyColumnBodyDummyColumnNameOneRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');

export const addDummyColumnBodyNullStrategyDefault = `exclude`;

export const AddDummyColumnBody = zod.object({
  "tableName": zod.string().min(1).describe('操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。'),
  "sourceColumnName": zod.string().min(1).describe('ダミー変数を作成する元となるカラム名。ワークスペースに存在するテーブルの中から指定してください。'),
  "addPositionColumn": zod.string().min(1).describe('追加位置のカラム名。指定したカラムの右隣に新しいカラムが追加されます。既存のカラム名から指定してください。'),
  "mode": zod.enum(['single', 'all_except_base']).default(addDummyColumnBodyModeDefault).describe('ダミー化モード。\'single\': 特定の1値をダミー化する。\'all_except_base\': 基準値を除いた全カテゴリを一括ダミー化する。'),
  "dummyColumnName": zod.union([zod.string().min(1).max(addDummyColumnBodyDummyColumnNameOneMax).regex(addDummyColumnBodyDummyColumnNameOneRegExp).describe('新しいカラム名'),zod.null()]).optional().describe('新しいカラム名。single モード時は必須。all_except_base モードでは無視され、{source}_{value} 形式で自動生成されます。'),
  "targetValue": zod.union([zod.string().min(1),zod.null()]).optional().describe('single モード時のみ必須。列に存在する1にする対象の値。'),
  "dropBaseValue": zod.union([zod.string(),zod.null()]).optional().describe('all_except_base モード時のみ必須。ダミー化から除外する基準カテゴリ値。\'auto_most_frequent\' を指定すると最頻値を自動選択します。'),
  "nullStrategy": zod.enum(['exclude', 'as_category', 'error']).default(addDummyColumnBodyNullStrategyDefault).describe('null値（空文字・空白を含む）の扱い。\'exclude\': null を無視してダミーを生成しない。\'as_category\': null を \'__null__\' カテゴリとして扱う。\'error\': null が存在する場合エラーを返す。')
}).describe('ダミー変数カラム追加リクエスト')

export const addDummyColumnResponseCodeDefault = `OK`;

export const AddDummyColumnResponse = zod.object({
  "code": zod.string().default(addDummyColumnResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('ダミーカラムを追加したテーブル名'),
  "addedColumnNames": zod.array(zod.string()).describe('追加したダミーカラム名のリスト')
}).describe('処理結果')
})

/**
 * カラムを削除するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DeleteColumnRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Delete Column
 */
export const DeleteColumnHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})





export const DeleteColumnBody = zod.object({
  "tableName": zod.string().min(1).describe('列を削除するテーブル名。ワークスペースに存在するテーブルの中から指定してください。'),
  "columnName": zod.string().min(1).describe('削除するカラム名。ワークスペースに存在するテーブルの中から指定してください。')
}).describe('カラム削除リクエスト')

export const deleteColumnResponseCodeDefault = `OK`;

export const DeleteColumnResponse = zod.object({
  "code": zod.string().default(deleteColumnResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('カラムを削除したテーブル名')
}).describe('処理結果')
})

/**
 * 列名変更エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : RenameColumnRequestBody
    リクエストボディ
    - tableName: テーブル名
    - oldColumnName: 旧列名
    - newColumnName: 新列名

Returns
-------
JSONResponse
    処理結果
 * @summary Rename Column
 */
export const RenameColumnHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})



export const renameColumnBodyNewColumnNameMax = 128;


export const renameColumnBodyNewColumnNameRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');


export const RenameColumnBody = zod.object({
  "tableName": zod.string().min(1).describe('カラム名を変更するテーブル名。ワークスペースに存在するテーブルの中から指定してください。'),
  "oldColumnName": zod.string().min(1).describe('変更前のカラム名。ワークスペースに存在するテーブルの中から指定してください。'),
  "newColumnName": zod.string().min(1).max(renameColumnBodyNewColumnNameMax).regex(renameColumnBodyNewColumnNameRegExp).describe('新しいカラム名。既存のカラム名と重複しない名前を指定してください。')
}).describe('カラム名変更リクエスト')

export const renameColumnResponseCodeDefault = `OK`;

export const RenameColumnResponse = zod.object({
  "code": zod.string().default(renameColumnResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('カラム名を変更したテーブル名'),
  "columnName": zod.string().describe('変更後のカラム名')
}).describe('処理結果')
})

/**
 * ラグ・リードカラムを追加するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : AddLagLeadColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Add Lag Lead Column
 */
export const AddLagLeadColumnHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})



export const addLagLeadColumnBodyNewColumnNameMax = 128;


export const addLagLeadColumnBodyNewColumnNameRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');




export const AddLagLeadColumnBody = zod.object({
  "tableName": zod.string().min(1).describe('操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。'),
  "sourceColumn": zod.string().min(1).describe('ラグ・リードの元となるカラム名。ワークスペースに存在するテーブルの中から指定してください。'),
  "newColumnName": zod.string().min(1).max(addLagLeadColumnBodyNewColumnNameMax).regex(addLagLeadColumnBodyNewColumnNameRegExp).describe('新しいカラム名。既存のカラム名と重複しない名前を指定してください。'),
  "addPositionColumn": zod.string().min(1).describe('追加位置のカラム名。指定したカラムの右隣に新しいカラムが追加されます。既存のカラム名から指定してください。'),
  "periods": zod.number().describe('ラグ・リードの期間。負の値（-1, -2...）はラグ変数、正の値（1, 2...）はリード変数を作成します。例えば、-1を指定すると1行前の値（ラグ1）、1を指定すると1行後の値（リード1）が新しいカラムに入ります。'),
  "groupColumns": zod.array(zod.string().min(1).describe('カラム名')).optional().describe('ラグ・リードのグループ化に使用するカラムのリスト。指定したカラムの組み合わせごとにラグ・リードが計算されます。例えば、都市ごとにラグ・リードを計算したい場合は、[\'city\']や[\'都市\']を指定してください。複数カラムを指定することもできます。既存カラム名から指定してください。')
}).describe('ラグ・リードカラム追加リクエスト')

export const addLagLeadColumnResponseCodeDefault = `OK`;

export const AddLagLeadColumnResponse = zod.object({
  "code": zod.string().default(addLagLeadColumnResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('ラグ・リードカラムを追加したテーブル名'),
  "columnName": zod.string().describe('追加したラグ・リードカラム名')
}).describe('処理結果')
})

/**
 * シミュレーションカラムを追加するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : AddSimulationColumnRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Add Simulation Column
 */
export const AddSimulationColumnHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})


export const addSimulationColumnBodySimulationColumnColumnNameMax = 128;


export const addSimulationColumnBodySimulationColumnColumnNameRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');
export const addSimulationColumnBodySimulationColumnDistributionOneTwoScaleExclusiveMin = 0;

export const addSimulationColumnBodySimulationColumnDistributionOneThreeScaleExclusiveMin = 0;

export const addSimulationColumnBodySimulationColumnDistributionOneFourShapeExclusiveMin = 0;

export const addSimulationColumnBodySimulationColumnDistributionOneFourScaleExclusiveMin = 0;

export const addSimulationColumnBodySimulationColumnDistributionOneFiveAExclusiveMin = 0;

export const addSimulationColumnBodySimulationColumnDistributionOneFiveBExclusiveMin = 0;

export const addSimulationColumnBodySimulationColumnDistributionOneSixAExclusiveMin = 0;

export const addSimulationColumnBodySimulationColumnDistributionOneSixScaleExclusiveMin = 0;

export const addSimulationColumnBodySimulationColumnDistributionOneSevenSigmaExclusiveMin = 0;

export const addSimulationColumnBodySimulationColumnDistributionOneEightNExclusiveMin = 0;

export const addSimulationColumnBodySimulationColumnDistributionOneEightPExclusiveMin = 0;
export const addSimulationColumnBodySimulationColumnDistributionOneEightPMax = 1;

export const addSimulationColumnBodySimulationColumnDistributionOneNinePExclusiveMin = 0;
export const addSimulationColumnBodySimulationColumnDistributionOneNinePMax = 1;

export const addSimulationColumnBodySimulationColumnDistributionOneOnezeroLamExclusiveMin = 0;

export const addSimulationColumnBodySimulationColumnDistributionOneOneonePExclusiveMin = 0;
export const addSimulationColumnBodySimulationColumnDistributionOneOneonePMax = 1;

export const addSimulationColumnBodySimulationColumnDistributionOneOnetwoPopulationSizeExclusiveMin = 0;

export const addSimulationColumnBodySimulationColumnDistributionOneOnetwoSuccessCountExclusiveMin = 0;

export const addSimulationColumnBodySimulationColumnDistributionOneOnetwoSampleSizeExclusiveMin = 0;

export const addSimulationColumnBodySimulationColumnDistributionOneOnethreeNExclusiveMin = 0;

export const addSimulationColumnBodySimulationColumnDistributionOneOnethreePExclusiveMin = 0;
export const addSimulationColumnBodySimulationColumnDistributionOneOnethreePMax = 1;


export const addSimulationColumnBodyRandomSeedOneMin = 0;
export const addSimulationColumnBodyRandomSeedOneMax = 100000000;



export const AddSimulationColumnBody = zod.object({
  "tableName": zod.string().min(1).describe('操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。'),
  "simulationColumn": zod.object({
  "columnName": zod.string().min(1).max(addSimulationColumnBodySimulationColumnColumnNameMax).regex(addSimulationColumnBodySimulationColumnColumnNameRegExp).describe('新しいカラム名'),
  "distribution": zod.union([zod.object({
  "type": zod.literal("uniform").describe('分布の種類'),
  "low": zod.number().describe('分布の下限'),
  "high": zod.number().describe('分布の上限')
}).describe('一様分布のパラメータ'),zod.object({
  "type": zod.literal("exponential").describe('分布の種類'),
  "scale": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneTwoScaleExclusiveMin).describe('尺度パラメータ')
}).describe('指数分布のパラメータ'),zod.object({
  "type": zod.literal("normal").describe('分布の種類'),
  "loc": zod.number().describe('平均'),
  "scale": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneThreeScaleExclusiveMin).describe('標準偏差')
}).describe('正規分布のパラメータ'),zod.object({
  "type": zod.literal("gamma").describe('分布の種類'),
  "shape": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneFourShapeExclusiveMin).describe('形状パラメータ'),
  "scale": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneFourScaleExclusiveMin).describe('尺度パラメータ')
}).describe('ガンマ分布のパラメータ'),zod.object({
  "type": zod.literal("beta").describe('分布の種類'),
  "a": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneFiveAExclusiveMin).describe('形状パラメータa'),
  "b": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneFiveBExclusiveMin).describe('形状パラメータb')
}).describe('ベータ分布のパラメータ'),zod.object({
  "type": zod.literal("weibull").describe('分布の種類'),
  "a": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneSixAExclusiveMin).describe('形状パラメータ'),
  "scale": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneSixScaleExclusiveMin).describe('尺度パラメータ')
}).describe('ワイブル分布のパラメータ'),zod.object({
  "type": zod.literal("lognormal").describe('分布の種類'),
  "mean": zod.number().describe('平均'),
  "sigma": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneSevenSigmaExclusiveMin).describe('標準偏差')
}).describe('対数正規分布のパラメータ'),zod.object({
  "type": zod.literal("binomial").describe('分布の種類'),
  "n": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneEightNExclusiveMin).describe('試行回数'),
  "p": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneEightPExclusiveMin).max(addSimulationColumnBodySimulationColumnDistributionOneEightPMax).describe('成功確率')
}).describe('二項分布のパラメータ'),zod.object({
  "type": zod.literal("bernoulli").describe('分布の種類'),
  "p": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneNinePExclusiveMin).max(addSimulationColumnBodySimulationColumnDistributionOneNinePMax).describe('成功確率')
}).describe('ベルヌーイ分布のパラメータ'),zod.object({
  "type": zod.literal("poisson").describe('分布の種類'),
  "lam": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneOnezeroLamExclusiveMin).describe('発生率')
}).describe('ポアソン分布のパラメータ'),zod.object({
  "type": zod.literal("geometric").describe('分布の種類'),
  "p": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneOneonePExclusiveMin).max(addSimulationColumnBodySimulationColumnDistributionOneOneonePMax).describe('成功確率')
}).describe('幾何分布のパラメータ'),zod.object({
  "type": zod.literal("hypergeometric").describe('分布の種類'),
  "populationSize": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneOnetwoPopulationSizeExclusiveMin).describe('母集団サイズ'),
  "successCount": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneOnetwoSuccessCountExclusiveMin).describe('成功要素数'),
  "sampleSize": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneOnetwoSampleSizeExclusiveMin).describe('標本サイズ')
}).describe('超幾何分布のパラメータ'),zod.object({
  "type": zod.literal("negative_binomial").describe('分布の種類'),
  "n": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneOnethreeNExclusiveMin).describe('成功回数'),
  "p": zod.number().gt(addSimulationColumnBodySimulationColumnDistributionOneOnethreePExclusiveMin).max(addSimulationColumnBodySimulationColumnDistributionOneOnethreePMax).describe('成功確率')
}).describe('負の二項分布のパラメータ\n\nn 回成功するまでに必要な失敗回数をシミュレートする。\nイベント発生強度の過分散モデリングに広く使われる。'),zod.object({
  "type": zod.literal("fixed").describe('分布の種類'),
  "value": zod.union([zod.number(),zod.number()]).describe('固定値')
}).describe('固定値のパラメータ')]).and(zod.object({
  "type": zod.enum(['bernoulli', 'beta', 'binomial', 'exponential', 'fixed', 'gamma', 'geometric', 'hypergeometric', 'lognormal', 'negative_binomial', 'normal', 'poisson', 'uniform', 'weibull'])
})).describe('分布設定')
}).describe('シミュレーションカラムの設定。'),
  "addPositionColumn": zod.string().min(1).describe('追加位置のカラム名。指定したカラムの右隣に新しいカラムが追加されます。既存のカラム名から指定してください。'),
  "randomSeed": zod.union([zod.number().min(addSimulationColumnBodyRandomSeedOneMin).max(addSimulationColumnBodyRandomSeedOneMax),zod.null()]).optional().describe('乱数シード値（0以上1億以下の整数）。同じシードを指定すると同じ結果が再現されます。None の場合は毎回異なる結果になります。')
}).describe('シミュレーションカラム追加リクエスト')

export const addSimulationColumnResponseCodeDefault = `OK`;

export const AddSimulationColumnResponse = zod.object({
  "code": zod.string().default(addSimulationColumnResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('シミュレーションカラムを追加したテーブル名'),
  "columnName": zod.string().describe('追加したシミュレーションカラム名'),
  "distributionType": zod.enum(['uniform', 'exponential', 'normal', 'gamma', 'beta', 'weibull', 'lognormal', 'binomial', 'bernoulli', 'poisson', 'geometric', 'hypergeometric', 'negative_binomial', 'fixed']).describe('使用した分布タイプ')
}).describe('処理結果')
})

/**
 * カラム計算を実行するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CalculateColumnRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Calculate Column
 */
export const CalculateColumnHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})


export const calculateColumnBodyNewColumnNameMax = 128;


export const calculateColumnBodyNewColumnNameRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');




export const CalculateColumnBody = zod.object({
  "tableName": zod.string().min(1).describe('操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。'),
  "newColumnName": zod.string().min(1).max(calculateColumnBodyNewColumnNameMax).regex(calculateColumnBodyNewColumnNameRegExp).describe('新しいカラム名。既存のカラム名と重複しない名前を指定してください。'),
  "addPositionColumn": zod.string().min(1).describe('追加位置のカラム名。指定したカラムの右隣に新しいカラムが追加されます。既存のカラム名から指定してください。'),
  "calculationExpression": zod.string().min(1).describe('計算式。数値カラム名をpl.col(\'price\')の形式で指定し、四則演算や関数を組み合わせて計算式を定義してください。例: ({population} \/ {area}) \* 1000\')')
}).describe('カラム計算リクエスト')

export const calculateColumnResponseCodeDefault = `OK`;

export const CalculateColumnResponse = zod.object({
  "code": zod.string().default(calculateColumnResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('計算カラムを追加したテーブル名'),
  "columnName": zod.string().describe('追加した計算カラム名')
}).describe('処理結果')
})

/**
 * カラムを複製するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DuplicateColumnRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Duplicate Column
 */
export const DuplicateColumnHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})



export const duplicateColumnBodyNewColumnNameMax = 128;


export const duplicateColumnBodyNewColumnNameRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');



export const DuplicateColumnBody = zod.object({
  "tableName": zod.string().min(1).describe('操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。'),
  "sourceColumnName": zod.string().min(1).describe('元となるカラム名。ワークスペースに存在するテーブルの中から指定してください。'),
  "newColumnName": zod.string().min(1).max(duplicateColumnBodyNewColumnNameMax).regex(duplicateColumnBodyNewColumnNameRegExp).describe('新しいカラム名。既存のカラム名と重複しない名前を指定してください。'),
  "addPositionColumn": zod.string().min(1).describe('追加位置のカラム名。指定したカラムの右隣に新しいカラムが追加されます。既存のカラム名から指定してください。')
}).describe('カラム複製リクエスト')

export const duplicateColumnResponseCodeDefault = `OK`;

export const DuplicateColumnResponse = zod.object({
  "code": zod.string().default(duplicateColumnResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('複製操作を行ったテーブル名'),
  "columnName": zod.string().describe('複製後の新しいカラム名')
}).describe('処理結果')
})

/**
 * 列の変換処理エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : TransformColumnRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Transform Column
 */
export const TransformColumnHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})



export const transformColumnBodyNewColumnNameMax = 128;


export const transformColumnBodyNewColumnNameRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');

export const transformColumnBodyTransformMethodOneOneLogBaseOneExclusiveMin = 0;

export const transformColumnBodyTransformMethodOneTwoExponentDefault = 2;
export const transformColumnBodyTransformMethodOneThreeRootIndexDefault = 2;
export const transformColumnBodyTransformMethodOneThreeRootIndexExclusiveMin = 0;



export const TransformColumnBody = zod.object({
  "tableName": zod.string().min(1).describe('テーブル名'),
  "sourceColumnName": zod.string().min(1).describe('元となるカラム名'),
  "newColumnName": zod.string().min(1).max(transformColumnBodyNewColumnNameMax).regex(transformColumnBodyNewColumnNameRegExp).describe('新しいカラム名。既存のカラム名と重複しない名前を指定してください。'),
  "addPositionColumn": zod.string().min(1).describe('追加位置のカラム名。指定したカラムの右隣に新しいカラムが追加されます。既存のカラム名から指定してください。'),
  "transformMethod": zod.union([zod.object({
  "method": zod.literal("log").describe('変換方法'),
  "logBase": zod.union([zod.number().gt(transformColumnBodyTransformMethodOneOneLogBaseOneExclusiveMin),zod.null()]).optional().describe('対数の底 (省略時は自然対数)')
}).describe('対数変換のパラメータ'),zod.object({
  "method": zod.literal("power").describe('変換方法'),
  "exponent": zod.number().default(transformColumnBodyTransformMethodOneTwoExponentDefault).describe('べき乗の指数 (省略時は2乗)')
}).describe('べき乗変換のパラメータ'),zod.object({
  "method": zod.literal("root").describe('変換方法'),
  "rootIndex": zod.number().gt(transformColumnBodyTransformMethodOneThreeRootIndexExclusiveMin).default(transformColumnBodyTransformMethodOneThreeRootIndexDefault).describe('ルートの指数 (省略時は平方根)')
}).describe('平方根変換のパラメータ')]).and(zod.object({
  "method": zod.enum(['log', 'power', 'root'])
})).describe('変換方法設定')
}).describe('カラム変換リクエスト')

export const transformColumnResponseCodeDefault = `OK`;

export const TransformColumnResponse = zod.object({
  "code": zod.string().default(transformColumnResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('変換カラムを追加したテーブル名'),
  "columnName": zod.string().describe('追加した変換カラム名')
}).describe('処理結果')
})

/**
 * カラムリストを取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : GetColumnListRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Get Column List
 */
export const GetColumnListHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})


export const getColumnListBodyIsNumberOnlyDefault = false;

export const GetColumnListBody = zod.object({
  "tableName": zod.string().min(1).describe('操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。'),
  "isNumberOnly": zod.boolean().default(getColumnListBodyIsNumberOnlyDefault).describe('数値カラムのみ取得するかどうか。Trueを指定すると、数値カラムのみが返されます。Falseを指定すると、全てのカラムが返されます。')
}).describe('カラムリスト取得リクエスト')

export const getColumnListResponseCodeDefault = `OK`;

export const GetColumnListResponse = zod.object({
  "code": zod.string().default(getColumnListResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('カラムリストを取得したテーブル名'),
  "columnInfoList": zod.array(zod.object({
  "name": zod.string().describe('カラム名'),
  "type": zod.string().describe('Polarsデータ型（例: Int64, Float64, String）')
}).describe('カラム情報')).describe('カラム情報のリスト')
}).describe('処理結果')
})

/**
 * 列のソート処理エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : SortColumnsRequestBody
    リクエストボディ
    - tableName: テーブル名
    - sortColumns: ソート列情報

Returns
-------
JSONResponse
    処理結果
 * @summary Sort Columns
 */
export const SortColumnsHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})






export const SortColumnsBody = zod.object({
  "tableName": zod.string().min(1).describe('操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。'),
  "sortColumns": zod.array(zod.object({
  "columnName": zod.string().min(1).describe('カラム名'),
  "ascending": zod.boolean()
})).min(1).describe('ソート設定のリスト。ソートするカラム名と昇順・降順の指定を組み合わせて、複数カラムでのソートも可能です。既存カラム名から指定してください。')
}).describe('カラムソートリクエスト')

export const sortColumnsResponseCodeDefault = `OK`;

export const SortColumnsResponse = zod.object({
  "code": zod.string().default(sortColumnsResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('ソートを実行したテーブル名')
}).describe('処理結果')
})

/**
 * 列型変換エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CastColumnRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Cast Column
 */
export const CastColumnHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})



export const castColumnBodyNewColumnNameMax = 128;


export const castColumnBodyNewColumnNameRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');

export const castColumnBodyCleanupWhitespaceDefault = true;
export const castColumnBodyRemoveCommasDefault = true;
export const castColumnBodyStrictDefault = false;

export const CastColumnBody = zod.object({
  "tableName": zod.string().min(1).describe('操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。'),
  "sourceColumnName": zod.string().min(1).describe('変換元となるカラム名。ワークスペースに存在するテーブルの中から指定してください。'),
  "targetType": zod.enum(['float', 'int', 'str', 'bool', 'date', 'datetime']).describe('変換先のデータ型。float \/ int \/ str \/ bool \/ date \/ datetime から選択。'),
  "newColumnName": zod.string().min(1).max(castColumnBodyNewColumnNameMax).regex(castColumnBodyNewColumnNameRegExp).describe('新しいカラム名。既存のカラム名と重複しない名前を指定してください。'),
  "addPositionColumn": zod.string().min(1).describe('追加位置のカラム名。指定したカラムの右隣に新しいカラムが追加されます。既存のカラム名から指定してください。'),
  "cleanupWhitespace": zod.boolean().default(castColumnBodyCleanupWhitespaceDefault).describe('前後の空白を削除するか。変換元が文字列型の場合のみ有効。'),
  "removeCommas": zod.boolean().default(castColumnBodyRemoveCommasDefault).describe('カンマ(,)を削除するか。数値型変換時に \'1,234\' → \'1234\' のような前処理に使用。変換元が文字列型の場合のみ有効。'),
  "datetimeFormat": zod.union([zod.string(),zod.null()]).optional().describe('date \/ datetime 変換時のパース書式。例: \'%Y-%m-%d\', \'%Y\/%m\/%d\'。None の場合は Polars が自動推定します。'),
  "strict": zod.boolean().default(castColumnBodyStrictDefault).describe('True なら変換失敗時に 400 エラーを返す。False なら変換失敗した値を null にして処理を続行する。')
}).describe('列型変換リクエスト')

export const castColumnResponseCodeDefault = `OK`;

export const CastColumnResponse = zod.object({
  "code": zod.string().default(castColumnResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('型変換カラムを追加したテーブル名'),
  "columnName": zod.string().describe('追加した型変換カラム名')
}).describe('処理結果')
})

/**
 * 列を指定した位置に移動するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : MoveColumnRequestBody
    リクエストボディ
    - tableName: テーブル名
    - columnName: 移動する列名
    - anchorColumnName: 挿入基準列名（null のとき末尾に移動）

Returns
-------
JSONResponse
    処理結果
 * @summary Move Column
 */
export const MoveColumnHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})






export const MoveColumnBody = zod.object({
  "tableName": zod.string().min(1).describe('操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。'),
  "columnName": zod.string().min(1).describe('移動する列名。既存の列名から指定してください。'),
  "anchorColumnName": zod.union([zod.string().min(1).describe('カラム名'),zod.null()]).optional().describe('挿入基準列名。指定した列の直前に移動列を挿入します。null を指定した場合は末尾に移動します。')
}).describe('列移動リクエスト')

export const moveColumnResponseCodeDefault = `OK`;

export const MoveColumnResponse = zod.object({
  "code": zod.string().default(moveColumnResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('列を移動したテーブル名'),
  "columnNames": zod.array(zod.string()).describe('移動後の全列名リスト（順序付き）')
}).describe('処理結果')
})

