/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * アプリケーション設定を取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト

Returns
-------
JSONResponse
    処理結果
 * @summary Get Settings Endpoint
 */
export const GetSettingsEndpointApiSettingGetSettingsGetResponse = zod.unknown()

