/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * アプリケーション設定を取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト

Returns
-------
JSONResponse
    処理結果
 * @summary Get Settings
 */
export const getSettingsResponseCodeDefault = `OK`;

export const GetSettingsResponse = zod.object({
  "code": zod.string().default(getSettingsResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "osName": zod.string().describe('実行環境のOS名（Windows \/ macOS \/ Linux）'),
  "language": zod.string().describe('アプリケーションの表示言語（ja: 日本語, en: 英語）'),
  "lastOpenedPath": zod.string().describe('最後に開いたフォルダパス'),
  "theme": zod.string().describe('アプリケーションのテーマ（light \/ dark）'),
  "encoding": zod.string().describe('ファイルエンコーディング'),
  "logPath": zod.string().describe('ログファイルの出力先パス')
}).describe('アプリケーション設定取得レスポンス')
})

