/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * カラム追加レスポンス
 */
export type AddColumnResult = {
  /** カラムを追加したテーブル名 */
  tableName: string;
  /** 追加したカラム名 */
  columnName: string;
};
