/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

/**
 * カラム追加レスポンス
 */
export interface AddColumnResult {
  tableName: string;
  columnName: string;
}
