/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * CSV のエンコーディング。file_path が CSV の場合のみ有効。
 */
export type AddColumnRequestBodyCsvEncoding = typeof AddColumnRequestBodyCsvEncoding[keyof typeof AddColumnRequestBodyCsvEncoding];


export const AddColumnRequestBodyCsvEncoding = {
  utf8: 'utf8',
  latin1: 'latin1',
  ascii: 'ascii',
  gbk: 'gbk',
  'windows-1252': 'windows-1252',
  shift_jis: 'shift_jis',
} as const;
