/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 診断列追加レスポンス
 */
export type AddDiagnosticColumnsResult = {
  /** 更新されたテーブル名 */
  tableName: string;
  /** 追加された列名のリスト */
  addedColumns: string[];
};
