/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * ダミー変数カラム追加リクエスト
 */
export interface AddDummyColumnRequestBody {
  /**
   * 操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。
   * @minLength 1
   */
  tableName: string;
  /**
   * ダミー変数を作成する元となるカラム名。ワークスペースに存在するテーブルの中から指定してください。
   * @minLength 1
   */
  sourceColumnName: string;
  /**
   * 新しいカラム名。既存のカラム名と重複しない名前を指定してください。
   * @minLength 1
   * @maxLength 128
   * @pattern ^[^\x00-\x1f\x7f]+$
   */
  dummyColumnName: string;
  /**
   * 追加位置のカラム名。指定したカラムの右隣に新しいカラムが追加されます。既存のカラム名から指定してください。
   * @minLength 1
   */
  addPositionColumn: string;
  /**
   * 列に存在する1にする対象の値。例えば、元の列が都市名で、東京を1、それ以外を0にしたい場合は、'Tokyo'や'東京'を指定してください。
   * @minLength 1
   */
  targetValue: string;
}
