/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { AddDiagnosticColumnsRequestBodyBinaryResidualType } from './addDiagnosticColumnsRequestBodyBinaryResidualType';
import type { AddDiagnosticColumnsRequestBodyFeType } from './addDiagnosticColumnsRequestBodyFeType';
import type { AddDiagnosticColumnsRequestBodyTarget } from './addDiagnosticColumnsRequestBodyTarget';
import type { AddDiagnosticColumnsRequestBodyTobitFittedType } from './addDiagnosticColumnsRequestBodyTobitFittedType';

/**
 * 推定済みモデルから予測値・残差を抽出してテーブルに列追加するリクエスト
 */
export type AddDiagnosticColumnsRequestBody = {
  /**
   * 追加先テーブル名。ワークスペース内に存在するテーブル名を指定してください。
   * @minLength 1
   */
  tableName: string;
  /** 対象の分析結果 ID（AnalysisResult の UUID） */
  resultId: string;
  /** 追加する値の種類。fitted: 予測値のみ、residual: 残差のみ、both: 両方 */
  target: AddDiagnosticColumnsRequestBodyTarget;
  /** True の場合、標準化残差（studentized internal）を追加する。OLS/Logit/Probit のみ有効。 */
  standardized?: boolean;
  /** True の場合、予測値の 95%信頼区間列を追加する。OLS/FE/RE/IV で有効。 */
  includeInterval?: boolean;
  /** FE/RE モデルの予測値タイプ。total: 固定効果を含む予測（effects=True）、within: 固定効果を除いた変動成分（effects=False）。FE/RE 以外では無視される。 */
  feType?: AddDiagnosticColumnsRequestBodyFeType;
  /** Logit/Probit の残差種別。raw: 生残差 (y - p̂)、deviance: デビアンス残差 sign(y-p̂)√(-2[y·log(p̂)+(1-y)·log(1-p̂)])。OLS などその他のモデルでは無視される。 */
  binaryResidualType?: AddDiagnosticColumnsRequestBodyBinaryResidualType;
  /** Tobit モデルの予測値種別。latent: 潜在変数の予測値 x'β（デフォルト）、observable: 観測値の無条件期待値 E[y|x]（打ち切りを考慮した期待値）。Tobit 以外のモデルでは無視される。 */
  tobitFittedType?: AddDiagnosticColumnsRequestBodyTobitFittedType;
};
