/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * FE/RE モデルの予測値タイプ。total: 固定効果を含む予測（effects=True）、within: 固定効果を除いた変動成分（effects=False）。FE/RE 以外では無視される。
 */
export type AddDiagnosticColumnsRequestBodyFeType = typeof AddDiagnosticColumnsRequestBodyFeType[keyof typeof AddDiagnosticColumnsRequestBodyFeType];


export const AddDiagnosticColumnsRequestBodyFeType = {
  total: 'total',
  within: 'within',
} as const;
