/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import type { DummyMode } from './dummyMode';
import type { NullStrategy } from './nullStrategy';

/**
 * ダミー変数カラム追加リクエスト
 */
export type AddDummyColumnRequestBody = {
  /**
   * 操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。
   * @minLength 1
   */
  tableName: string;
  /**
   * ダミー変数を作成する元となるカラム名。ワークスペースに存在するテーブルの中から指定してください。
   * @minLength 1
   */
  sourceColumnName: string;
  /**
   * 追加位置のカラム名。指定したカラムの右隣に新しいカラムが追加されます。既存のカラム名から指定してください。
   * @minLength 1
   */
  addPositionColumn: string;
  /** ダミー化モード。'single': 特定の1値をダミー化する。'all_except_base': 基準値を除いた全カテゴリを一括ダミー化する。 */
  mode?: DummyMode;
  /** 新しいカラム名。single モード時は必須。all_except_base モードでは無視され、{source}_{value} 形式で自動生成されます。 */
  dummyColumnName?: string | null;
  /** single モード時のみ必須。列に存在する1にする対象の値。 */
  targetValue?: string | null;
  /** all_except_base モード時のみ必須。ダミー化から除外する基準カテゴリ値。'auto_most_frequent' を指定すると最頻値を自動選択します。 */
  dropBaseValue?: string | null;
  /** null値（空文字・空白を含む）の扱い。'exclude': null を無視してダミーを生成しない。'as_category': null を '__null__' カテゴリとして扱う。'error': null が存在する場合エラーを返す。 */
  nullStrategy?: NullStrategy;
};
