/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * ダミー変数カラム追加レスポンス
 */
export interface AddDummyColumnResult {
  /** ダミーカラムを追加したテーブル名 */
  tableName: string;
  /** 追加したダミーカラム名 */
  dummyColumnName: string;
}
