/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

/**
 * 追加する値の種類。fitted: 予測値のみ、residual: 残差のみ、both: 両方
 */
export type AddDiagnosticColumnsRequestBodyTarget = typeof AddDiagnosticColumnsRequestBodyTarget[keyof typeof AddDiagnosticColumnsRequestBodyTarget];


export const AddDiagnosticColumnsRequestBodyTarget = {
  fitted: 'fitted',
  residual: 'residual',
  both: 'both',
} as const;
