/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Tobit モデルの予測値種別。latent: 潜在変数の予測値 x'β（デフォルト）、observable: 観測値の無条件期待値 E[y|x]（打ち切りを考慮した期待値）。Tobit 以外のモデルでは無視される。
 */
export type AddDiagnosticColumnsRequestBodyTobitFittedType = typeof AddDiagnosticColumnsRequestBodyTobitFittedType[keyof typeof AddDiagnosticColumnsRequestBodyTobitFittedType];


export const AddDiagnosticColumnsRequestBodyTobitFittedType = {
  latent: 'latent',
  observable: 'observable',
} as const;
