/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * ラグ・リードカラム追加レスポンス
 */
export type AddLagLeadColumnResult = {
  /** ラグ・リードカラムを追加したテーブル名 */
  tableName: string;
  /** 追加したラグ・リードカラム名 */
  columnName: string;
};
