/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * ラグ・リードカラム追加リクエスト
 */
export interface AddLagLeadColumnRequestBody {
  /**
   * 操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。
   * @minLength 1
   */
  tableName: string;
  /**
   * ラグ・リードの元となるカラム名。ワークスペースに存在するテーブルの中から指定してください。
   * @minLength 1
   */
  sourceColumn: string;
  /**
   * 新しいカラム名。既存のカラム名と重複しない名前を指定してください。
   * @minLength 1
   * @maxLength 128
   * @pattern ^[^\x00-\x1f\x7f]+$
   */
  newColumnName: string;
  /**
   * 追加位置のカラム名。指定したカラムの右隣に新しいカラムが追加されます。既存のカラム名から指定してください。
   * @minLength 1
   */
  addPositionColumn: string;
  /** ラグ・リードの期間。負の値（-1, -2...）はラグ変数、正の値（1, 2...）はリード変数を作成します。例えば、-1を指定すると1行前の値（ラグ1）、1を指定すると1行後の値（リード1）が新しいカラムに入ります。 */
  periods: number;
  /** ラグ・リードのグループ化に使用するカラムのリスト。指定したカラムの組み合わせごとにラグ・リードが計算されます。例えば、都市ごとにラグ・リードを計算したい場合は、['city']や['都市']を指定してください。複数カラムを指定することもできます。既存カラム名から指定してください。 */
  groupColumns?: string[];
}
