/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * パネル時間カラム追加レスポンス
 */
export type AddPanelTimeColumnResult = {
  /** パネル時間カラムを追加したテーブル名 */
  tableName: string;
  /** 追加したパネル時間カラム名 */
  columnName: string;
};
