/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { AddSimulationColumnRequestDistributionParams } from './addSimulationColumnRequestDistributionParams';

/**
 * シミュレーションカラム追加リクエスト
 */
export interface AddSimulationColumnRequest {
  /**
   * テーブル名
   * @minLength 1
   * @maxLength 255
   */
  tableName: string;
  /**
   * 新しいカラム名
   * @minLength 1
   * @maxLength 255
   */
  newColumnName: string;
  /**
   * 分布の種類
   * @minLength 1
   */
  distributionType: string;
  /** 分布のパラメータ */
  distributionParams: AddSimulationColumnRequestDistributionParams;
}
