/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import type { DistributionType } from './distributionType';

/**
 * シミュレーションカラム追加レスポンス
 */
export type AddSimulationColumnResult = {
  /** シミュレーションカラムを追加したテーブル名 */
  tableName: string;
  /** 追加したシミュレーションカラム名 */
  columnName: string;
  /** 使用した分布タイプ */
  distributionType: DistributionType;
};
