/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import type { SimulationColumnConfig } from './simulationColumnConfig';

/**
 * シミュレーションカラム追加リクエスト
 */
export type AddSimulationColumnRequestBody = {
  /**
     * 操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。
     * @minLength 1
     */
  tableName: string;
  /** シミュレーションカラムの設定。 */
  simulationColumn: SimulationColumnConfig;
  /**
     * 追加位置のカラム名。指定したカラムの右隣に新しいカラムが追加されます。既存のカラム名から指定してください。
     * @minLength 1
     */
  addPositionColumn: string;
  /** 乱数シード値（0以上1億以下の整数）。同じシードを指定すると同じ結果が再現されます。None の場合は毎回異なる結果になります。 */
  randomSeed?: number | null;
};
