/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { SimulationColumnConfig } from './simulationColumnConfig';

/**
 * シミュレーションカラム追加リクエスト
 */
export interface AddSimulationColumnRequestBody {
  /**
   * 操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。
   * @minLength 1
   */
  tableName: string;
  /** シミュレーションカラムの設定。 */
  simulationColumn: SimulationColumnConfig;
  /**
   * 追加位置のカラム名。指定したカラムの右隣に新しいカラムが追加されます。既存のカラム名から指定してください。
   * @minLength 1
   */
  addPositionColumn: string;
}
