/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 推定結果の詳細データ。手法（OLS / FE / RE / IV / Logit / Probit / Tobit 等）により含まれるキーが異なる。
 */
export type AnalysisResultDetailRegressionOutput = { [key: string]: unknown };
