/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import type { AnalysisResultDetailRegressionOutput } from './analysisResultDetailRegressionOutput';

/**
 * 分析結果詳細（1件取得用）
 */
export type AnalysisResultDetail = {
  /** 分析結果の一意 ID */
  id: string;
  /** 分析結果名 */
  name: string;
  /** 分析結果の説明メモ */
  description: string;
  /** 分析対象テーブル名 */
  tableName: string;
  /** 推定結果の詳細データ。手法（OLS / FE / RE / IV / Logit / Probit / Tobit 等）により含まれるキーが異なる。 */
  regressionOutput: AnalysisResultDetailRegressionOutput;
  /** 作成日時（ISO 8601 形式） */
  createdAt: string;
  /** 保存済みモデルファイルのパス（None の場合は未保存） */
  modelPath: string | null;
  /** モデルの種別文字列（ols / fe / re / iv 等） */
  modelType: string | null;
  /** パネルデータ分析における個体 ID 列名 */
  entityIdColumn: string | null;
  /** パネルデータ分析における時間列名 */
  timeColumn: string | null;
};
