/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 分析結果サマリー（一覧取得用の各要素）
 */
export type AnalysisResultSummary = {
  /** 分析結果の一意 ID */
  id: string;
  /** 分析結果名 */
  name: string;
  /** 分析結果の説明メモ */
  description: string;
  /** 作成日時（ISO 8601 形式） */
  createdAt: string;
  /** 分析対象テーブル名 */
  tableName: string;
  /** 分析種別文字列（regression / confidence_interval / descriptive_statistics / statistical_test / did / rdd / heckman 等） */
  resultType: string;
  /** 分析種別の表示ラベル（日本語） */
  resultTypeLabel: string;
  /** モデルの種別文字列（ols / fe / re / iv 等） */
  modelType: string | null;
  /** 分析内容の簡潔な説明文（フロントエンド一覧表示用） */
  summaryText: string;
};
