/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.4.0
 */

/**
 * 漸近正規性シミュレーション結果
 */
export type AsymptoticNormalityResult = {
  /** OLS β̂ の標本リスト */
  betaEstimates: number[];
  /** 真の傾きパラメータ */
  trueBeta: number;
  /** 漸近正規性が成立するか否か */
  isAsymptoticallyNormal: boolean;
  /** 漸近分布の平均（コーシー時は None） */
  asymptoticMean: number | null;
  /** 漸近分布の分散（コーシー時は None） */
  asymptoticVariance: number | null;
};
