/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

/**
 * ベルヌーイ分布のパラメータ
 */
export type BernoulliParams = {
  /** 分布の種類 */
  type: 'bernoulli';
  /**
   * 成功確率
   * @maximum 1
   * @exclusiveMinimum 0
   */
  p: number;
};
