/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * ベータ分布のパラメータ
 */
export type BetaParams = {
  /** 分布の種類 */
  type: 'beta';
  /**
     * 形状パラメータa
     * @exclusiveMinimum 0
     */
  a: number;
  /**
     * 形状パラメータb
     * @exclusiveMinimum 0
     */
  b: number;
};
