/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * ベータ分布のパラメータ
 */
export interface BetaParams {
  /** 分布の種類 */
  type: 'beta';
  /**
   * 形状パラメータa
   * @exclusiveMinimum 0
   */
  a: number;
  /**
   * 形状パラメータb
   * @exclusiveMinimum 0
   */
  b: number;
}
