/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 分布の種類
 */
export type BetaParamsType = typeof BetaParamsType[keyof typeof BetaParamsType];


export const BetaParamsType = {
  beta: 'beta',
} as const;
