/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { BinaryChoiceRegressionParamsMethod } from './binaryChoiceRegressionParamsMethod';
import type { BinaryChoiceRegularization } from './binaryChoiceRegularization';

export interface BinaryChoiceRegressionParams {
  method: BinaryChoiceRegressionParamsMethod;
  regularization?: BinaryChoiceRegularization | null;
  /** 平均限界効果(AME)を計算するかどうか */
  calculateMarginalEffects?: boolean;
}
