/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

export type BinaryChoiceRegularizationType = typeof BinaryChoiceRegularizationType[keyof typeof BinaryChoiceRegularizationType];


export const BinaryChoiceRegularizationType = {
  l1: 'l1',
  l2: 'l2',
} as const;
