/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { BinaryChoiceRegressionParamsBinaryResidualType } from './binaryChoiceRegressionParamsBinaryResidualType';
import type { BinaryChoiceRegressionParamsMethod } from './binaryChoiceRegressionParamsMethod';
import type { BinaryChoiceRegularization } from './binaryChoiceRegularization';

export type BinaryChoiceRegressionParams = {
  method: BinaryChoiceRegressionParamsMethod;
  regularization?: BinaryChoiceRegularization | null;
  /** 平均限界効果(AME)を計算するかどうか */
  calculateMarginalEffects?: boolean;
  /** 残差種別。raw: 生残差 (y - p̂)、deviance: デビアンス残差。Logit/Probit のみ有効。 */
  binaryResidualType?: BinaryChoiceRegressionParamsBinaryResidualType;
};
