/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import type { BinaryChoiceRegularizationType } from './binaryChoiceRegularizationType';

export type BinaryChoiceRegularization = {
  type?: BinaryChoiceRegularizationType;
  /** @minimum 0 */
  alpha?: number;
};
