/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 二項分布のパラメータ
 */
export type BinomialParams = {
  /** 分布の種類 */
  type: 'binomial';
  /**
     * 試行回数
     * @exclusiveMinimum 0
     */
  n: number;
  /**
     * 成功確率
     * @maximum 1
     * @exclusiveMinimum 0
     */
  p: number;
};
