/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import { BinomialParamsType } from './binomialParamsType';

/**
 * 二項分布のパラメータ
 */
export type BinomialParams = {
  /** 分布の種類 */
  type: BinomialParamsType;
  /**
     * 試行回数
     * @exclusiveMinimum 0
     */
  trialCount: number;
  /**
     * 成功確率
     * @maximum 1
     * @exclusiveMinimum 0
     */
  successProbability: number;
};
