/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 分布の種類
 */
export type BinomialParamsType = typeof BinomialParamsType[keyof typeof BinomialParamsType];


export const BinomialParamsType = {
  binomial: 'binomial',
} as const;
