/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * カラム計算レスポンス
 */
export type CalculateColumnResult = {
  /** 計算カラムを追加したテーブル名 */
  tableName: string;
  /** 追加した計算カラム名 */
  columnName: string;
};
