/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

/**
 * カラム計算リクエスト
 */
export type CalculateColumnRequestBody = {
  /**
   * 操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。
   * @minLength 1
   */
  tableName: string;
  /**
   * 新しいカラム名。既存のカラム名と重複しない名前を指定してください。
   * @minLength 1
   * @maxLength 128
   * @pattern ^[^\x00-\x1f\x7f]+$
   */
  newColumnName: string;
  /**
   * 追加位置のカラム名。指定したカラムの右隣に新しいカラムが追加されます。既存のカラム名から指定してください。
   * @minLength 1
   */
  addPositionColumn: string;
  /**
   * 計算式。数値カラム名をpl.col('price')の形式で指定し、四則演算や関数を組み合わせて計算式を定義してください。例: ({population} / {area}) * 1000')
   * @minLength 1
   */
  calculationExpression: string;
};
