/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 変換先のデータ型。float / int / str / bool / date / datetime から選択。
 */
export type CastColumnRequestBodyTargetType = typeof CastColumnRequestBodyTargetType[keyof typeof CastColumnRequestBodyTargetType];


export const CastColumnRequestBodyTargetType = {
  float: 'float',
  int: 'int',
  str: 'str',
  bool: 'bool',
  date: 'date',
  datetime: 'datetime',
} as const;
