/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

/**
 * 列型変換レスポンス
 */
export type CastColumnResult = {
  /** 型変換カラムを追加したテーブル名 */
  tableName: string;
  /** 追加した型変換カラム名 */
  columnName: string;
};
