/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { CastColumnRequestBodyTargetType } from './castColumnRequestBodyTargetType';

/**
 * 列型変換リクエスト
 */
export interface CastColumnRequestBody {
  /**
   * 操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。
   * @minLength 1
   */
  tableName: string;
  /**
   * 変換元となるカラム名。ワークスペースに存在するテーブルの中から指定してください。
   * @minLength 1
   */
  sourceColumnName: string;
  /** 変換先のデータ型。float / int / str / bool / date / datetime から選択。 */
  targetType: CastColumnRequestBodyTargetType;
  /**
   * 新しいカラム名。既存のカラム名と重複しない名前を指定してください。
   * @minLength 1
   * @maxLength 128
   * @pattern ^[^\x00-\x1f\x7f]+$
   */
  newColumnName: string;
  /**
   * 追加位置のカラム名。指定したカラムの右隣に新しいカラムが追加されます。既存のカラム名から指定してください。
   * @minLength 1
   */
  addPositionColumn: string;
  /** 前後の空白を削除するか。変換元が文字列型の場合のみ有効。 */
  cleanupWhitespace?: boolean;
  /** カンマ(,)を削除するか。数値型変換時に '1,234' → '1234' のような前処理に使用。変換元が文字列型の場合のみ有効。 */
  removeCommas?: boolean;
  /** date / datetime 変換時のパース書式。例: '%Y-%m-%d', '%Y/%m/%d'。None の場合は Polars が自動推定します。 */
  datetimeFormat?: string | null;
  /** True なら変換失敗時に 400 エラーを返す。False なら変換失敗した値を null にして処理を続行する。 */
  strict?: boolean;
}
