/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.4.0
 */
import { ChiSquareParamsType } from './chiSquareParamsType';

/**
 * カイ二乗分布のパラメータ
 */
export type ChiSquareParams = {
  /** 分布の種類 */
  type: ChiSquareParamsType;
  /**
     * 自由度
     * @maximum 1000
     * @exclusiveMinimum 0
     */
  degreesOfFreedom: number;
};
