/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.4.0
 */

/**
 * 分布の種類
 */
export type ChiSquareParamsType = typeof ChiSquareParamsType[keyof typeof ChiSquareParamsType];


export const ChiSquareParamsType = {
  chi_square: 'chi_square',
} as const;
