/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.4.0
 */

/**
 * 信頼区間の境界値と包含フラグ
 */
export type CIBound = {
  /** 信頼区間下限 */
  lower: number;
  /** 信頼区間上限 */
  upper: number;
  /** 真の値を含むか否か */
  containsTrue: boolean;
};
