/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 全分析結果クリアレスポンス
 */
export type ClearAllAnalysisResultsResult = {
  /** 処理結果メッセージ */
  message: string;
};
