/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 全テーブルクリアレスポンス（データなし）
 */
export type ClearTablesResult = { [key: string]: unknown };
