/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

export type ClusteredStandardErrorMethod = typeof ClusteredStandardErrorMethod[keyof typeof ClusteredStandardErrorMethod];


export const ClusteredStandardErrorMethod = {
  cluster: 'cluster',
} as const;
