/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

export type ClusteredStandardErrorMethod = typeof ClusteredStandardErrorMethod[keyof typeof ClusteredStandardErrorMethod];


export const ClusteredStandardErrorMethod = {
  cluster: 'cluster',
} as const;
