/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import { ClusteredStandardErrorMethod } from './clusteredStandardErrorMethod';

export type ClusteredStandardError = {
  method: ClusteredStandardErrorMethod;
  /** クラスターを構成する列名 */
  groups: string[];
  /** 小標本補正を行うか */
  useCorrection?: boolean;
};
