/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * カラム情報
 */
export type ColumnInfo = {
  /** カラム名 */
  name: string;
  /** Polarsデータ型（例: Int64, Float64, String） */
  type: string;
};
