/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 信頼区間の下限・上限
 */
export interface ConfidenceIntervalBounds {
  /** 信頼区間の下限値 */
  lower: number;
  /** 信頼区間の上限値 */
  upper: number;
}
