/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import type { ConfidenceIntervalOutputOptions } from './confidenceIntervalOutputOptions';
import type { OutputResultFormat } from './outputResultFormat';

/**
 * 信頼区間結果のフォーマット出力リクエスト
 */
export type ConfidenceIntervalOutputRequest = {
  /** 出力対象の分析結果種別。 */
  resultType?: 'confidence_interval';
  /**
     * 出力する分析結果 ID のリスト（1件以上）
     * @minItems 1
     */
  resultIds: string[];
  /** 出力フォーマット。 */
  format: OutputResultFormat;
  /** 信頼区間出力用オプション。 */
  options?: ConfidenceIntervalOutputOptions;
};
