/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 信頼区間計算リクエスト
 */
export interface ConfidenceIntervalRequest {
  /**
   * テーブル名
   * @minLength 1
   * @maxLength 255
   */
  tableName: string;
  /**
   * 対象カラム名
   * @minLength 1
   * @maxLength 255
   */
  columnName: string;
  /**
   * 信頼水準 (例: 0.95)
   * @exclusiveMinimum 0
   * @exclusiveMaximum 1
   */
  confidenceLevel: number;
  /**
   * 統計量のタイプ (mean, median, etc.)
   * @minLength 1
   * @maxLength 50
   */
  statisticType: string;
}
