/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.4.0
 */
import type { CIBound } from './cIBound';

/**
 * 信頼区間シミュレーション結果
 */
export type ConfidenceIntervalSimResult = {
  /** 真の値 */
  trueValue: number;
  /** 信頼水準 */
  confidenceLevel: number;
  /** 各試行の信頼区間リスト */
  intervals: CIBound[];
};
