/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { ConfidenceIntervalStatisticsType } from './confidenceIntervalStatisticsType';

/**
 * 信頼区間計算リクエスト
 */
export interface ConfidenceIntervalRequestBody {
  /**
   * 信頼区間を計算する対象テーブル名。ワークスペース内に存在するテーブル名を指定してください。
   * @minLength 1
   */
  tableName: string;
  /**
   * 信頼区間を計算する対象カラム名。テーブル内に存在するカラム名を指定してください。
   * @minLength 1
   */
  columnName: string;
  /**
   * 信頼水準（例: 0.95 = 95%信頼区間）
   * @exclusiveMinimum 0
   * @exclusiveMaximum 1
   */
  confidenceLevel: number;
  /** 信頼区間を計算する統計量のタイプ。（mean: 平均、median: 中央値、proportion: 割合、variance: 分散、standard_deviation: 標準偏差） */
  statisticType: ConfidenceIntervalStatisticsType;
}
