/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.4.0
 */
import type { ConfidenceIntervalSimRequestBodyCiType } from './confidenceIntervalSimRequestBodyCiType';

/**
 * 信頼区間シミュレーションリクエスト
 */
export type ConfidenceIntervalSimRequestBody = {
  ciType?: ConfidenceIntervalSimRequestBodyCiType;
  /**
     * シミュレーション試行回数
     * @minimum 10
     * @maximum 2000
     */
  trials?: number;
  /**
     * 各試行のサンプルサイズ
     * @minimum 5
     * @maximum 500
     */
  sampleSize?: number;
  /** 信頼水準（0.90 / 0.95 / 0.99） */
  confidenceLevel?: number;
  /**
     * 母平均の真の値
     * @minimum -100
     * @maximum 100
     */
  trueMean?: number;
  /**
     * 母分散の真の値
     * @minimum 0.01
     * @maximum 100
     */
  trueVariance?: number;
};
