/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.4.0
 */

export type ConfidenceIntervalSimRequestBodyCiType = typeof ConfidenceIntervalSimRequestBodyCiType[keyof typeof ConfidenceIntervalSimRequestBodyCiType];


export const ConfidenceIntervalSimRequestBodyCiType = {
  mean: 'mean',
  variance: 'variance',
} as const;
