/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import type { ConfidenceIntervalBounds } from './confidenceIntervalBounds';
import type { StatisticValue } from './statisticValue';

/**
 * 信頼区間計算レスポンス
 */
export type ConfidenceIntervalResult = {
  /** 計算対象のテーブル名 */
  tableName: string;
  /** 計算対象のカラム名 */
  columnName: string;
  /** 計算した統計量のタイプと値 */
  statistic: StatisticValue;
  /** 信頼区間の下限値と上限値 */
  confidenceInterval: ConfidenceIntervalBounds;
  /** 計算に使用した信頼水準 */
  confidenceLevel: number;
};
