/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.4.0
 */
import type { XDistributionParams } from './xDistributionParams';

/**
 * 一致性シミュレーションリクエスト
 */
export type ConsistencyRequestBody = {
  /**
     * サンプルサイズの上限
     * @minimum 50
     * @maximum 5000
     */
  nMax?: number;
  /**
     * 真の傾きパラメータ
     * @minimum -3
     * @maximum 3
     */
  trueBeta?: number;
  /**
     * 誤差の分散
     * @minimum 0.1
     * @maximum 10
     */
  errorVariance?: number;
  /** 内生性あり (True) / 外生性成立 (False) */
  endogenous?: boolean;
  /**
     * 内生性の強さ（γ）: endogenous=True 時のみ有効
     * @minimum 0.1
     * @maximum 3
     */
  endogeneityStrength?: number;
  xDistribution?: XDistributionParams;
};
