/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

export type CorrelationMethod = typeof CorrelationMethod[keyof typeof CorrelationMethod];


export const CorrelationMethod = {
  pearson: 'pearson',
  spearman: 'spearman',
  kendall: 'kendall',
} as const;
