/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.4.0
 */

/**
 * GroupBy 統計テーブル作成レスポンス
 */
export type CreateGroupStatisticsTableResult = {
  /** 新規作成された GroupBy 統計テーブルの名前。 */
  tableName: string;
};
