/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

/**
 * ユニオンテーブル作成リクエスト
 */
export interface CreateUnionTableRequest {
  /**
   * ユニオン後のテーブル名
   * @minLength 1
   * @maxLength 255
   */
  unionTableName: string;
  /**
   * 結合するテーブル名のリスト
   * @minItems 1
   */
  tableNames: string[];
  /** 対象カラム名のリスト */
  columnNames?: string[];
}
