/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 結合テーブル作成リクエスト
 */
export interface CreateJoinTableRequest {
  /**
   * 結合後のテーブル名
   * @minLength 1
   * @maxLength 255
   */
  joinTableName: string;
  /**
   * 左側のテーブル名
   * @minLength 1
   * @maxLength 255
   */
  leftTableName: string;
  /**
   * 右側のテーブル名
   * @minLength 1
   * @maxLength 255
   */
  rightTableName: string;
  /**
   * 左側の結合キーカラム名のリスト
   * @minItems 1
   */
  leftKeyColumnNames: string[];
  /**
   * 右側の結合キーカラム名のリスト
   * @minItems 1
   */
  rightKeyColumnNames: string[];
  /**
   * 結合タイプ (inner, left, right, outer)
   * @minLength 1
   * @maxLength 50
   */
  joinType: string;
}
