/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 相関係数テーブル作成レスポンス
 */
export type CreateCorrelationTableResult = {
  /** 新規作成された相関係数テーブルの名前。 */
  tableName: string;
};
