/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */
import type { CorrelationMethod } from './correlationMethod';
import type { MissingHandlingMethod } from './missingHandlingMethod';

/**
 * 相関係数テーブル作成リクエスト
 */
export type CreateCorrelationTableRequestBody = {
  /**
     * 相関係数を計算する元テーブル名。
     * @minLength 1
     */
  tableName: string;
  /**
     * 相関係数を計算する対象カラム名のリスト。2列以上を指定してください。
     * @minItems 2
     */
  columnNames: string[];
  /**
     * 結果を格納する新規テーブル名。
     * @minLength 1
     */
  newTableName: string;
  /** 相関係数の計算手法。pearson: ピアソン積率相関係数（デフォルト）、spearman: スピアマン順位相関係数、kendall: ケンドールの順位相関係数 */
  method?: CorrelationMethod;
  /**
     * 丸め桁数（1～15、デフォルト: 3）
     * @minimum 1
     * @maximum 15
     */
  decimalPlaces?: number;
  /** True の場合、上三角部分の値を null に置き換えて返す。デフォルト: False。 */
  lowerTriangleOnly?: boolean;
  /** 欠損値の処理方法。pairwise: ペア単位で欠損を除外して計算（デフォルト）、listwise: 欠損を含む行をすべての列で一括削除してから計算 */
  missingHandling?: MissingHandlingMethod;
};
