/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { CreateTableRequestBodyCsvEncoding } from './createTableRequestBodyCsvEncoding';

/**
 * テーブル作成リクエスト
 */
export interface CreateTableRequestBody {
  /**
   * 作成するテーブルの名前。ワークスペース内に存在しない名前を指定してください。
   * @minLength 1
   * @maxLength 128
   * @pattern ^[^\x00-\x1f\x7f]+$
   */
  tableName: string;
  /** テーブルの行数。file_path が指定されている場合は省略可能（None の場合はファイルの行数を使用）。file_path が省略されている場合は必須（1以上の整数）。 */
  rowCount?: number | null;
  /**
   * テーブルに作成するカラム名のリスト
   * @minItems 1
   */
  columnNames: string[];
  /** 読み込むファイルのパス（CSV / Excel / Parquet）。省略時はすべての値が None の空テーブルを作成します。 */
  filePath?: string | null;
  /** CSV ファイルにヘッダ行があるか。True: 1 行目をヘッダとして読み飛ばし、2 行目からをデータとする。False: 1 行目からデータとして読み込む。file_path が CSV の場合のみ有効。 */
  csvHasHeader?: boolean;
  /**
   * CSV の区切り文字。file_path が CSV の場合のみ有効。
   * @minLength 1
   * @maxLength 10
   */
  csvSeparator?: string;
  /** CSV のエンコーディング。file_path が CSV の場合のみ有効。 */
  csvEncoding?: CreateTableRequestBodyCsvEncoding;
  /** 読み込むシート名。file_path が Excel の場合のみ有効。省略時は先頭シートを読み込みます。 */
  excelSheetName?: string | null;
}
