/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

/**
 * シミュレーションデータテーブル作成レスポンス
 */
export type CreateSimulationDataTableResult = {
  /** 操作対象または生成されたテーブル名 */
  tableName: string;
};
