/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 結合テーブル作成レスポンス
 */
export type CreateJoinTableResult = {
  /** 操作対象または生成されたテーブル名 */
  tableName: string;
};
