/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import type { JoinType } from './joinType';

/**
 * 結合テーブル作成リクエスト
 */
export type CreateJoinTableRequestBody = {
  /**
     * 結合後に作成される新しいテーブル名。ワークスペース内に存在しない名前を指定してください。
     * @minLength 1
     * @maxLength 128
     * @pattern ^[^\x00-\x1f\x7f]+$
     */
  joinTableName: string;
  /**
     * 結合の左側テーブル名。ワークスペース内に存在するテーブル名を指定してください。
     * @minLength 1
     */
  leftTableName: string;
  /**
     * 結合の右側テーブル名。ワークスペース内に存在するテーブル名を指定してください。
     * @minLength 1
     */
  rightTableName: string;
  /**
     * 左側テーブルの結合キーカラム名のリスト
     * @minItems 1
     */
  leftKeyColumnNames: string[];
  /**
     * 右側テーブルの結合キーカラム名のリスト
     * @minItems 1
     */
  rightKeyColumnNames: string[];
  /** 結合タイプ（inner: 内部結合、left: 左外部結合、right: 右外部結合、full: 完全外部結合） */
  joinType?: JoinType;
};
