/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 相関係数テーブル作成レスポンス
 */
export type CreateCorrelationTableResult = {
  /** 新規作成された相関係数テーブルの名前。 */
  tableName: string;
};
