/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

/**
 * ユニオンテーブル作成リクエスト
 */
export type CreateUnionTableRequestBody = {
  /**
   * ユニオン後に作成される新しいテーブル名
   * @minLength 1
   * @maxLength 128
   * @pattern ^[^\x00-\x1f\x7f]+$
   */
  unionTableName: string;
  /**
   * ユニオンするテーブル名のリスト（2テーブル以上）。ワークスペース内に存在するテーブル名を指定してください。
   * @minItems 2
   */
  tableNames: string[];
  /**
   * ユニオンの対象とするカラム名のリスト。指定されたテーブルすべてに存在するカラム名を指定してください。
   * @minItems 1
   */
  columnNames: string[];
};
