/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

/**
 * テーブル作成リクエスト
 */
export interface CreateTableRequest {
  /**
   * テーブル名
   * @minLength 1
   * @maxLength 255
   */
  tableName: string;
  /**
   * テーブルの行数
   * @minimum 1
   */
  tableNumberOfRows: number;
  /**
   * カラム名のリスト
   * @minItems 1
   */
  columnNames: string[];
}
