/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { SimulationColumnConfig } from './simulationColumnConfig';

/**
 * シミュレーションデータテーブル作成リクエスト
 */
export interface CreateSimulationDataTableRequestBody {
  /**
   * 作成するシミュレーションデータテーブルの名前。ワークスペース内に存在しない名前を指定してください。
   * @minLength 1
   * @maxLength 128
   * @pattern ^[^\x00-\x1f\x7f]+$
   */
  tableName: string;
  /**
   * 生成するテーブルの行数
   * @minimum 1
   */
  rowCount: number;
  /**
   * シミュレーションカラムの設定リスト
   * @minItems 1
   */
  simulationColumns: SimulationColumnConfig[];
}
