/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSimulationDataTableRequestColumnSettingsItem } from './createSimulationDataTableRequestColumnSettingsItem';

/**
 * シミュレーションデータテーブル作成リクエスト
 */
export interface CreateSimulationDataTableRequest {
  /**
   * テーブル名
   * @minLength 1
   * @maxLength 255
   */
  tableName: string;
  /**
   * テーブルの行数
   * @minimum 1
   */
  tableNumberOfRows: number;
  /**
   * カラム設定のリスト
   * @minItems 1
   */
  columnSettings: CreateSimulationDataTableRequestColumnSettingsItem[];
}
