/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * カラム削除レスポンス
 */
export interface DeleteColumnResult {
  /** カラムを削除したテーブル名 */
  tableName: string;
}
