/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 分析結果削除レスポンス
 */
export interface DeleteAnalysisResultResult {
  /** 削除した分析結果の ID */
  deletedResultId: string;
}
