/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

/**
 * 分析結果削除レスポンス
 */
export type DeleteAnalysisResultResult = {
  /** 削除した分析結果の ID */
  deletedResultId: string;
};
