/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * カラム削除レスポンス
 */
export type DeleteColumnResult = {
  /** カラムを削除したテーブル名 */
  tableName: string;
};
