/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * テーブル削除リクエスト
 */
export interface DeleteTableRequestBody {
  /**
   * 削除するテーブル名。ワークスペースに存在するテーブルの中から指定してください。
   * @minLength 1
   */
  tableName: string;
}
