/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

/**
 * カラム削除リクエスト
 */
export interface DeleteColumnRequest {
  /**
   * テーブル名
   * @minLength 1
   * @maxLength 255
   */
  tableName: string;
  /**
   * カラム名
   * @minLength 1
   * @maxLength 255
   */
  columnName: string;
}
