/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

/**
 * 記述統計の計算結果。カラム名をキー、{統計量名: 値} を値とする辞書型データ。
 */
export type DescriptiveStatisticsResultStatistics = {[key: string]: {[key: string]: number | null}};
