/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

export type DescriptiveStatisticType = typeof DescriptiveStatisticType[keyof typeof DescriptiveStatisticType];


export const DescriptiveStatisticType = {
  mean: 'mean',
  median: 'median',
  mode: 'mode',
  variance: 'variance',
  std_dev: 'std_dev',
  range: 'range',
  iqr: 'iqr',
} as const;
