/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

export type DescriptiveStatisticType = typeof DescriptiveStatisticType[keyof typeof DescriptiveStatisticType];


export const DescriptiveStatisticType = {
  mean: 'mean',
  median: 'median',
  mode: 'mode',
  variance: 'variance',
  std_dev: 'std_dev',
  range: 'range',
  iqr: 'iqr',
  count: 'count',
  null_count: 'null_count',
  null_ratio: 'null_ratio',
  population_variance: 'population_variance',
} as const;
