/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import type { DescriptiveStatisticsOutputOptions } from './descriptiveStatisticsOutputOptions';
import type { OutputResultFormat } from './outputResultFormat';

/**
 * 記述統計結果のフォーマット出力リクエスト
 */
export type DescriptiveStatisticsOutputRequest = {
  /** 出力対象の分析結果種別。 */
  resultType?: 'descriptive_statistics';
  /**
     * 出力する分析結果 ID のリスト（1件以上）
     * @minItems 1
     */
  resultIds: string[];
  /** 出力フォーマット。 */
  format: OutputResultFormat;
  /** 記述統計出力用オプション。 */
  options?: DescriptiveStatisticsOutputOptions;
};
