/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 変数名から表示ラベルへのマッピング辞書。
 */
export type DescriptiveStatisticsOutputOptionsVariableLabels = {[key: string]: string} | null;
