/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 記述統計レスポンス
 */
export type DescriptiveStatisticsResult = {
  /** 計算対象のテーブル名 */
  tableName: string;
  /** 記述統計の計算結果。カラム名と統計量名をキーに持つ辞書型データ。 */
  statistics: unknown;
};
