/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */
import type { DescriptiveStatisticsResultStatistics } from './descriptiveStatisticsResultStatistics';

/**
 * 記述統計レスポンス
 */
export type DescriptiveStatisticsResult = {
  /** 計算対象のテーブル名 */
  tableName: string;
  /** 記述統計の計算結果。カラム名をキー、{統計量名: 値} を値とする辞書型データ。 */
  statistics: DescriptiveStatisticsResultStatistics;
};
