/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */
import type { DescriptiveStatisticType } from './descriptiveStatisticType';

/**
 * 記述統計リクエスト
 */
export type DescriptiveStatisticsRequestBody = {
  /**
     * 記述統計を計算する対象テーブル名。ワークスペース内に存在するテーブル名を指定してください。
     * @minLength 1
     */
  tableName: string;
  /**
     * 記述統計を計算する対象カラム名のリスト。テーブル内に存在するカラム名を指定してください。複数カラムを指定することもできます。
     * @minItems 1
     */
  columnNameList: string[];
  /**
     * 計算する統計量のリスト（mean: 平均、median: 中央値、mode: 最頻値、variance: 不偏分散、std_dev: 標準偏差、range: 範囲、iqr: 四分位数範囲、count: 有効サンプル数、null_count: null数、null_ratio: null割合、population_variance: 母分散）
     * @minItems 1
     */
  statistics: DescriptiveStatisticType[];
};
