/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { BernoulliParams } from './bernoulliParams';
import type { BetaParams } from './betaParams';
import type { BinomialParams } from './binomialParams';
import type { ExponentialParams } from './exponentialParams';
import type { FixedParams } from './fixedParams';
import type { GammaParams } from './gammaParams';
import type { GeometricParams } from './geometricParams';
import type { HypergeometricParams } from './hypergeometricParams';
import type { LognormalParams } from './lognormalParams';
import type { NormalParams } from './normalParams';
import type { PoissonParams } from './poissonParams';
import type { UniformParams } from './uniformParams';
import type { WeibullParams } from './weibullParams';

export type DistributionParams = UniformParams | ExponentialParams | NormalParams | GammaParams | BetaParams | WeibullParams | LognormalParams | BinomialParams | BernoulliParams | PoissonParams | GeometricParams | HypergeometricParams | FixedParams;
