/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.4.0
 */

/**
 * 分布プレビューレスポンス
 */
export type DistributionPreviewResult = {
  /** 離散分布のとき True */
  isDiscrete: boolean;
  /** X 軸の値のリスト */
  x: number[];
  /** PDF（連続）または PMF（離散）の値 */
  yDensity: number[];
  /** CDF（連続）または CMF（離散）の値 */
  yCumulative: number[];
};
