/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

export type DistributionType = typeof DistributionType[keyof typeof DistributionType];


export const DistributionType = {
  uniform: 'uniform',
  exponential: 'exponential',
  normal: 'normal',
  gamma: 'gamma',
  beta: 'beta',
  weibull: 'weibull',
  lognormal: 'lognormal',
  binomial: 'binomial',
  bernoulli: 'bernoulli',
  poisson: 'poisson',
  geometric: 'geometric',
  hypergeometric: 'hypergeometric',
  negative_binomial: 'negative_binomial',
  fixed: 'fixed',
  sequence: 'sequence',
} as const;
