/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import type { BernoulliParams } from './bernoulliParams';
import type { BetaParams } from './betaParams';
import type { BinomialParams } from './binomialParams';
import type { DistributionParamsType } from './distributionParamsType';
import type { ExponentialParams } from './exponentialParams';
import type { FixedParams } from './fixedParams';
import type { GammaParams } from './gammaParams';
import type { GeometricParams } from './geometricParams';
import type { HypergeometricParams } from './hypergeometricParams';
import type { LognormalParams } from './lognormalParams';
import type { NegativeBinomialParams } from './negativeBinomialParams';
import type { NormalParams } from './normalParams';
import type { PoissonParams } from './poissonParams';
import type { UniformParams } from './uniformParams';
import type { WeibullParams } from './weibullParams';

export type DistributionParams = (UniformParams & {
  type: DistributionParamsType;
}) | (ExponentialParams & {
  type: DistributionParamsType;
}) | (NormalParams & {
  type: DistributionParamsType;
}) | (GammaParams & {
  type: DistributionParamsType;
}) | (BetaParams & {
  type: DistributionParamsType;
}) | (WeibullParams & {
  type: DistributionParamsType;
}) | (LognormalParams & {
  type: DistributionParamsType;
}) | (BinomialParams & {
  type: DistributionParamsType;
}) | (BernoulliParams & {
  type: DistributionParamsType;
}) | (PoissonParams & {
  type: DistributionParamsType;
}) | (GeometricParams & {
  type: DistributionParamsType;
}) | (HypergeometricParams & {
  type: DistributionParamsType;
}) | (NegativeBinomialParams & {
  type: DistributionParamsType;
}) | (FixedParams & {
  type: DistributionParamsType;
});
