/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

export type DummyMode = typeof DummyMode[keyof typeof DummyMode];


export const DummyMode = {
  single: 'single',
  all_except_base: 'all_except_base',
} as const;
