/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

/**
 * テーブル複製リクエスト
 */
export interface DuplicateTableRequest {
  /**
   * 元のテーブル名
   * @minLength 1
   * @maxLength 255
   */
  tableName: string;
  /**
   * 新しいテーブル名
   * @minLength 1
   * @maxLength 255
   */
  newTableName: string;
}
