/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * テーブル複製レスポンス
 */
export interface DuplicateTableResult {
  /** 操作対象または生成されたテーブル名 */
  tableName: string;
}
