/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

/**
 * カラム複製リクエスト
 */
export type DuplicateColumnRequestBody = {
  /**
     * 操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。
     * @minLength 1
     */
  tableName: string;
  /**
     * 元となるカラム名。ワークスペースに存在するテーブルの中から指定してください。
     * @minLength 1
     */
  sourceColumnName: string;
  /**
     * 新しいカラム名。既存のカラム名と重複しない名前を指定してください。
     * @minLength 1
     * @maxLength 128
     * @pattern ^[^\x00-\x1f\x7f]+$
     */
  newColumnName: string;
  /**
     * 追加位置のカラム名。指定したカラムの右隣に新しいカラムが追加されます。既存のカラム名から指定してください。
     * @minLength 1
     */
  addPositionColumn: string;
};
