/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * テーブル複製リクエスト
 */
export interface DuplicateTableRequestBody {
  /**
   * 複製元のテーブル名。ワークスペースに存在するテーブルの中から指定してください。
   * @minLength 1
   */
  tableName: string;
  /**
   * 複製後の新しいテーブル名。ワークスペースに存在しない名前を指定してください。
   * @minLength 1
   * @maxLength 128
   * @pattern ^[^\x00-\x1f\x7f]+$
   */
  newTableName: string;
}
