/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Excelファイルパス指定エクスポートリクエスト
 */
export interface ExportExcelByPathRequest {
  /**
   * テーブル名
   * @minLength 1
   * @maxLength 255
   */
  tableName: string;
  /**
   * 出力するディレクトリパス
   * @minLength 1
   * @maxLength 1024
   */
  directoryPath: string;
  /**
   * 出力するExcelファイル名
   * @minLength 1
   * @maxLength 255
   */
  fileName: string;
}
