/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import { ExponentialParamsType } from './exponentialParamsType';

/**
 * 指数分布のパラメータ
 */
export type ExponentialParams = {
  /** 分布の種類 */
  type: ExponentialParamsType;
  /**
     * 尺度パラメータ
     * @exclusiveMinimum 0
     */
  scale: number;
};
