/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 指数分布のパラメータ
 */
export type ExponentialParams = {
  /** 分布の種類 */
  type: 'exponential';
  /**
   * 尺度パラメータ
   * @exclusiveMinimum 0
   */
  scale: number;
};
