/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

/**
 * CSV ファイルの出力エンコーディング（CSV のみ有効）。utf8 / latin1 / ascii / gbk / windows-1252 / shift_jis から選択してください。
 */
export type ExportFileRequestBodyEncoding = typeof ExportFileRequestBodyEncoding[keyof typeof ExportFileRequestBodyEncoding];


export const ExportFileRequestBodyEncoding = {
  utf8: 'utf8',
  latin1: 'latin1',
  ascii: 'ascii',
  gbk: 'gbk',
  'windows-1252': 'windows-1252',
  shift_jis: 'shift_jis',
} as const;
