/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * エクスポート共通レスポンス
 */
export type ExportFileResult = {
  /** 出力したファイルのフルパス（拡張子付き） */
  filePath: string;
};
