/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 指数分布のパラメータ
 */
export interface ExponentialParams {
  /** 分布の種類 */
  type: 'exponential';
  /**
   * 尺度パラメータ
   * @exclusiveMinimum 0
   */
  scale: number;
}
