/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.4.0
 */

/**
 * 分布の種類
 */
export type FDistributionParamsType = typeof FDistributionParamsType[keyof typeof FDistributionParamsType];


export const FDistributionParamsType = {
  f_distribution: 'f_distribution',
} as const;
