/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.4.0
 */
import { FDistributionParamsType } from './fDistributionParamsType';

/**
 * F分布のパラメータ
 */
export type FDistributionParams = {
  /** 分布の種類 */
  type: FDistributionParamsType;
  /**
     * 分子自由度
     * @maximum 1000
     * @exclusiveMinimum 0
     */
  numeratorDf: number;
  /**
     * 分母自由度
     * @maximum 1000
     * @exclusiveMinimum 0
     */
  denominatorDf: number;
};
