/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

export type FEParamsMethod = typeof FEParamsMethod[keyof typeof FEParamsMethod];


export const FEParamsMethod = {
  fe: 'fe',
} as const;
