/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

/**
 * データArrow取得リクエスト
 */
export interface FetchDataToArrowRequest {
  /**
   * 対象テーブル名
   * @minLength 1
   * @maxLength 255
   */
  tableName: string;
  /**
   * 開始行番号
   * @minimum 0
   */
  startRow: number;
  /**
   * チャンクサイズ（デフォルト500行）
   * @minimum 1
   * @maximum 10000
   */
  chunkSize?: number;
}
