/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

/**
 * データArrow取得リクエスト
 */
export type FetchDataToArrowRequestBody = {
  /**
     * データを取得するテーブル名。ワークスペースに存在するテーブルの中から指定してください。
     * @minLength 1
     */
  tableName: string;
  /**
     * 取得を開始する行番号（0始まり）
     * @minimum 0
     */
  startRow: number;
  /**
     * 1リクエストで取得する行数（1〜10000、デフォルト500）
     * @minimum 1
     * @maximum 10000
     */
  chunkSize?: number;
};
