/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * テーブルデータ Arrow IPC 形式取得レスポンス
 */
export interface FetchDataToArrowResult {
  /** データを取得したテーブル名 */
  tableName: string;
  /** Apache Arrow IPC 形式のバイナリデータ（Base64エンコード） */
  arrowData: Blob;
  /** テーブル全体の行数 */
  totalRows: number;
  /** 取得開始行番号 */
  startRow: number;
  /** 取得終了行番号 */
  endRow: number;
}
