/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * テーブルデータ JSON 形式取得レスポンス
 */
export interface FetchDataToJsonResult {
  /** データを取得したテーブル名 */
  tableName: string;
  /** JSON 文字列形式のテーブルデータ */
  data: string;
  /** テーブル全体の行数 */
  totalRows: number;
  /** 取得開始行番号 */
  startRow: number;
  /** 取得終了行番号 */
  endRow: number;
}
