/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * データJSON取得リクエスト
 */
export interface FetchDataToJsonRequestBody {
  /**
   * データを取得するテーブル名。ワークスペースに存在するテーブルの中から指定してください。
   * @minLength 1
   */
  tableName: string;
  /**
   * 取得を開始する行番号（0始まり）
   * @minimum 0
   */
  startRow: number;
  /**
   * 取得する行数（1〜10000、デフォルト500）
   * @minimum 1
   * @maximum 10000
   */
  fetchRows?: number;
}
