/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * プロット用列指定データ Arrow 取得リクエスト

グラフ描画に必要な列のみを選択して Arrow IPC 形式で返す。
列を絞ることでメモリ使用量と転送量を削減する。
 */
export type FetchPlotDataRequestBody = {
  /**
     * データを取得するテーブル名。ワークスペースに存在するテーブルの中から指定してください。
     * @minLength 1
     */
  tableName: string;
  /**
     * 取得する列名のリスト（1〜50列）。重複した列名は無視されます。
     * @minItems 1
     * @maxItems 50
     */
  columnNames: string[];
};
