/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

export type FGLSParamsMethod = typeof FGLSParamsMethod[keyof typeof FGLSParamsMethod];


export const FGLSParamsMethod = {
  fgls: 'fgls',
} as const;
