/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import type { FGLSParamsFglsMethod } from './fGLSParamsFglsMethod';
import { FGLSParamsMethod } from './fGLSParamsMethod';

export type FGLSParams = {
  method: FGLSParamsMethod;
  /** FGLS の推定手法。'heteroskedastic': OLS残差を用いた1ステップFGLS（不均一分散対応）。'ar1': AR(1)誤差構造を仮定した反復FGLS（GLSAR）。 */
  fglsMethod?: FGLSParamsFglsMethod;
  /**
     * ar1 選択時の収束判定イテレーション上限。heteroskedastic 選択時は無視される。
     * @minimum 1
     * @maximum 100
     */
  maxIter?: number;
};
