/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * FGLS の推定手法。'heteroskedastic': OLS残差を用いた1ステップFGLS（不均一分散対応）。'ar1': AR(1)誤差構造を仮定した反復FGLS（GLSAR）。
 */
export type FGLSParamsFglsMethod = typeof FGLSParamsFglsMethod[keyof typeof FGLSParamsFglsMethod];


export const FGLSParamsFglsMethod = {
  heteroskedastic: 'heteroskedastic',
  ar1: 'ar1',
} as const;
