/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import type { FilterCondition } from './filterCondition';
import type { LogicalOperatorType } from './logicalOperatorType';

/**
 * テーブルフィルタリクエスト（複数条件 AND / OR）
 */
export type FilterRequestBody = {
  /**
     * フィルタ条件を適用するテーブル名。ワークスペースに存在するテーブルの中から指定してください。
     * @minLength 1
     */
  tableName: string;
  /**
     * フィルタ結果を格納する新しいテーブル名。ワークスペースに存在しない名前を指定してください。
     * @minLength 1
     * @maxLength 128
     * @pattern ^[^\x00-\x1f\x7f]+$
     */
  newTableName: string;
  /** 複数条件を結合する論理演算子（and / or）。省略時は and。 */
  logicalOperator?: LogicalOperatorType;
  /**
     * フィルタ条件のリスト（1件以上）
     * @minItems 1
     */
  conditions: FilterCondition[];
};
