/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 単一条件フィルタレスポンス
 */
export interface FilterSingleConditionResult {
  /** 操作対象または生成されたテーブル名 */
  tableName: string;
}
