/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import type { FilterOperatorType } from './filterOperatorType';

/**
 * フィルタ条件の1要素
 */
export type FilterCondition = {
  /**
     * フィルタ条件を適用するカラム名。
     * @minLength 1
     */
  columnName: string;
  /** フィルタ条件の演算子（equals, notEquals, greaterThan, lessThan 等） */
  condition: FilterOperatorType;
  /** 比較対象がカラムかどうか。true: compareValue をカラム名として解釈、false: 定数値として解釈。 */
  isCompareColumn: boolean;
  /** 比較する値またはカラム名。isCompareColumn が true の場合はカラム名を指定。 */
  compareValue: unknown;
};
