/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

/**
 * 固定値のパラメータ
 */
export type FixedParams = {
  /** 分布の種類 */
  type: 'fixed';
  /** 固定値 */
  value: number;
};
