/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 固定値のパラメータ
 */
export interface FixedParams {
  /** 分布の種類 */
  type: 'fixed';
  /** 固定値 */
  value: number;
}
