/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import { GammaParamsType } from './gammaParamsType';

/**
 * ガンマ分布のパラメータ
 */
export type GammaParams = {
  /** 分布の種類 */
  type: GammaParamsType;
  /**
     * 形状パラメータ
     * @exclusiveMinimum 0
     */
  shapeParameter: number;
  /**
     * 尺度パラメータ
     * @exclusiveMinimum 0
     */
  scaleParameter: number;
};
