/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * ガンマ分布のパラメータ
 */
export type GammaParams = {
  /** 分布の種類 */
  type: 'gamma';
  /**
   * 形状パラメータ
   * @exclusiveMinimum 0
   */
  shape: number;
  /**
   * 尺度パラメータ
   * @exclusiveMinimum 0
   */
  scale: number;
};
