/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 分析結果詳細取得レスポンス
 */
export type GetAnalysisResultResult = {
  /** 分析結果の詳細データ */
  result: unknown;
};
