/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 全分析結果サマリー取得レスポンス
 */
export interface GetAllAnalysisResultsResult {
  /** 分析結果のサマリーリスト */
  results: unknown[];
}
