/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import type { AnalysisResultDetail } from './analysisResultDetail';

/**
 * 分析結果詳細取得レスポンス
 */
export type GetAnalysisResultResult = {
  /** 分析結果の詳細データ */
  result: AnalysisResultDetail;
};
