/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 全分析結果サマリー取得レスポンス
 */
export type GetAllAnalysisResultsResult = {
  /** 分析結果のサマリーリスト */
  results: unknown[];
};
