/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 分析結果詳細取得レスポンス
 */
export interface GetAnalysisResultResult {
  /** 分析結果の詳細データ */
  result: unknown;
}
