/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import type { ColumnInfo } from './columnInfo';

/**
 * カラムリスト取得レスポンス
 */
export type GetColumnListResult = {
  /** カラムリストを取得したテーブル名 */
  tableName: string;
  /** カラム情報のリスト */
  columnInfoList: ColumnInfo[];
};
