/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { ColumnInfo } from './columnInfo';

/**
 * カラムリスト取得レスポンス
 */
export interface GetColumnListResult {
  /** カラムリストを取得したテーブル名 */
  tableName: string;
  /** カラム情報のリスト */
  columnInfoList: ColumnInfo[];
}
