/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * アプリケーション設定取得レスポンス
 */
export interface GetSettingsResult {
  /** 実行環境のOS名（Windows / macOS / Linux） */
  osName: string;
  /** アプリケーションの表示言語（ja: 日本語, en: 英語） */
  language: string;
  /** 最後に開いたフォルダパス */
  lastOpenedPath: string;
  /** アプリケーションのテーマ（light / dark） */
  theme: string;
  /** ファイルエンコーディング */
  encoding: string;
  /** ログファイルの出力先パス */
  logPath: string;
}
