/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

/**
 * テーブルリスト取得レスポンス
 */
export type GetTableListResult = {
  /** ワークスペースに存在するテーブル名のリスト */
  tableNameList: string[];
};
