/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * テーブルリスト取得レスポンス
 */
export interface GetTableListResult {
  /** ワークスペースに存在するテーブル名のリスト */
  tableNameList: string[];
}
