/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

export type GLSParamsMethod = typeof GLSParamsMethod[keyof typeof GLSParamsMethod];


export const GLSParamsMethod = {
  gls: 'gls',
} as const;
