/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

export type HacStandardErrorMethod = typeof HacStandardErrorMethod[keyof typeof HacStandardErrorMethod];


export const HacStandardErrorMethod = {
  hac: 'hac',
} as const;
