/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import { HacStandardErrorMethod } from './hacStandardErrorMethod';

export type HacStandardError = {
  method: HacStandardErrorMethod;
  /**
   * 考慮する最大ラグ数
   * @minimum 0
   */
  maxlags: number;
  /** カーネルの種類 */
  kernel?: string;
  /** 小標本補正を行うか */
  useCorrection?: boolean;
};
