/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import type { MissingValueHandlingType } from './missingValueHandlingType';

/**
 * ヘックマン2段階推定リクエスト

選択方程式（Probit）と結果方程式（OLS）の2段階推定
によりサンプルセレクションバイアスを補正します。
 */
export type HeckmanRequestBody = {
  /**
     * 分析対象のテーブル名。ワークスペース内に存在するテーブル名を指定してください。
     * @minLength 1
     */
  tableName: string;
  /**
     * 分析結果の名前（省略時は自動生成）
     * @maxLength 128
     */
  resultName?: string;
  /**
     * 分析結果の説明メモ
     * @maxLength 512
     */
  description?: string;
  /**
     * 結果方程式の被説明変数列名。選択サンプル（selectionColumn=1）のみで推定されます。
     * @minLength 1
     */
  dependentVariable: string;
  /** 結果方程式の説明変数列名リスト。 */
  explanatoryVariables: string[];
  /**
     * 選択ダミー列名（0/1）。1 = 結果変数が観測されるサンプル。
     * @minLength 1
     */
  selectionColumn: string;
  /** 選択方程式（Probit）の説明変数列名リスト。除外制約として explanatoryVariables にない変数を 1 つ以上含む必要があります。 */
  selectionVariables: string[];
  /** 結果方程式（Step 2 OLS）に定数項を追加するか。 */
  hasConst?: boolean;
  /** 欠損値の処理方法（remove: 削除, ignore: 無視, error: エラー） */
  missingValueHandling?: MissingValueHandlingType;
  /** 1 段階目（Probit）の推定結果をレスポンスの firstStage に含めるか。 */
  reportFirstStage?: boolean;
};
