/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 分布の種類
 */
export type HypergeometricParamsType = typeof HypergeometricParamsType[keyof typeof HypergeometricParamsType];


export const HypergeometricParamsType = {
  hypergeometric: 'hypergeometric',
} as const;
