/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

/**
 * CSVファイルパス指定インポートリクエスト
 */
export interface ImportCsvByPathRequest {
  /**
   * インポートするCSVファイルのパス
   * @minLength 1
   * @maxLength 1024
   */
  filePath: string;
  /**
   * 作成するテーブル名
   * @minLength 1
   * @maxLength 255
   */
  tableName: string;
  /**
   * 区切り文字
   * @minLength 1
   * @maxLength 10
   */
  separator?: string;
}
