/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

/**
 * CSV ファイルのエンコーディング（CSV / TSV のみ有効）。utf8 / latin1 / ascii / gbk / windows-1252 / shift_jis から選択してください。
 */
export type ImportFileRequestBodyEncoding = typeof ImportFileRequestBodyEncoding[keyof typeof ImportFileRequestBodyEncoding];


export const ImportFileRequestBodyEncoding = {
  utf8: 'utf8',
  latin1: 'latin1',
  ascii: 'ascii',
  gbk: 'gbk',
  'windows-1252': 'windows-1252',
  shift_jis: 'shift_jis',
} as const;
