/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { ImportFileRequestBodyEncoding } from './importFileRequestBodyEncoding';

/**
 * ファイルパス指定インポートリクエスト（CSV / Excel / Parquet 共通）

拡張子に応じて適切なインポーターが自動選択されます。

- .csv / .tsv  → CSV インポーター（separator / encoding が有効）
- .xlsx / .xls → Excel インポーター（sheet_name が有効）
- .parquet     → Parquet インポーター
 */
export type ImportFileRequestBody = {
  /**
   * インポートするファイルの絶対パス。対応拡張子: .csv, .tsv, .xlsx, .xls, .parquet（相対パスはサポートされていません）。
   * @minLength 1
   * @maxLength 1024
   */
  filePath: string;
  /**
   * インポート後のテーブル名。ワークスペース内で既存のテーブル名と重複しない名前を指定してください。
   * @minLength 1
   * @maxLength 128
   * @pattern ^[^\x00-\x1f\x7f]+$
   */
  tableName: string;
  /**
   * CSV 区切り文字（CSV / TSV のみ有効）。カンマかタブ、もしくは 1〜10 文字の任意の文字列から選択してください。
   * @minLength 1
   * @maxLength 10
   */
  separator?: string;
  /** CSV ファイルのエンコーディング（CSV / TSV のみ有効）。utf8 / latin1 / ascii / gbk / windows-1252 / shift_jis から選択してください。 */
  encoding?: ImportFileRequestBodyEncoding;
  /** インポートする Excel シート名（Excel のみ有効）。省略または null の場合は先頭シートを読み込みます。シート名は大文字・小文字を区別します。 */
  sheetName?: string | null;
};
