/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

/**
 * ファイルパス指定インポートレスポンス
 */
export type ImportFileResult = {
  /** インポートによって作成されたテーブル名 */
  tableName: string;
};
