/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * ファイルパス指定インポートレスポンス
 */
export interface ImportFileResult {
  /** インポートによって作成されたテーブル名 */
  tableName: string;
}
