/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * セルデータ入力リクエスト
 */
export interface InputCellDataRequestBody {
  /**
   * セルデータを入力するテーブル名。ワークスペースに存在するテーブルの中から指定してください。
   * @minLength 1
   */
  tableName: string;
  /**
   * セルデータを入力するカラム名。ワークスペースに存在するテーブルの中から指定してください。
   * @minLength 1
   */
  columnName: string;
  /**
   * 更新するセルの行インデックス（0始まり）
   * @minimum 0
   */
  rowIndex: number;
  /** セルに入力する新しい値。カラムのデータ型に合わせた値を指定してください。 */
  newValue: unknown;
}
