/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

export type InstrumentalVariablesParamsMethod = typeof InstrumentalVariablesParamsMethod[keyof typeof InstrumentalVariablesParamsMethod];


export const InstrumentalVariablesParamsMethod = {
  iv: 'iv',
} as const;
