/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import type { InstrumentalVariablesParamsGmmWeightMatrix } from './instrumentalVariablesParamsGmmWeightMatrix';
import type { InstrumentalVariablesParamsIvMethod } from './instrumentalVariablesParamsIvMethod';
import { InstrumentalVariablesParamsMethod } from './instrumentalVariablesParamsMethod';

export type InstrumentalVariablesParams = {
  method: InstrumentalVariablesParamsMethod;
  /** 推定アルゴリズム。過剰識別かつ異分散がある場合はGMMを推奨 */
  ivMethod?: InstrumentalVariablesParamsIvMethod;
  /** @minItems 1 */
  instrumentalVariables: string[];
  /** @minItems 1 */
  endogenousVariables: string[];
  gmmWeightMatrix?: InstrumentalVariablesParamsGmmWeightMatrix;
};
