/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

/**
 * 推定アルゴリズム。過剰識別かつ異分散がある場合はGMMを推奨
 */
export type InstrumentalVariablesParamsIvMethod = typeof InstrumentalVariablesParamsIvMethod[keyof typeof InstrumentalVariablesParamsIvMethod];


export const InstrumentalVariablesParamsIvMethod = {
  '2sls': '2sls',
  gmm: 'gmm',
} as const;
