/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

export type InstrumentalVariablesParamsMethod = typeof InstrumentalVariablesParamsMethod[keyof typeof InstrumentalVariablesParamsMethod];


export const InstrumentalVariablesParamsMethod = {
  iv: 'iv',
} as const;
