/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

export type InstrumentalVariablesParamsGmmWeightMatrix = typeof InstrumentalVariablesParamsGmmWeightMatrix[keyof typeof InstrumentalVariablesParamsGmmWeightMatrix];


export const InstrumentalVariablesParamsGmmWeightMatrix = {
  uncentered: 'uncentered',
  robust: 'robust',
  hac: 'hac',
} as const;
