/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { InstrumentalVariablesParamsGmmWeightMatrix } from './instrumentalVariablesParamsGmmWeightMatrix';
import type { InstrumentalVariablesParamsIvMethod } from './instrumentalVariablesParamsIvMethod';
import type { InstrumentalVariablesParamsMethod } from './instrumentalVariablesParamsMethod';

export interface InstrumentalVariablesParams {
  method: InstrumentalVariablesParamsMethod;
  /** 推定アルゴリズム。過剰識別かつ異分散がある場合はGMMを推奨 */
  iv_method?: InstrumentalVariablesParamsIvMethod;
  instrumental_variables: string[];
  endogenous_variables: string[];
  gmm_weight_matrix?: InstrumentalVariablesParamsGmmWeightMatrix;
}
