/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

export type JoinType = typeof JoinType[keyof typeof JoinType];


export const JoinType = {
  inner: 'inner',
  left: 'left',
  right: 'right',
  full: 'full',
} as const;
