/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

export type LassoParamsMethod = typeof LassoParamsMethod[keyof typeof LassoParamsMethod];


export const LassoParamsMethod = {
  lasso: 'lasso',
} as const;
