/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

export type LogicalOperatorType = typeof LogicalOperatorType[keyof typeof LogicalOperatorType];


export const LogicalOperatorType = {
  and: 'and',
  or: 'or',
} as const;
