/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

export type LogitParamsMethod = typeof LogitParamsMethod[keyof typeof LogitParamsMethod];


export const LogitParamsMethod = {
  logit: 'logit',
} as const;
