/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

export type LogitParamsMethod = typeof LogitParamsMethod[keyof typeof LogitParamsMethod];


export const LogitParamsMethod = {
  logit: 'logit',
} as const;
