/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 残差種別。raw: 生残差 (y - p̂)、deviance: デビアンス残差。
 */
export type LogitParamsBinaryResidualType = typeof LogitParamsBinaryResidualType[keyof typeof LogitParamsBinaryResidualType];


export const LogitParamsBinaryResidualType = {
  raw: 'raw',
  deviance: 'deviance',
} as const;
