/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import type { BinaryChoiceRegularization } from './binaryChoiceRegularization';
import type { LogitParamsBinaryResidualType } from './logitParamsBinaryResidualType';
import { LogitParamsMethod } from './logitParamsMethod';

export type LogitParams = {
  regularization?: BinaryChoiceRegularization | null;
  /** 平均限界効果(AME)を計算するかどうか */
  calculateMarginalEffects?: boolean;
  /** 残差種別。raw: 生残差 (y - p̂)、deviance: デビアンス残差。 */
  binaryResidualType?: LogitParamsBinaryResidualType;
  method: LogitParamsMethod;
};
