/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 対数正規分布のパラメータ
 */
export interface LognormalParams {
  /** 分布の種類 */
  type: 'lognormal';
  /** 平均 */
  mean: number;
  /**
   * 標準偏差
   * @exclusiveMinimum 0
   */
  sigma: number;
}
