/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import { LognormalParamsType } from './lognormalParamsType';

/**
 * 対数正規分布のパラメータ
 */
export type LognormalParams = {
  /** 分布の種類 */
  type: LognormalParamsType;
  /** 対数空間での平均 */
  logMean: number;
  /**
     * 対数空間での標準偏差
     * @exclusiveMinimum 0
     */
  logStandardDeviation: number;
};
