/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 変換方法
 */
export type LogParamsMethod = typeof LogParamsMethod[keyof typeof LogParamsMethod];


export const LogParamsMethod = {
  log: 'log',
} as const;
