/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

export type MissingValueHandlingType = typeof MissingValueHandlingType[keyof typeof MissingValueHandlingType];


export const MissingValueHandlingType = {
  ignore: 'ignore',
  remove: 'remove',
  error: 'error',
} as const;
