/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

export type MissingHandlingMethod = typeof MissingHandlingMethod[keyof typeof MissingHandlingMethod];


export const MissingHandlingMethod = {
  pairwise: 'pairwise',
  listwise: 'listwise',
} as const;
