/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 列移動リクエスト
 */
export type MoveColumnRequestBody = {
  /**
     * 操作対象のテーブル名。ワークスペースに存在するテーブルの中から指定してください。
     * @minLength 1
     */
  tableName: string;
  /**
     * 移動する列名。既存の列名から指定してください。
     * @minLength 1
     */
  columnName: string;
  /** 挿入基準列名。指定した列の直前に移動列を挿入します。null を指定した場合は末尾に移動します。 */
  anchorColumnName?: string | null;
};
