/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 列移動レスポンス
 */
export type MoveColumnResult = {
  /** 列を移動したテーブル名 */
  tableName: string;
  /** 移動後の全列名リスト（順序付き） */
  columnNames: string[];
};
