/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import { NegativeBinomialParamsType } from './negativeBinomialParamsType';

/**
 * 負の二項分布のパラメータ
 */
export type NegativeBinomialParams = {
  /** 分布の種類 */
  type: NegativeBinomialParamsType;
  /**
     * 成功回数
     * @exclusiveMinimum 0
     */
  n: number;
  /**
     * 成功確率
     * @maximum 1
     * @exclusiveMinimum 0
     */
  p: number;
};
