/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */
import { NonRobustStandardErrorMethod } from './nonRobustStandardErrorMethod';

export type NonRobustStandardError = {
  method: NonRobustStandardErrorMethod;
};
