/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

export type NonRobustStandardErrorMethod = typeof NonRobustStandardErrorMethod[keyof typeof NonRobustStandardErrorMethod];


export const NonRobustStandardErrorMethod = {
  nonrobust: 'nonrobust',
} as const;
