/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

export type NonRobustStandardErrorMethod = typeof NonRobustStandardErrorMethod[keyof typeof NonRobustStandardErrorMethod];


export const NonRobustStandardErrorMethod = {
  nonrobust: 'nonrobust',
} as const;
