/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import { NormalParamsType } from './normalParamsType';

/**
 * 正規分布のパラメータ
 */
export type NormalParams = {
  /** 分布の種類 */
  type: NormalParamsType;
  /** 平均 */
  mean: number;
  /**
     * 標準偏差
     * @exclusiveMinimum 0
     */
  standardDeviation: number;
};
