/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

export type NullStrategy = typeof NullStrategy[keyof typeof NullStrategy];


export const NullStrategy = {
  exclude: 'exclude',
  as_category: 'as_category',
  error: 'error',
} as const;
