/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

export type OLSParamsMethod = typeof OLSParamsMethod[keyof typeof OLSParamsMethod];


export const OLSParamsMethod = {
  ols: 'ols',
} as const;
