/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */
import { OLSParamsMethod } from './oLSParamsMethod';

export type OLSParams = {
  method: OLSParamsMethod;
};
