/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import { OLSParamsMethod } from './oLSParamsMethod';

export type OLSParams = {
  method: OLSParamsMethod;
};
