/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 推定結果フォーマット出力レスポンス
 */
export type OutputResultResult = {
  /** フォーマット済み出力テキスト */
  content: string;
  /** 出力フォーマット (latex / markdown / text) */
  format: string;
};
