/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 出力フォーマット。latex: LaTeX tabular、markdown: Markdown テーブル、text: 固定幅テキスト
 */
export type OutputResultRequestFormat = typeof OutputResultRequestFormat[keyof typeof OutputResultRequestFormat];


export const OutputResultRequestFormat = {
  latex: 'latex',
  markdown: 'markdown',
  text: 'text',
} as const;
