/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

export type OutputResultFormat = typeof OutputResultFormat[keyof typeof OutputResultFormat];


export const OutputResultFormat = {
  latex: 'latex',
  markdown: 'markdown',
  text: 'text',
} as const;
