/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 変数名から表示ラベルへのマッピング辞書。未設定の変数は変数名をそのまま使用。
 */
export type OutputResultRequestVariableLabels = {[key: string]: string} | null;
