/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { PanelIvParamsGmmWeightMatrix } from './panelIvParamsGmmWeightMatrix';
import { PanelIvParamsMethod } from './panelIvParamsMethod';

export interface PanelIvParams {
  method: PanelIvParamsMethod;
  /**
   * 個体ID列名
   * @minLength 1
   */
  entityIdColumn: string;
  /** 時間列名 */
  timeColumn?: string | null;
  instrumentalVariables: string[];
  endogenousVariables: string[];
  gmmWeightMatrix?: PanelIvParamsGmmWeightMatrix;
}
