/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */
import type { PanelIvParamsGmmWeightMatrix } from './panelIvParamsGmmWeightMatrix';
import { PanelIvParamsMethod } from './panelIvParamsMethod';

export type PanelIvParams = {
  method: PanelIvParamsMethod;
  /**
     * 個体ID列名
     * @minLength 1
     */
  entityIdColumn: string;
  /** 時間列名 */
  timeColumn?: string | null;
  instrumentalVariables: string[];
  endogenousVariables: string[];
  gmmWeightMatrix?: PanelIvParamsGmmWeightMatrix;
};
