/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { PanelDataParamsMethod } from './panelDataParamsMethod';

export interface PanelDataParams {
  method: PanelDataParamsMethod;
  /**
   * 個体ID列名
   * @minLength 1
   */
  entityIdColumn: string;
  /** 時間列名 */
  timeColumn?: string | null;
}
