/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

export type PanelIvParamsMethod = typeof PanelIvParamsMethod[keyof typeof PanelIvParamsMethod];


export const PanelIvParamsMethod = {
  feiv: 'feiv',
} as const;
