/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * べき乗変換のパラメータ
 */
export type PowerParams = {
  /** 変換方法 */
  method: 'power';
  /** べき乗の指数 (省略時は2乗) */
  exponent?: number;
};
