/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */
import type { BinaryChoiceRegularization } from './binaryChoiceRegularization';
import type { ProbitParamsBinaryResidualType } from './probitParamsBinaryResidualType';
import { ProbitParamsMethod } from './probitParamsMethod';

export type ProbitParams = {
  regularization?: BinaryChoiceRegularization | null;
  /** 平均限界効果(AME)を計算するかどうか */
  calculateMarginalEffects?: boolean;
  /** 残差種別。raw: 生残差 (y - p̂)、deviance: デビアンス残差。 */
  binaryResidualType?: ProbitParamsBinaryResidualType;
  method: ProbitParamsMethod;
};
