/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

export type ProbitParamsMethod = typeof ProbitParamsMethod[keyof typeof ProbitParamsMethod];


export const ProbitParamsMethod = {
  probit: 'probit',
} as const;
