/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 残差種別。raw: 生残差 (y - p̂)、deviance: デビアンス残差。
 */
export type ProbitParamsBinaryResidualType = typeof ProbitParamsBinaryResidualType[keyof typeof ProbitParamsBinaryResidualType];


export const ProbitParamsBinaryResidualType = {
  raw: 'raw',
  deviance: 'deviance',
} as const;
