/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

export type RDDBandwidthSelectType = typeof RDDBandwidthSelectType[keyof typeof RDDBandwidthSelectType];


export const RDDBandwidthSelectType = {
  mserd: 'mserd',
  msetwo: 'msetwo',
  msesum: 'msesum',
  msecomb1: 'msecomb1',
  msecomb2: 'msecomb2',
  cerrd: 'cerrd',
  certwo: 'certwo',
  cersum: 'cersum',
  cercomb1: 'cercomb1',
  cercomb2: 'cercomb2',
} as const;
