/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

export type RDDKernelType = typeof RDDKernelType[keyof typeof RDDKernelType];


export const RDDKernelType = {
  triangular: 'triangular',
  epanechnikov: 'epanechnikov',
  uniform: 'uniform',
} as const;
