/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import type { RDDBandwidthSelectType } from './rDDBandwidthSelectType';
import type { RDDKernelType } from './rDDKernelType';
import type { RDDVceType } from './rDDVceType';

/**
 * 回帰不連続デザイン（RDD）分析リクエスト

rdrobust を使用したシャープ RDD 推定と診断を実行します。
バイアス補正済み推定・密度検定・プラシーボ検定を包括的に返します。
 */
export type RDDRequestBody = {
  /**
     * 分析対象のテーブル名。ワークスペース内に存在するテーブル名を指定してください。
     * @minLength 1
     */
  tableName: string;
  /**
     * 分析結果の名前（省略時は自動生成）
     * @maxLength 128
     */
  resultName?: string;
  /**
     * 分析結果の説明メモ
     * @maxLength 512
     */
  description?: string;
  /**
     * 結果変数（y）の列名。数値型カラムを指定してください。
     * @minLength 1
     */
  outcomeVariable: string;
  /**
     * 実行変数（score / forcing variable）の列名。カットオフ前後で処置割り当てが決まる連続変数。数値型カラムを指定してください。
     * @minLength 1
     */
  runningVariable: string;
  /** カットオフ値。実行変数がこの値以上の観測を処置群とみなします。デフォルトは 0。 */
  cutoff?: number;
  /** カーネル重み付け関数。triangular（デフォルト）/ epanechnikov / uniform。 */
  kernel?: RDDKernelType;
  /** バンド幅の自動選定アルゴリズム。mserd（デフォルト）: MSE 最小化・左右共通バンド幅。msetwo: MSE 最小化・左右独立バンド幅。cerrd/certwo: CER（Coverage Error Rate）最小化。 */
  bwSelect?: RDDBandwidthSelectType;
  /** 手動バンド幅。指定した場合 bwSelect による自動選択より優先されます。null の場合は bwSelect で自動選択します。 */
  h?: number | null;
  /**
     * 局所多項式の次数、1（線形、デフォルト）または2（2次式）を推奨。バイアス補正バンド幅には p+1 次多項式が使用されます。
     * @minimum 1
     * @maximum 4
     */
  p?: number;
  /** 分散共分散行列の推定方式（標準誤差の計算方法）。nn: 最近傍法（デフォルト）。hc1 / hc3: HC 不均一分散一致推定量。cluster: クラスタ標準誤差。nncluster: 最近傍クラスタ標準誤差。 */
  vce?: RDDVceType;
  /**
     * 信頼区間の水準（デフォルト: 0.95 → 95%）
     * @minimum 0.5
     * @maximum 0.999
     */
  confidenceLevel?: number;
  /**
     * 散布図用ビン数（左右合計）。デフォルト: 30（左右各 15 本）。
     * @minimum 10
     * @maximum 200
     */
  nBins?: number;
  /** プラシーボ検定用の偽境界値リスト。null の場合は実行変数の範囲に基づきカットオフ左右 ±5% 相当の 2 点を自動生成します。 */
  placeboCutoffs?: number[] | null;
};
