/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * RDD 分析実行レスポンス
 */
export type RDDResult = {
  /** 保存された分析結果の一意 ID */
  resultId: string;
};
