/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

export type RDDVceType = typeof RDDVceType[keyof typeof RDDVceType];


export const RDDVceType = {
  nn: 'nn',
  hc1: 'hc1',
  hc3: 'hc3',
  cluster: 'cluster',
  nncluster: 'nncluster',
} as const;
