/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 回帰分析実行レスポンス
 */
export interface RegressionResult {
  /** 保存された分析結果の一意 ID */
  resultId: string;
}
