/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 分析タイプ
 */
export type RegressionRequestType = typeof RegressionRequestType[keyof typeof RegressionRequestType];


export const RegressionRequestType = {
  ols: 'ols',
  logit: 'logit',
  probit: 'probit',
  tobit: 'tobit',
  fe: 'fe',
  re: 're',
  iv: 'iv',
  feiv: 'feiv',
  lasso: 'lasso',
  ridge: 'ridge',
} as const;
