/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

/**
 * ハイパーパラメータ (例: Lasso/Ridge の alpha)
 */
export type RegressionRequestHyperParameters = { [key: string]: unknown };
