/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { MissingValueHandlingType } from './missingValueHandlingType';
import type { RegressionParams } from './regressionParams';
import type { StandardErrorSettings } from './standardErrorSettings';

/**
 * 統合回帰分析リクエスト

全ての回帰分析タイプを単一のエンドポイントで扱うための
統合スキーマです。
 */
export interface RegressionRequestBody {
  /**
   * 分析対象のテーブル名。ワークスペース内に存在するテーブル名を指定してください。
   * @minLength 1
   */
  tableName: string;
  /**
   * 分析結果の名前（省略時は被説明変数名を使用）
   * @maxLength 128
   */
  resultName?: string;
  /**
   * 分析結果の説明メモ
   * @maxLength 512
   */
  description?: string;
  /**
   * 被説明変数（目的変数）の列名。テーブル内に存在するカラム名を指定してください。
   * @minLength 1
   */
  dependentVariable: string;
  /** 説明変数の列名のリスト。テーブル内に存在するカラム名を指定してください。 */
  explanatoryVariables: string[];
  /** 定数項を設計行列に追加するかどうか */
  hasConst?: boolean;
  /** 欠損値の処理方法（remove: 該当行を削除、ignore: そのまま使用、error: エラーとして扱う） */
  missingValueHandling?: MissingValueHandlingType;
  /** 回帰分析手法の詳細パラメータ。method フィールドで手法（ols, fe, re, iv 等）を指定します。 */
  analysis: RegressionParams;
  /** 標準誤差の計算方法設定。nonrobust, robust（HC）, cluster, hac（Newey-West）から選択します。 */
  standardError: StandardErrorSettings;
}
