/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 計算手法
 */
export type RegressionRequestMethod = typeof RegressionRequestMethod[keyof typeof RegressionRequestMethod];


export const RegressionRequestMethod = {
  ols: 'ols',
  wls: 'wls',
  gls: 'gls',
  gmm: 'gmm',
} as const;
