/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 標準誤差計算方法
 */
export type RegressionRequestStandardErrorMethod = typeof RegressionRequestStandardErrorMethod[keyof typeof RegressionRequestStandardErrorMethod];


export const RegressionRequestStandardErrorMethod = {
  nonrobust: 'nonrobust',
  hc0: 'hc0',
  hc1: 'hc1',
  hc2: 'hc2',
  hc3: 'hc3',
  hac: 'hac',
  clustered: 'clustered',
} as const;
