/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import type { FEParams } from './fEParams';
import type { FGLSParams } from './fGLSParams';
import type { GLSParams } from './gLSParams';
import type { InstrumentalVariablesParams } from './instrumentalVariablesParams';
import type { LassoParams } from './lassoParams';
import type { LogitParams } from './logitParams';
import type { OLSParams } from './oLSParams';
import type { PanelIvParams } from './panelIvParams';
import type { ProbitParams } from './probitParams';
import type { REParams } from './rEParams';
import type { RidgeParams } from './ridgeParams';
import type { TobitParams } from './tobitParams';
import type { WLSParams } from './wLSParams';

export type RegressionParams = OLSParams | LassoParams | RidgeParams | LogitParams | ProbitParams | InstrumentalVariablesParams | FEParams | REParams | TobitParams | PanelIvParams | WLSParams | GLSParams | FGLSParams;
