/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 回帰分析実行レスポンス
 */
export type RegressionResult = {
  /** 保存された分析結果の一意 ID */
  resultId: string;
};
