/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { RegressionRequestHyperParameters } from './regressionRequestHyperParameters';
import type { RegressionRequestMethod } from './regressionRequestMethod';
import type { RegressionRequestMissingValueHandling } from './regressionRequestMissingValueHandling';
import type { RegressionRequestStandardErrorMethod } from './regressionRequestStandardErrorMethod';
import type { RegressionRequestStandardErrorParams } from './regressionRequestStandardErrorParams';
import type { RegressionRequestType } from './regressionRequestType';

/**
 * 統合回帰分析リクエスト

全ての回帰分析タイプを単一のエンドポイントで扱うための
統合スキーマです。
 */
export interface RegressionRequest {
  /** 分析タイプ */
  type: RegressionRequestType;
  /** 計算手法 */
  method?: RegressionRequestMethod;
  /** 対象テーブル名 */
  tableName: string;
  /** 分析結果の名前（ユーザー指定） */
  name?: string;
  /** 分析結果の説明・メモ（ユーザー指定） */
  description?: string;
  /** 被説明変数の列名 */
  dependentVariable: string;
  /** 説明変数の列名リスト */
  explanatoryVariables: string[];
  /** 標準誤差計算方法 */
  standardErrorMethod?: RegressionRequestStandardErrorMethod;
  /** 標準誤差計算のパラメータ (例: クラスタ変数名) */
  standardErrorParams?: RegressionRequestStandardErrorParams;
  /** ハイパーパラメータ (例: Lasso/Ridge の alpha) */
  hyperParameters?: RegressionRequestHyperParameters;
  /** t分布を使用するか */
  useTDistribution?: boolean;
  /** 定数項を追加するか */
  hasConst?: boolean;
  /** 欠損値の処理方法 */
  missingValueHandling?: RegressionRequestMissingValueHandling;
  /** 個体ID列名 (固定効果・変量効果の場合に必要) */
  entityIdColumn?: string | null;
  /** 時間列名 (パネルデータ分析の場合に使用) */
  timeColumn?: string | null;
  /** 操作変数の列名リスト (IV の場合に必要) */
  instrumentalVariables?: string[] | null;
  /** 内生変数の列名リスト (IV の場合に必要) */
  endogenousVariables?: string[] | null;
  /** 左側打ち切り値 (Tobit の場合に使用、デフォルト0.0) */
  leftCensoringLimit?: number | null;
  /** 右側打ち切り値 (Tobit の場合に使用) */
  rightCensoringLimit?: number | null;
}
