/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { RegularizedRegressionParamsMethod } from './regularizedRegressionParamsMethod';

export interface RegularizedRegressionParams {
  method: RegularizedRegressionParamsMethod;
  /**
   * 正則化強度のパラメータ
   * @minimum 0
   */
  alpha?: number;
  /** ブートストラップ法による標準誤差を計算するかどうか */
  calculateSe?: boolean;
  /**
   * ブートストラップ法のイテレーション回数
   * @minimum 100
   * @maximum 10000
   */
  bootstrapIterations?: number;
  /** ブートストラップの乱数シード。None の場合は固定しない。実験の再現性を確保する場合は整数値を指定する。 */
  randomState?: number | null;
}
