/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * カラム名変更レスポンス
 */
export interface RenameColumnResult {
  /** カラム名を変更したテーブル名 */
  tableName: string;
  /** 変更後のカラム名 */
  columnName: string;
}
