/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

/**
 * テーブル名変更レスポンス
 */
export type RenameTableResult = {
  /** 操作対象または生成されたテーブル名 */
  tableName: string;
};
