/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

/**
 * カラム名変更リクエスト
 */
export interface RenameColumnRequest {
  /**
   * テーブル名
   * @minLength 1
   * @maxLength 255
   */
  tableName: string;
  /**
   * 元のカラム名
   * @minLength 1
   * @maxLength 255
   */
  oldColumnName: string;
  /**
   * 新しいカラム名
   * @minLength 1
   * @maxLength 255
   */
  newColumnName: string;
}
