/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

/**
 * テーブル名変更リクエスト
 */
export type RenameTableRequestBody = {
  /**
     * 変更前のテーブル名
     * @minLength 1
     */
  oldTableName: string;
  /**
     * 変更後の新しいテーブル名
     * @minLength 1
     * @maxLength 128
     * @pattern ^[^\x00-\x1f\x7f]+$
     */
  newTableName: string;
};
