/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * カラム名変更リクエスト
 */
export interface RenameColumnRequestBody {
  /**
   * カラム名を変更するテーブル名。ワークスペースに存在するテーブルの中から指定してください。
   * @minLength 1
   */
  tableName: string;
  /**
   * 変更前のカラム名。ワークスペースに存在するテーブルの中から指定してください。
   * @minLength 1
   */
  oldColumnName: string;
  /**
   * 新しいカラム名。既存のカラム名と重複しない名前を指定してください。
   * @minLength 1
   * @maxLength 128
   * @pattern ^[^\x00-\x1f\x7f]+$
   */
  newColumnName: string;
}
