/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import { REParamsMethod } from './rEParamsMethod';

export type REParams = {
  /**
   * 個体ID列名
   * @minLength 1
   */
  entityIdColumn: string;
  /** 時間列名 */
  timeColumn?: string | null;
  method: REParamsMethod;
};
