/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

export type REParamsMethod = typeof REParamsMethod[keyof typeof REParamsMethod];


export const REParamsMethod = {
  re: 're',
} as const;
