/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

export type REParamsMethod = typeof REParamsMethod[keyof typeof REParamsMethod];


export const REParamsMethod = {
  re: 're',
} as const;
