/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */
import type { RidgeParamsAlphaConvention } from './ridgeParamsAlphaConvention';
import { RidgeParamsMethod } from './ridgeParamsMethod';

export type RidgeParams = {
  /**
     * 正則化強度のパラメータ
     * @minimum 0
     */
  alpha?: number;
  /** alpha の規約。'glmnet': R の glmnet パッケージ準拠（計量経済学・統計学のデフォルト）。'sklearn': scikit-learn 準拠。 */
  alphaConvention?: RidgeParamsAlphaConvention;
  /**
     * 座標降下法の最大反復回数。収束しない場合は増やしてください。
     * @minimum 1
     * @maximum 100000
     */
  maxIter?: number;
  /** ブートストラップ法による標準誤差を計算するかどうか */
  calculateSe?: boolean;
  /**
     * ブートストラップ法のイテレーション回数
     * @minimum 100
     * @maximum 10000
     */
  bootstrapIterations?: number;
  /** ブートストラップの乱数シード。None の場合は固定しない。 */
  randomState?: number | null;
  method: RidgeParamsMethod;
};
