/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

export type RidgeParamsMethod = typeof RidgeParamsMethod[keyof typeof RidgeParamsMethod];


export const RidgeParamsMethod = {
  ridge: 'ridge',
} as const;
