/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { RobustStandardErrorHcType } from './robustStandardErrorHcType';
import type { RobustStandardErrorMethod } from './robustStandardErrorMethod';

export interface RobustStandardError {
  method: RobustStandardErrorMethod;
  hcType?: RobustStandardErrorHcType;
}
