/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { RobustStandardErrorHcType } from './robustStandardErrorHcType';
import { RobustStandardErrorMethod } from './robustStandardErrorMethod';

export type RobustStandardError = {
  method: RobustStandardErrorMethod;
  hcType?: RobustStandardErrorHcType;
};
