/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

export type RobustStandardErrorMethod = typeof RobustStandardErrorMethod[keyof typeof RobustStandardErrorMethod];


export const RobustStandardErrorMethod = {
  robust: 'robust',
} as const;
