/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

/**
 * 平方根変換のパラメータ
 */
export type RootParams = {
  /** 変換方法 */
  method: 'root';
  /**
     * ルートの指数 (省略時は平方根)
     * @exclusiveMinimum 0
     */
  rootIndex?: number;
};
