/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

/**
 * 検定に使用する1サンプルの指定（テーブル名・列名のペア）
 */
export type SampleInput = {
  /**
     * サンプルを取得するテーブル名。
     * @minLength 1
     */
  tableName: string;
  /**
     * サンプルとして使用する列名。
     * @minLength 1
     */
  columnName: string;
};
