/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 検定に使用する1サンプルの指定（テーブル名・列名のペア）
 */
export interface SampleInput {
  /**
   * サンプルを取得するテーブル名。
   * @minLength 1
   */
  tableName: string;
  /**
   * サンプルとして使用する列名。
   * @minLength 1
   */
  columnName: string;
}
