/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 連番のパラメータ
 */
export type SequenceParams = {
  /** 分布の種類 */
  type: 'sequence';
  /** 開始値 */
  start?: number;
  /** 増分（負値で降順連番） */
  step?: number;
};
