/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

export interface SortInstruction {
  /**
   * カラム名
   * @minLength 1
   */
  column_name: string;
  ascending: boolean;
}
