/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */

/**
 * カラムソートレスポンス
 */
export type SortColumnsResult = {
  /** ソートを実行したテーブル名 */
  tableName: string;
};
