/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

export type SortInstruction = {
  /**
     * カラム名
     * @minLength 1
     */
  columnName: string;
  ascending: boolean;
};
