/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 有意性記号の設定
 */
export type StarConfig = {
  /** 有意水準の閾値（例: 0.05） */
  threshold: number;
  /** 有意性を示す記号（例: '**'） */
  symbol: string;
};
