/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 統計量の種別と値
 */
export type StatisticValue = {
  /** 統計量のタイプ（mean, median 等） */
  type: string;
  /** 統計量の計算値 */
  value: unknown;
};
