/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

export type StatisticalTestType = typeof StatisticalTestType[keyof typeof StatisticalTestType];


export const StatisticalTestType = {
  't-test': 't-test',
  'z-test': 'z-test',
  'f-test': 'f-test',
} as const;
