/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import type { AlternativeHypothesis } from './alternativeHypothesis';

/**
 * 統計検定のオプション設定
 */
export type StatisticalTestOptions = {
  /** 対立仮説の方向。two-sided: 両側検定（デフォルト）、larger: 右側検定、smaller: 左側検定 */
  alternative?: AlternativeHypothesis;
  /** 1 群検定における比較基準値（デフォルト: 0.0） */
  mu?: number | null;
  /** 対応のある検定を行うかどうか（デフォルト: False） */
  paired?: boolean;
  /** t 検定で等分散を仮定するかどうか。False の場合は Welch の t 検定を使用（デフォルト: True） */
  equalVar?: boolean;
};
