/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 統計検定レスポンス。
詳細は GET /api/analysis/results/{resultId} で取得できる
 */
export type StatisticalTestResult = {
  /** 分析結果の一意 ID。詳細は GET /api/analysis/results/{resultId} で取得可能。 */
  resultId: string;
};
