/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import type { ConfidenceIntervalBounds } from './confidenceIntervalBounds';

/**
 * 統計検定レスポンス
 */
export type StatisticalTestResult = {
  /** 検定統計量（t 値 / Z 値 / F 値） */
  statistic: number;
  /** 有意確率（p 値） */
  pValue: number;
  /** 自由度（t 検定: 分子自由度、F 検定: df1、z 検定は None） */
  df: number | null;
  /** 分母自由度（F 検定のみ設定。df=分子自由度、df2=分母自由度） */
  df2?: number | null;
  /** 95% 信頼区間（F 検定では None） */
  confidenceInterval: ConfidenceIntervalBounds | null;
  /** 効果量（t 検定: Cohen's d、ANOVA: η²、z 検定・分散比 F 検定では None） */
  effectSize: number | null;
};
