/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { ClearAllAnalysisResultsResult } from './clearAllAnalysisResultsResult';

export type SuccessResponseClearAllAnalysisResultsResult = {
  /** レスポンスコード */
  code?: string;
  /** 処理結果 */
  result: ClearAllAnalysisResultsResult;
};
