/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import type { DeleteTableResult } from './deleteTableResult';

export type SuccessResponseDeleteTableResult = {
  /** レスポンスコード */
  code?: string;
  /** 処理結果 */
  result: DeleteTableResult;
};
