/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */
import type { AddDummyColumnResult } from './addDummyColumnResult';

export type SuccessResponseAddDummyColumnResult = {
  /** レスポンスコード */
  code?: string;
  /** 処理結果 */
  result: AddDummyColumnResult;
};
