/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { DeleteAnalysisResultResult } from './deleteAnalysisResultResult';

export interface SuccessResponseDeleteAnalysisResultResult {
  /** レスポンスコード */
  code?: string;
  /** 処理結果 */
  result: DeleteAnalysisResultResult;
}
