/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import type { ExportFileResult } from './exportFileResult';

export type SuccessResponseExportFileResult = {
  /** レスポンスコード */
  code?: string;
  /** 処理結果 */
  result: ExportFileResult;
};
