/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import type { DescriptiveStatisticsResult } from './descriptiveStatisticsResult';

export type SuccessResponseDescriptiveStatisticsResult = {
  /** レスポンスコード */
  code?: string;
  /** 処理結果 */
  result: DescriptiveStatisticsResult;
};
