/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { AddColumnResult } from './addColumnResult';

export interface SuccessResponseAddColumnResult {
  /** レスポンスコード */
  code?: string;
  /** 処理結果 */
  result: AddColumnResult;
}
