/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import type { AddSimulationColumnResult } from './addSimulationColumnResult';

export type SuccessResponseAddSimulationColumnResult = {
  /** レスポンスコード */
  code?: string;
  /** 処理結果 */
  result: AddSimulationColumnResult;
};
