/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import type { SortColumnsResult } from './sortColumnsResult';

export type SuccessResponseSortColumnsResult = {
  /** レスポンスコード */
  code?: string;
  /** 処理結果 */
  result: SortColumnsResult;
};
