/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */
import type { ImportFileResult } from './importFileResult';

export type SuccessResponseImportFileResult = {
  /** レスポンスコード */
  code?: string;
  /** 処理結果 */
  result: ImportFileResult;
};
