/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */
import type { FetchDataToJsonResult } from './fetchDataToJsonResult';

export type SuccessResponseFetchDataToJsonResult = {
  /** レスポンスコード */
  code?: string;
  /** 処理結果 */
  result: FetchDataToJsonResult;
};
