/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { CreateSimulationDataTableResult } from './createSimulationDataTableResult';

export interface SuccessResponseCreateSimulationDataTableResult {
  /** レスポンスコード */
  code?: string;
  /** 処理結果 */
  result: CreateSimulationDataTableResult;
}
