/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.4.0
 */
import type { CreateGroupStatisticsTableResult } from './createGroupStatisticsTableResult';

export type SuccessResponseCreateGroupStatisticsTableResult = {
  /** レスポンスコード */
  code?: string;
  /** 処理結果 */
  result: CreateGroupStatisticsTableResult;
};
