/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import type { GetSettingsResult } from './getSettingsResult';

export type SuccessResponseGetSettingsResult = {
  /** レスポンスコード */
  code?: string;
  /** 処理結果 */
  result: GetSettingsResult;
};
