/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.4.0
 */
import type { UnbiasednessResult } from './unbiasednessResult';

export type SuccessResponseUnbiasednessResult = {
  /** レスポンスコード */
  code?: string;
  /** 処理結果 */
  result: UnbiasednessResult;
};
