/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { AddDummyColumnResult } from './addDummyColumnResult';

export interface SuccessResponseAddDummyColumnResult {
  /** レスポンスコード */
  code?: string;
  /** 処理結果 */
  result: AddDummyColumnResult;
}
