/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

export type TobitParamsMethod = typeof TobitParamsMethod[keyof typeof TobitParamsMethod];


export const TobitParamsMethod = {
  tobit: 'tobit',
} as const;
