/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { TobitParamsMethod } from './tobitParamsMethod';

export interface TobitParams {
  method: TobitParamsMethod;
  /** 左側打ち切り値。この値以下のデータが打ち切られていると見なす */
  left_censoring_limit?: number | null;
  /** 右側打ち切り値 */
  right_censoring_limit?: number | null;
}
