/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

/**
 * カラム変換レスポンス
 */
export type TransformColumnResult = {
  /** 変換カラムを追加したテーブル名 */
  tableName: string;
  /** 追加した変換カラム名 */
  columnName: string;
};
