/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import type { TransformMethodParams } from './transformMethodParams';

/**
 * 変換方法設定
 */
export type TransformMethodConfig = TransformMethodParams;
