/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */

export type TransformMethodParamsMethod = typeof TransformMethodParamsMethod[keyof typeof TransformMethodParamsMethod];


export const TransformMethodParamsMethod = {
  log: 'log',
  power: 'power',
  root: 'root',
} as const;
