/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import type { LogParams } from './logParams';
import type { PowerParams } from './powerParams';
import type { RootParams } from './rootParams';

/**
 * 変換方法設定
 */
export type TransformMethodConfig = LogParams | PowerParams | RootParams;
