/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

/**
 * カラム変換リクエスト
 */
export interface TransformColumnRequest {
  /**
   * テーブル名
   * @minLength 1
   * @maxLength 255
   */
  tableName: string;
  /**
   * 元となるカラム名
   * @minLength 1
   * @maxLength 255
   */
  sourceColumnName: string;
  /**
   * 新しい列名
   * @minLength 1
   * @maxLength 255
   */
  newColumnName: string;
  /**
   * 変換メソッド
   * @minLength 1
   */
  transformMethod: string;
  /** 対数の底（オプション） */
  logBase?: number | null;
  /** 指数（オプション） */
  exponent?: number | null;
  /** 累乗根の次数（オプション） */
  rootIndex?: number | null;
}
