/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.4.0
 */

/**
 * 不偏性シミュレーション結果
 */
export type UnbiasednessResult = {
  /** 各試行の OLS β̂ リスト */
  betaEstimates: number[];
  /** 真の傾きパラメータ */
  trueBeta: number;
};
