/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */

/**
 * 分布の種類
 */
export type UniformParamsType = typeof UniformParamsType[keyof typeof UniformParamsType];


export const UniformParamsType = {
  uniform: 'uniform',
} as const;
