/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */

/**
 * アプリケーション設定更新レスポンス（更新後の全設定を返す）
 */
export type UpdateSettingsResult = {
  /** アプリケーションの表示言語（ja: 日本語, en: 英語） */
  language: string;
  /** 最後に開いたフォルダパス */
  lastOpenedPath: string;
  /** アプリケーションのテーマ（light / dark） */
  theme: string;
  /** ファイルエンコーディング */
  encoding: string;
  /** ログファイルの出力先パス */
  logPath: string;
};
