/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import type { AnalysisResultDetail } from './analysisResultDetail';
import type { AnalysisResultSummary } from './analysisResultSummary';

/**
 * 分析結果メタデータ更新レスポンス
 */
export type UpdateAnalysisResultResult = {
  /** 更新後の分析結果サマリー */
  updatedSummary: AnalysisResultSummary;
  /** 更新後の分析結果詳細 */
  updatedDetail: AnalysisResultDetail;
};
