/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}
