/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import { WLSParamsMethod } from './wLSParamsMethod';

export type WLSParams = {
  method: WLSParamsMethod;
  /**
     * 観測値ごとの重み (1/σ²ᵢ) を格納した列名。正の数値型列が必要（全値 > 0）。
     * @minLength 1
     */
  weightsColumn: string;
};
