/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * 拡張子に基づいてファイルをインポートしてテーブルを作成するエンドポイント

対応拡張子:
- ``.csv`` / ``.tsv`` → CSV インポーター（separator / encoding が有効）
- ``.xlsx`` / ``.xls`` → Excel インポーター（sheet_name が有効）
- ``.parquet``         → Parquet インポーター

インポート成功後、ファイルの親ディレクトリを
``last_opened_path`` としてメモリ上の設定に反映する。
ファイルへの保存はアプリ終了時に一括して行われる。

Parameters
----------
request : Request
    FastAPI のリクエストオブジェクト
body : ImportFileRequestBody
    リクエストボディ
tables_store : TablesStoreDep
    依存注入されたテーブルストア
settings_store : SettingsStoreDep
    依存注入された設定ストア

Returns
-------
JSONResponse
    処理結果
 * @summary Import File
 */
export const ImportFileHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})

export const importFileBodyFilePathMax = 1024;

export const importFileBodyTableNameMax = 128;


export const importFileBodyTableNameRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');
export const importFileBodySeparatorDefault = `,`;
export const importFileBodySeparatorMax = 10;

export const importFileBodyEncodingDefault = `utf8`;
export const importFileBodySheetNameOneMax = 31;


export const importFileBodySheetNameOneRegExp = new RegExp('^[^\/\\\\?\*:\\[\\]]+$');


export const ImportFileBody = zod.object({
  "filePath": zod.string().min(1).max(importFileBodyFilePathMax).describe('インポートするファイルの絶対パス。対応拡張子: .csv, .tsv, .xlsx, .xls, .parquet（相対パスはサポートされていません）。'),
  "tableName": zod.string().min(1).max(importFileBodyTableNameMax).regex(importFileBodyTableNameRegExp).describe('インポート後のテーブル名。ワークスペース内で既存のテーブル名と重複しない名前を指定してください。'),
  "separator": zod.string().min(1).max(importFileBodySeparatorMax).default(importFileBodySeparatorDefault).describe('CSV 区切り文字（CSV \/ TSV のみ有効）。カンマかタブ、もしくは 1〜10 文字の任意の文字列から選択してください。'),
  "encoding": zod.enum(['utf8', 'latin1', 'ascii', 'gbk', 'windows-1252', 'shift_jis']).default(importFileBodyEncodingDefault).describe('CSV ファイルのエンコーディング（CSV \/ TSV のみ有効）。utf8 \/ latin1 \/ ascii \/ gbk \/ windows-1252 \/ shift_jis から選択してください。'),
  "sheetName": zod.union([zod.string().min(1).max(importFileBodySheetNameOneMax).regex(importFileBodySheetNameOneRegExp).describe('Excelのシート名（31文字以内、使用不可記号あり）'),zod.null()]).optional().describe('インポートする Excel シート名（Excel のみ有効）。省略または null の場合は先頭シートを読み込みます。シート名は大文字・小文字を区別します。')
}).describe('ファイルパス指定インポートリクエスト（CSV \/ Excel \/ Parquet 共通）\n\n拡張子に応じて適切なインポーターが自動選択されます。\n\n- .csv \/ .tsv  → CSV インポーター（separator \/ encoding が有効）\n- .xlsx \/ .xls → Excel インポーター（sheet_name が有効）\n- .parquet     → Parquet インポーター')

export const importFileResponseCodeDefault = `OK`;

export const ImportFileResponse = zod.object({
  "code": zod.string().default(importFileResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('インポートによって作成されたテーブル名')
}).describe('処理結果')
})

/**
 * format に基づいてテーブルをファイルにエクスポートするエンドポイント

対応形式：
- ``csv``     → CSV エクスポーター（separator / include_header が有効）
- ``excel``   → Excel エクスポーター（sheet_name / include_header が有効）
- ``parquet`` → Parquet エクスポーター

エクスポート成功後、出力先ディレクトリを
``last_opened_path`` としてメモリ上の設定に反映する。
ファイルへの保存はアプリ終了時に一括して行われる。

Parameters
----------
request : Request
    FastAPI のリクエストオブジェクト
body : ExportFileRequestBody
    リクエストボディ
tables_store : TablesStoreDep
    依存注入されたテーブルストア
settings_store : SettingsStoreDep
    依存注入された設定ストア

Returns
-------
JSONResponse
    処理結果
 * @summary Export File
 */
export const ExportFileHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})


export const exportFileBodyDirectoryPathMax = 1024;

export const exportFileBodyFileNameMax = 255;


export const exportFileBodyFileNameRegExp = new RegExp('^[^\\\\\/:\*?\"<>|]+$');
export const exportFileBodySeparatorDefault = `,`;
export const exportFileBodySeparatorMax = 10;

export const exportFileBodyEncodingDefault = `utf8`;
export const exportFileBodyIncludeHeaderDefault = true;
export const exportFileBodySheetNameOneMax = 31;


export const exportFileBodySheetNameOneRegExp = new RegExp('^[^\/\\\\?\*:\\[\\]]+$');


export const ExportFileBody = zod.object({
  "tableName": zod.string().min(1).describe('エクスポートするテーブル名。ワークスペース内に存在するテーブル名を指定してください。'),
  "directoryPath": zod.string().min(1).max(exportFileBodyDirectoryPathMax).describe('出力ファイルのディレクトリの絶対パス（相対パスはサポートされていません）。'),
  "fileName": zod.string().min(1).max(exportFileBodyFileNameMax).regex(exportFileBodyFileNameRegExp).describe('出力ファイルのベース名（拡張子なし）。同名ファイルが存在する場合は上書きされます。'),
  "format": zod.enum(['csv', 'excel', 'parquet']).describe('出力するファイル形式。csv \/ excel \/ parquet から選択してください。選択した形式に応じた拡張子が自動付与されます。'),
  "separator": zod.string().min(1).max(exportFileBodySeparatorMax).default(exportFileBodySeparatorDefault).describe('CSV 区切り文字（CSV のみ有効）。カンマかタブ、もしくは 1〜10 文字の任意の文字列から選択してください。'),
  "encoding": zod.enum(['utf8', 'latin1', 'ascii', 'gbk', 'windows-1252', 'shift_jis']).default(exportFileBodyEncodingDefault).describe('CSV ファイルの出力エンコーディング（CSV のみ有効）。utf8 \/ latin1 \/ ascii \/ gbk \/ windows-1252 \/ shift_jis から選択してください。'),
  "includeHeader": zod.boolean().default(exportFileBodyIncludeHeaderDefault).describe('ヘッダ行を含めるか否か（CSV のみ有効）。デフォルトは True（ヘッダあり）。'),
  "sheetName": zod.union([zod.string().min(1).max(exportFileBodySheetNameOneMax).regex(exportFileBodySheetNameOneRegExp).describe('Excelのシート名（31文字以内、使用不可記号あり）'),zod.null()]).optional().describe('出力する Excel シート名（Excel のみ有効）。省略または null の場合は \'Sheet1\' を使用します。')
}).describe('ファイルパス指定エクスポートリクエスト（CSV \/ Excel \/ Parquet 共通）\n\n``format`` に応じて適切なエクスポーターが自動選択され、\nファイル拡張子も自動で付与されます。\n\n- ``csv``     →\n    CSV エクスポーター（separator \/ encoding \/ include_header が有効）\n- ``excel``   → Excel エクスポーター（sheet_name が有効）\n- ``parquet`` → Parquet エクスポーター')

export const exportFileResponseCodeDefault = `OK`;

export const ExportFileResponse = zod.object({
  "code": zod.string().default(exportFileResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "filePath": zod.string().describe('出力したファイルのフルパス（拡張子付き）')
}).describe('処理結果')
})

