/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.3.0
 */
import * as zod from 'zod';


/**
 * 信頼区間計算を行うエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : ConfidenceIntervalRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Confidence Interval
 */
export const ConfidenceIntervalHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})



export const confidenceIntervalBodyConfidenceLevelExclusiveMin = 0;
export const confidenceIntervalBodyConfidenceLevelExclusiveMax = 1;

export const confidenceIntervalBodyBootstrapNResamplesDefault = 1000;
export const confidenceIntervalBodyBootstrapNResamplesMin = 100;
export const confidenceIntervalBodyBootstrapNResamplesMax = 100000;



export const ConfidenceIntervalBody = zod.object({
  "tableName": zod.string().min(1).describe('信頼区間を計算する対象テーブル名。ワークスペース内に存在するテーブル名を指定してください。'),
  "columnName": zod.string().min(1).describe('信頼区間を計算する対象カラム名。テーブル内に存在するカラム名を指定してください。'),
  "confidenceLevel": zod.number().gt(confidenceIntervalBodyConfidenceLevelExclusiveMin).lt(confidenceIntervalBodyConfidenceLevelExclusiveMax).describe('信頼水準（例: 0.95 = 95%信頼区間）'),
  "statisticType": zod.enum(['mean', 'median', 'proportion', 'variance', 'standard_deviation']).describe('信頼区間を計算する統計量のタイプ。（mean: 平均、median: 中央値、proportion: 割合、variance: 分散、standard_deviation: 標準偏差）'),
  "bootstrapNResamples": zod.number().min(confidenceIntervalBodyBootstrapNResamplesMin).max(confidenceIntervalBodyBootstrapNResamplesMax).default(confidenceIntervalBodyBootstrapNResamplesDefault).describe('Bootstrap 法（中央値 CI）のリサンプリング回数。statisticType が median のときのみ有効。（デフォルト: 1000、100〜100000）'),
  "bootstrapSeed": zod.union([zod.number(),zod.null()]).optional().describe('Bootstrap 法の乱数シード。None の場合は毎回異なる結果になる。再現性が必要な場合に整数を指定してください。（デフォルト: None）')
}).describe('信頼区間計算リクエスト')

export const confidenceIntervalResponseCodeDefault = `OK`;

export const ConfidenceIntervalResponse = zod.object({
  "code": zod.string().default(confidenceIntervalResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "resultId": zod.string().describe('分析結果の一意 ID。詳細は GET \/api\/analysis\/results\/{resultId} で取得可能。')
}).describe('処理結果')
})

/**
 * 記述統計を計算するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DescriptiveStatisticsRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Descriptive Statistics
 */
export const DescriptiveStatisticsHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})







export const DescriptiveStatisticsBody = zod.object({
  "tableName": zod.string().min(1).describe('記述統計を計算する対象テーブル名。ワークスペース内に存在するテーブル名を指定してください。'),
  "columnNameList": zod.array(zod.string().min(1).describe('カラム名')).min(1).describe('記述統計を計算する対象カラム名のリスト。テーブル内に存在するカラム名を指定してください。複数カラムを指定することもできます。'),
  "statistics": zod.array(zod.enum(['mean', 'median', 'mode', 'variance', 'std_dev', 'range', 'iqr', 'count', 'null_count', 'null_ratio', 'population_variance'])).min(1).describe('計算する統計量のリスト（mean: 平均、median: 中央値、mode: 最頻値、variance: 不偏分散、std_dev: 標準偏差、range: 範囲、iqr: 四分位数範囲、count: 有効サンプル数、null_count: null数、null_ratio: null割合、population_variance: 母分散）')
}).describe('記述統計リクエスト')

export const descriptiveStatisticsResponseCodeDefault = `OK`;

export const DescriptiveStatisticsResponse = zod.object({
  "code": zod.string().default(descriptiveStatisticsResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "resultId": zod.string().describe('分析結果の一意 ID。詳細は GET \/api\/analysis\/results\/{resultId} で取得可能。')
}).describe('処理結果')
})

/**
 * 相関係数テーブル作成を行うエンドポイント

指定されたテーブルの各列間の相関係数行列を計算し、
新しいテーブルとして保存します。

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateCorrelationTableRequestBody
    リクエストボディ
tables_store : TablesStoreDep
    テーブルストア依存性

Returns
-------
JSONResponse
    処理結果（新規作成されたテーブル名）
 * @summary Create Correlation Table
 */
export const CreateCorrelationTableHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})



export const createCorrelationTableBodyColumnNamesMin = 2;


export const createCorrelationTableBodyMethodDefault = `pearson`;
export const createCorrelationTableBodyDecimalPlacesDefault = 3;
export const createCorrelationTableBodyDecimalPlacesMax = 15;

export const createCorrelationTableBodyLowerTriangleOnlyDefault = false;
export const createCorrelationTableBodyMissingHandlingDefault = `pairwise`;

export const CreateCorrelationTableBody = zod.object({
  "tableName": zod.string().min(1).describe('相関係数を計算する元テーブル名。'),
  "columnNames": zod.array(zod.string().min(1).describe('カラム名')).min(createCorrelationTableBodyColumnNamesMin).describe('相関係数を計算する対象カラム名のリスト。2列以上を指定してください。'),
  "newTableName": zod.string().min(1).describe('結果を格納する新規テーブル名。'),
  "method": zod.enum(['pearson', 'spearman', 'kendall']).default(createCorrelationTableBodyMethodDefault).describe('相関係数の計算手法。pearson: ピアソン積率相関係数（デフォルト）、spearman: スピアマン順位相関係数、kendall: ケンドールの順位相関係数'),
  "decimalPlaces": zod.number().min(1).max(createCorrelationTableBodyDecimalPlacesMax).default(createCorrelationTableBodyDecimalPlacesDefault).describe('丸め桁数（1～15、デフォルト: 3）'),
  "lowerTriangleOnly": zod.boolean().default(createCorrelationTableBodyLowerTriangleOnlyDefault).describe('True の場合、上三角部分の値を null に置き換えて返す。デフォルト: False。'),
  "missingHandling": zod.enum(['pairwise', 'listwise']).default(createCorrelationTableBodyMissingHandlingDefault).describe('欠損値の処理方法。pairwise: ペア単位で欠損を除外して計算（デフォルト）、listwise: 欠損を含む行をすべての列で一括削除してから計算')
}).describe('相関係数テーブル作成リクエスト')

export const createCorrelationTableResponseCodeDefault = `OK`;

export const CreateCorrelationTableResponse = zod.object({
  "code": zod.string().default(createCorrelationTableResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('新規作成された相関係数テーブルの名前。')
}).describe('処理結果')
})

/**
 * 統計的検定を実行するエンドポイント

t 検定・z 検定・F 検定（分散比検定 / ANOVA）を実行し、
検定統計量・p 値・自由度・信頼区間・効果量を返します。

Parameters
----------
request : Request
    FastAPI のリクエストオブジェクト
body : StatisticalTestRequestBody
    リクエストボディ
tables_store : TablesStoreDep
    テーブルストア依存性

Returns
-------
JSONResponse
    処理結果
 * @summary Statistical Test
 */
export const StatisticalTestHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})




export const statisticalTestBodyOptionsAlternativeDefault = `two-sided`;
export const statisticalTestBodyOptionsPairedDefault = false;
export const statisticalTestBodyOptionsEqualVarDefault = true;
export const statisticalTestBodyOptionsConfidenceLevelDefault = 0.95;
export const statisticalTestBodyOptionsConfidenceLevelExclusiveMin = 0;
export const statisticalTestBodyOptionsConfidenceLevelExclusiveMax = 1;



export const StatisticalTestBody = zod.object({
  "testType": zod.enum(['t-test', 'z-test', 'f-test']).describe('実行する統計検定の種類。t-test: t 検定、z-test: z 検定、f-test: F 検定 \/ ANOVA'),
  "samples": zod.array(zod.object({
  "tableName": zod.string().min(1).describe('サンプルを取得するテーブル名。'),
  "columnName": zod.string().min(1).describe('サンプルとして使用する列名。')
}).describe('検定に使用する1サンプルの指定（テーブル名・列名のペア）')).min(1).describe('比較対象となるサンプルのリスト。各要素にテーブル名と列名を指定する。'),
  "options": zod.object({
  "alternative": zod.enum(['two-sided', 'larger', 'smaller']).default(statisticalTestBodyOptionsAlternativeDefault).describe('対立仮説の方向。two-sided: 両側検定（デフォルト）、larger: 右側検定、smaller: 左側検定'),
  "mu": zod.union([zod.number(),zod.null()]).optional().describe('1 群検定における比較基準値（デフォルト: 0.0）'),
  "paired": zod.boolean().default(statisticalTestBodyOptionsPairedDefault).describe('対応のある検定を行うかどうか（デフォルト: False）'),
  "equalVar": zod.boolean().default(statisticalTestBodyOptionsEqualVarDefault).describe('t 検定で等分散を仮定するかどうか。False の場合は Welch の t 検定を使用（デフォルト: True）'),
  "confidenceLevel": zod.number().gt(statisticalTestBodyOptionsConfidenceLevelExclusiveMin).lt(statisticalTestBodyOptionsConfidenceLevelExclusiveMax).default(statisticalTestBodyOptionsConfidenceLevelDefault).describe('検定結果に付与する信頼区間の信頼水準。例: 0.95 = 95%信頼区間（デフォルト: 0.95）。t 検定・z 検定に適用。f 検定は信頼区間なし。')
}).optional().describe('検定オプション（対立仮説・等分散仮定・対応の有無など）')
}).describe('統計検定リクエスト')

export const statisticalTestResponseCodeDefault = `OK`;

export const StatisticalTestResponse = zod.object({
  "code": zod.string().default(statisticalTestResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "resultId": zod.string().describe('分析結果の一意 ID。詳細は GET \/api\/analysis\/results\/{resultId} で取得可能。')
}).describe('処理結果')
})

