/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * 信頼区間計算を行うエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : ConfidenceIntervalRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Confidence Interval Endpoint
 */
export const confidenceIntervalEndpointApiStatisticsConfidenceIntervalPostBodyTableNameMax = 255;

export const confidenceIntervalEndpointApiStatisticsConfidenceIntervalPostBodyColumnNameMax = 255;

export const confidenceIntervalEndpointApiStatisticsConfidenceIntervalPostBodyConfidenceLevelExclusiveMin = 0;
export const confidenceIntervalEndpointApiStatisticsConfidenceIntervalPostBodyConfidenceLevelExclusiveMax = 1;

export const confidenceIntervalEndpointApiStatisticsConfidenceIntervalPostBodyStatisticTypeMax = 50;



export const ConfidenceIntervalEndpointApiStatisticsConfidenceIntervalPostBody = zod.object({
  "tableName": zod.string().min(1).max(confidenceIntervalEndpointApiStatisticsConfidenceIntervalPostBodyTableNameMax).describe('テーブル名'),
  "columnName": zod.string().min(1).max(confidenceIntervalEndpointApiStatisticsConfidenceIntervalPostBodyColumnNameMax).describe('対象カラム名'),
  "confidenceLevel": zod.number().gt(confidenceIntervalEndpointApiStatisticsConfidenceIntervalPostBodyConfidenceLevelExclusiveMin).lt(confidenceIntervalEndpointApiStatisticsConfidenceIntervalPostBodyConfidenceLevelExclusiveMax).describe('信頼水準 (例: 0.95)'),
  "statisticType": zod.string().min(1).max(confidenceIntervalEndpointApiStatisticsConfidenceIntervalPostBodyStatisticTypeMax).describe('統計量のタイプ (mean, median, etc.)')
}).describe('信頼区間計算リクエスト')

export const ConfidenceIntervalEndpointApiStatisticsConfidenceIntervalPostResponse = zod.unknown()

/**
 * 記述統計を計算するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DescriptiveStatisticsRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Descriptive Statistics Endpoint
 */
export const descriptiveStatisticsEndpointApiStatisticsDescriptivePostBodyTableNameMax = 255;





export const DescriptiveStatisticsEndpointApiStatisticsDescriptivePostBody = zod.object({
  "tableName": zod.string().min(1).max(descriptiveStatisticsEndpointApiStatisticsDescriptivePostBodyTableNameMax).describe('テーブル名'),
  "columnNameList": zod.array(zod.string()).min(1).describe('対象カラム名のリスト'),
  "statistics": zod.array(zod.string()).min(1).describe('統計量のリスト')
}).describe('記述統計リクエスト')

export const DescriptiveStatisticsEndpointApiStatisticsDescriptivePostResponse = zod.unknown()

