/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * 信頼区間計算を行うエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : ConfidenceIntervalRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Confidence Interval Endpoint
 */
export const confidenceIntervalEndpointBodyTableNameMax = 255;

export const confidenceIntervalEndpointBodyColumnNameMax = 255;

export const confidenceIntervalEndpointBodyConfidenceLevelExclusiveMin = 0;
export const confidenceIntervalEndpointBodyConfidenceLevelExclusiveMax = 1;

export const confidenceIntervalEndpointBodyStatisticTypeMax = 50;



export const ConfidenceIntervalEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(confidenceIntervalEndpointBodyTableNameMax).describe('テーブル名'),
  "columnName": zod.string().min(1).max(confidenceIntervalEndpointBodyColumnNameMax).describe('対象カラム名'),
  "confidenceLevel": zod.number().gt(confidenceIntervalEndpointBodyConfidenceLevelExclusiveMin).lt(confidenceIntervalEndpointBodyConfidenceLevelExclusiveMax).describe('信頼水準 (例: 0.95)'),
  "statisticType": zod.string().min(1).max(confidenceIntervalEndpointBodyStatisticTypeMax).describe('統計量のタイプ (mean, median, etc.)')
}).describe('信頼区間計算リクエスト')

export const ConfidenceIntervalEndpointResponse = zod.unknown()

/**
 * 記述統計を計算するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DescriptiveStatisticsRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Descriptive Statistics Endpoint
 */
export const descriptiveStatisticsEndpointBodyTableNameMax = 255;





export const DescriptiveStatisticsEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(descriptiveStatisticsEndpointBodyTableNameMax).describe('テーブル名'),
  "columnNameList": zod.array(zod.string()).min(1).describe('対象カラム名のリスト'),
  "statistics": zod.array(zod.string()).min(1).describe('統計量のリスト')
}).describe('記述統計リクエスト')

export const DescriptiveStatisticsEndpointResponse = zod.unknown()

