/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * ルートエンドポイント
 * @summary Root
 */
export const RootResponse = zod.unknown()

/**
 * ヘルスチェック
 * @summary Health Check
 */
export const HealthCheckResponse = zod.unknown()

