version: "3.9"
services:
  analysis-api-server:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        UID: ${UID:-20000}
        GID: ${GID:-20000}
        DEV_ENV: "development"
    tty: true
    volumes:
      - ../.devcontainer:/economicon/.devcontainer
      - ../.github:/economicon/.github
      - ../.vscode:/economicon/economicon/.vscode
      - ../api:/economicon/economiconServer
      - ../app:/economicon/economicon/app
      - ../SampleData:/economicon/economicon/SampleData
      - ../.env:/economicon/economicon/.env
      - ../.gitignore:/economicon/economicon/.gitignore
      - ../README.md:/economicon/README.md
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:8000:8000"
    working_dir: /economicon/economicon
