/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * アプリ終了前クリーンアップエンドポイント

フロントエンドの CloseRequested ハンドラから呼び出される。
分析結果ファイルの削除と設定の保存を行う。

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
analysis_result_store : AnalysisResultStoreDep
    依存注入された分析結果ストア
settings_store : SettingsStoreDep
    依存注入された設定ストア

Returns
-------
JSONResponse
    処理結果
 * @summary Shutdown
 */
export const ShutdownHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})

export const ShutdownResponse = zod.unknown()

