/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.1.0
 */
import type {
  AddDiagnosticColumnsRequestBody,
  AddDummyColumnRequestBody,
  AddLagLeadColumnRequestBody,
  AddSimulationColumnRequestBody,
  CalculateColumnRequestBody,
  CastColumnRequestBody,
  ConfidenceIntervalRequestBody,
  CreateCorrelationTableRequestBody,
  CreateJoinTableRequestBody,
  CreateSimulationDataTableRequestBody,
  CreateUnionTableRequestBody,
  DeleteColumnRequestBody,
  DeleteTableRequestBody,
  DescriptiveStatisticsRequestBody,
  DuplicateColumnRequestBody,
  DuplicateTableRequestBody,
  ExportFileRequestBody,
  FetchDataToArrowRequestBody,
  FetchDataToJsonRequestBody,
  FilterSingleConditionRequestBody,
  GetColumnListRequestBody,
  ImportFileRequestBody,
  InputCellDataRequestBody,
  OutputResultRequest,
  RegressionRequestBody,
  RenameColumnRequestBody,
  RenameTableRequestBody,
  SortColumnsRequestBody,
  StatisticalTestRequestBody,
  SuccessResponseAddDiagnosticColumnsResult,
  SuccessResponseAddDummyColumnResult,
  SuccessResponseAddLagLeadColumnResult,
  SuccessResponseAddSimulationColumnResult,
  SuccessResponseCalculateColumnResult,
  SuccessResponseCastColumnResult,
  SuccessResponseClearAllAnalysisResultsResult,
  SuccessResponseClearTablesResult,
  SuccessResponseConfidenceIntervalResult,
  SuccessResponseCreateCorrelationTableResult,
  SuccessResponseCreateJoinTableResult,
  SuccessResponseCreateSimulationDataTableResult,
  SuccessResponseCreateUnionTableResult,
  SuccessResponseDeleteAnalysisResultResult,
  SuccessResponseDeleteColumnResult,
  SuccessResponseDeleteTableResult,
  SuccessResponseDescriptiveStatisticsResult,
  SuccessResponseDuplicateColumnResult,
  SuccessResponseDuplicateTableResult,
  SuccessResponseExportFileResult,
  SuccessResponseFetchDataToJsonResult,
  SuccessResponseFilterSingleConditionResult,
  SuccessResponseGetAllAnalysisResultsResult,
  SuccessResponseGetAnalysisResultResult,
  SuccessResponseGetColumnListResult,
  SuccessResponseGetSettingsResult,
  SuccessResponseGetTableListResult,
  SuccessResponseImportFileResult,
  SuccessResponseInputCellDataResult,
  SuccessResponseOutputResultResult,
  SuccessResponseRegressionResult,
  SuccessResponseRenameColumnResult,
  SuccessResponseRenameTableResult,
  SuccessResponseShutdownResult,
  SuccessResponseSortColumnsResult,
  SuccessResponseStatisticalTestResult,
  SuccessResponseTransformColumnResult,
  SuccessResponseUpdateSettingsResult,
  TransformColumnRequestBody,
  UpdateSettingsRequest
} from './model';

import { customInstance } from './mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getEconomiconAppAPI = () => {
/**
 * ヘルスチェック
 * @summary Health Check
 */
const healthCheck = (
    
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/health`, method: 'GET'
    },
      options);
    }
  
/**
 * ダミー変数カラムを追加するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : AddDummyColumnRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Add Dummy Column
 */
const addDummyColumn = (
    addDummyColumnRequestBody: AddDummyColumnRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseAddDummyColumnResult>>,) => {
      return customInstance<SuccessResponseAddDummyColumnResult>(
      {url: `/api/column/add-dummy`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addDummyColumnRequestBody
    },
      options);
    }
  
/**
 * カラムを削除するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DeleteColumnRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Delete Column
 */
const deleteColumn = (
    deleteColumnRequestBody: DeleteColumnRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseDeleteColumnResult>>,) => {
      return customInstance<SuccessResponseDeleteColumnResult>(
      {url: `/api/column/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteColumnRequestBody
    },
      options);
    }
  
/**
 * 列名変更エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : RenameColumnRequestBody
    リクエストボディ
    - tableName: テーブル名
    - oldColumnName: 旧列名
    - newColumnName: 新列名

Returns
-------
JSONResponse
    処理結果
 * @summary Rename Column
 */
const renameColumn = (
    renameColumnRequestBody: RenameColumnRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseRenameColumnResult>>,) => {
      return customInstance<SuccessResponseRenameColumnResult>(
      {url: `/api/column/rename`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: renameColumnRequestBody
    },
      options);
    }
  
/**
 * ラグ・リードカラムを追加するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : AddLagLeadColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Add Lag Lead Column
 */
const addLagLeadColumn = (
    addLagLeadColumnRequestBody: AddLagLeadColumnRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseAddLagLeadColumnResult>>,) => {
      return customInstance<SuccessResponseAddLagLeadColumnResult>(
      {url: `/api/column/add-lag-lead`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addLagLeadColumnRequestBody
    },
      options);
    }
  
/**
 * シミュレーションカラムを追加するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : AddSimulationColumnRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Add Simulation Column
 */
const addSimulationColumn = (
    addSimulationColumnRequestBody: AddSimulationColumnRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseAddSimulationColumnResult>>,) => {
      return customInstance<SuccessResponseAddSimulationColumnResult>(
      {url: `/api/column/add-simulation`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addSimulationColumnRequestBody
    },
      options);
    }
  
/**
 * カラム計算を実行するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CalculateColumnRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Calculate Column
 */
const calculateColumn = (
    calculateColumnRequestBody: CalculateColumnRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseCalculateColumnResult>>,) => {
      return customInstance<SuccessResponseCalculateColumnResult>(
      {url: `/api/column/calculate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: calculateColumnRequestBody
    },
      options);
    }
  
/**
 * カラムを複製するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DuplicateColumnRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Duplicate Column
 */
const duplicateColumn = (
    duplicateColumnRequestBody: DuplicateColumnRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseDuplicateColumnResult>>,) => {
      return customInstance<SuccessResponseDuplicateColumnResult>(
      {url: `/api/column/duplicate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: duplicateColumnRequestBody
    },
      options);
    }
  
/**
 * 列の変換処理エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : TransformColumnRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Transform Column
 */
const transformColumn = (
    transformColumnRequestBody: TransformColumnRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseTransformColumnResult>>,) => {
      return customInstance<SuccessResponseTransformColumnResult>(
      {url: `/api/column/transform`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: transformColumnRequestBody
    },
      options);
    }
  
/**
 * カラムリストを取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : GetColumnListRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Get Column List
 */
const getColumnList = (
    getColumnListRequestBody: GetColumnListRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseGetColumnListResult>>,) => {
      return customInstance<SuccessResponseGetColumnListResult>(
      {url: `/api/column/get-list`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getColumnListRequestBody
    },
      options);
    }
  
/**
 * 列のソート処理エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : SortColumnsRequestBody
    リクエストボディ
    - tableName: テーブル名
    - sortColumns: ソート列情報

Returns
-------
JSONResponse
    処理結果
 * @summary Sort Columns
 */
const sortColumns = (
    sortColumnsRequestBody: SortColumnsRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseSortColumnsResult>>,) => {
      return customInstance<SuccessResponseSortColumnsResult>(
      {url: `/api/column/sort`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sortColumnsRequestBody
    },
      options);
    }
  
/**
 * 列型変換エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CastColumnRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Cast Column
 */
const castColumn = (
    castColumnRequestBody: CastColumnRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseCastColumnResult>>,) => {
      return customInstance<SuccessResponseCastColumnResult>(
      {url: `/api/column/cast`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: castColumnRequestBody
    },
      options);
    }
  
/**
 * 結合テーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateJoinTableRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Join Table
 */
const createJoinTable = (
    createJoinTableRequestBody: CreateJoinTableRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseCreateJoinTableResult>>,) => {
      return customInstance<SuccessResponseCreateJoinTableResult>(
      {url: `/api/table/create-join`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createJoinTableRequestBody
    },
      options);
    }
  
/**
 * ユニオンテーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateUnionTableRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Union Table
 */
const createUnionTable = (
    createUnionTableRequestBody: CreateUnionTableRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseCreateUnionTableResult>>,) => {
      return customInstance<SuccessResponseCreateUnionTableResult>(
      {url: `/api/table/create-union`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUnionTableRequestBody
    },
      options);
    }
  
/**
 * シミュレーションデータテーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateSimulationDataTableRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Simulation Data Table
 */
const createSimulationDataTable = (
    createSimulationDataTableRequestBody: CreateSimulationDataTableRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseCreateSimulationDataTableResult>>,) => {
      return customInstance<SuccessResponseCreateSimulationDataTableResult>(
      {url: `/api/table/create-simulation-data`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSimulationDataTableRequestBody
    },
      options);
    }
  
/**
 * テーブルを削除するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DeleteTableRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Delete Table
 */
const deleteTable = (
    deleteTableRequestBody: DeleteTableRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseDeleteTableResult>>,) => {
      return customInstance<SuccessResponseDeleteTableResult>(
      {url: `/api/table/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteTableRequestBody
    },
      options);
    }
  
/**
 * テーブルを複製するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DuplicateTableRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Duplicate Table
 */
const duplicateTable = (
    duplicateTableRequestBody: DuplicateTableRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseDuplicateTableResult>>,) => {
      return customInstance<SuccessResponseDuplicateTableResult>(
      {url: `/api/table/duplicate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: duplicateTableRequestBody
    },
      options);
    }
  
/**
 * テーブル名変更エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : RenameTableRequestBody
    リクエストボディ
    - oldTableName: 旧テーブル名
    - newTableName: 新テーブル名

Returns
-------
JSONResponse
    処理結果
 * @summary Rename Table
 */
const renameTable = (
    renameTableRequestBody: RenameTableRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseRenameTableResult>>,) => {
      return customInstance<SuccessResponseRenameTableResult>(
      {url: `/api/table/rename`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: renameTableRequestBody
    },
      options);
    }
  
/**
 * テーブルリストを取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト

Returns
-------
JSONResponse
    処理結果
 * @summary Get Table List
 */
const getTableList = (
    
 options?: SecondParameter<typeof customInstance<SuccessResponseGetTableListResult>>,) => {
      return customInstance<SuccessResponseGetTableListResult>(
      {url: `/api/table/get-list`, method: 'GET'
    },
      options);
    }
  
/**
 * 全テーブルをクリアするエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト

Returns
-------
JSONResponse
    処理結果
 * @summary Clear Tables
 */
const clearTables = (
    
 options?: SecondParameter<typeof customInstance<SuccessResponseClearTablesResult>>,) => {
      return customInstance<SuccessResponseClearTablesResult>(
      {url: `/api/table/clear-all`, method: 'DELETE'
    },
      options);
    }
  
/**
 * データをJSON形式で取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : FetchDataToJsonRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Fetch Data To Json
 */
const fetchDataToJson = (
    fetchDataToJsonRequestBody: FetchDataToJsonRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseFetchDataToJsonResult>>,) => {
      return customInstance<SuccessResponseFetchDataToJsonResult>(
      {url: `/api/table/fetch-data-to-json`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: fetchDataToJsonRequestBody
    },
      options);
    }
  
/**
 * データをApache Arrow IPC形式の生バイナリで返すエンドポイント

仮想スクロール用のチャンク取得API。
JSON包装なしでArrow IPC形式生バイナリを直接返す。
メタデータ（totalRows/startRow/endRow/tableName）は
Arrowスキーマメタデータに埋め込む。

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : FetchDataToArrowRequestBody
    リクエストボディ

Returns
-------
Response
    Arrow IPC形式生バイナリ
 * @summary Fetch Data To Arrow
 */
const fetchDataToArrow = (
    fetchDataToArrowRequestBody: FetchDataToArrowRequestBody,
 options?: SecondParameter<typeof customInstance<Blob>>,) => {
      return customInstance<Blob>(
      {url: `/api/table/fetch-data-to-arrow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: fetchDataToArrowRequestBody,
        responseType: 'blob'
    },
      options);
    }
  
/**
 * セルデータ入力エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : InputCellDataRequestBody
    リクエストボディ
    - tableName: テーブル名
    - columnName: 列名
    - rowIndex: 行インデックス
    - newValue: 新しい値

Returns
-------
JSONResponse
    処理結果
 * @summary Input Cell Data
 */
const inputCellData = (
    inputCellDataRequestBody: InputCellDataRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseInputCellDataResult>>,) => {
      return customInstance<SuccessResponseInputCellDataResult>(
      {url: `/api/table/input-cell-data`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: inputCellDataRequestBody
    },
      options);
    }
  
/**
 * 単一条件フィルタリングを実行するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : FilterSingleConditionRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Filter Single Condition
 */
const filterSingleCondition = (
    filterSingleConditionRequestBody: FilterSingleConditionRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseFilterSingleConditionResult>>,) => {
      return customInstance<SuccessResponseFilterSingleConditionResult>(
      {url: `/api/table/filter-single-condition`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filterSingleConditionRequestBody
    },
      options);
    }
  
/**
 * 統合回帰分析エンドポイント

typeフィールドに応じて適切な分析手法を選択し、実行します。

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : RegressionRequestBody
    統合回帰分析リクエスト
    - type: 分析タイプ (ols, logit, probit, tobit, fe, re, iv,
      feiv, lasso, ridge)
    - tableName: 対象テーブル名
    - dependentVariable: 被説明変数
    - explanatoryVariables: 説明変数のリスト
    - その他分析固有のパラメータ

Returns
-------
JSONResponse
    分析結果またはエラーメッセージ
 * @summary Regression
 */
const regression = (
    regressionRequestBody: RegressionRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseRegressionResult>>,) => {
      return customInstance<SuccessResponseRegressionResult>(
      {url: `/api/analysis/regression`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: regressionRequestBody
    },
      options);
    }
  
/**
 * すべての分析結果のサマリーを取得

Returns
-------
JSONResponse
    分析結果のサマリーリスト
 * @summary Get All Analysis Results
 */
const getAllAnalysisResults = (
    
 options?: SecondParameter<typeof customInstance<SuccessResponseGetAllAnalysisResultsResult>>,) => {
      return customInstance<SuccessResponseGetAllAnalysisResultsResult>(
      {url: `/api/analysis/results`, method: 'GET'
    },
      options);
    }
  
/**
 * すべての分析結果を削除

Returns
-------
JSONResponse
    削除成功メッセージ
 * @summary Clear All Analysis Results
 */
const clearAllAnalysisResults = (
    
 options?: SecondParameter<typeof customInstance<SuccessResponseClearAllAnalysisResultsResult>>,) => {
      return customInstance<SuccessResponseClearAllAnalysisResultsResult>(
      {url: `/api/analysis/results`, method: 'DELETE'
    },
      options);
    }
  
/**
 * 指定されたIDの分析結果を取得

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
result_id : str
    結果のID

Returns
-------
JSONResponse
    分析結果の詳細
 * @summary Get Analysis Result
 */
const getAnalysisResult = (
    resultId: string,
 options?: SecondParameter<typeof customInstance<SuccessResponseGetAnalysisResultResult>>,) => {
      return customInstance<SuccessResponseGetAnalysisResultResult>(
      {url: `/api/analysis/results/${resultId}`, method: 'GET'
    },
      options);
    }
  
/**
 * 指定されたIDの分析結果を削除

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
result_id : str
    削除する結果のID

Returns
-------
JSONResponse
    削除成功メッセージ
 * @summary Delete Analysis Result
 */
const deleteAnalysisResult = (
    resultId: string,
 options?: SecondParameter<typeof customInstance<SuccessResponseDeleteAnalysisResultResult>>,) => {
      return customInstance<SuccessResponseDeleteAnalysisResultResult>(
      {url: `/api/analysis/results/${resultId}`, method: 'DELETE'
    },
      options);
    }
  
/**
 * 推定済みモデルから予測値・残差を抽出してテーブルに列追加する

指定された分析結果 ID に対応するモデルをロードし、予測値・残差などの
診断列を元のテーブルに追加します。

Parameters
----------
request : Request
    FastAPI のリクエストオブジェクト
body : AddDiagnosticColumnsRequestBody
    - tableName: 追加先テーブル名
    - resultId: 分析結果の UUID
    - target: "fitted" / "residual" / "both"
    - standardized: 標準化残差を含めるか（OLS 系のみ有効）
    - includeInterval: 95%信頼区間を含めるか
    - feType: "total" または "within"（FE/RE のみ有効）

Returns
-------
JSONResponse
    追加したテーブル名と列名リスト
 * @summary Add Diagnostic Columns
 */
const addDiagnosticColumns = (
    addDiagnosticColumnsRequestBody: AddDiagnosticColumnsRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseAddDiagnosticColumnsResult>>,) => {
      return customInstance<SuccessResponseAddDiagnosticColumnsResult>(
      {url: `/api/analysis/regression/add-diagnostic-columns`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addDiagnosticColumnsRequestBody
    },
      options);
    }
  
/**
 * 推定結果をテキスト / Markdown / LaTeX 形式で整形出力する

指定した分析結果 ID のリストから係数表などを生成します。
複数 ID を指定するとモデル比較表を生成します。

Parameters
----------
request : Request
    FastAPI のリクエストオブジェクト
body : OutputResultRequest
    - resultIds: 出力する分析結果 ID のリスト（1件以上）
    - format: 出力形式（text / markdown / latex）
    - statInParentheses: 括弧内統計量（se / t / p / none）
    - significanceStars: 有意性記号の設定（省略時はデフォルト）
    - variableLabels: 変数名の表示ラベル辞書
    - constAtBottom: 定数項を最下部に表示するか

Returns
-------
JSONResponse
    整形済み出力テキストを含む成功レスポンス
 * @summary Output Result
 */
const outputResult = (
    outputResultRequest: OutputResultRequest,
 options?: SecondParameter<typeof customInstance<SuccessResponseOutputResultResult>>,) => {
      return customInstance<SuccessResponseOutputResultResult>(
      {url: `/api/analysis/output-result`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: outputResultRequest
    },
      options);
    }
  
/**
 * 拡張子に基づいてファイルをインポートしてテーブルを作成するエンドポイント

対応拡張子:
- ``.csv`` / ``.tsv`` → CSV インポーター（separator / encoding が有効）
- ``.xlsx`` / ``.xls`` → Excel インポーター（sheet_name が有効）
- ``.parquet``         → Parquet インポーター

インポート成功後、ファイルの親ディレクトリを
``last_opened_path`` としてメモリ上の設定に反映する。
ファイルへの保存はアプリ終了時に一括して行われる。

Parameters
----------
request : Request
    FastAPI のリクエストオブジェクト
body : ImportFileRequestBody
    リクエストボディ
tables_store : TablesStoreDep
    依存注入されたテーブルストア
settings_store : SettingsStoreDep
    依存注入された設定ストア

Returns
-------
JSONResponse
    処理結果
 * @summary Import File
 */
const importFile = (
    importFileRequestBody: ImportFileRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseImportFileResult>>,) => {
      return customInstance<SuccessResponseImportFileResult>(
      {url: `/api/data/import`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: importFileRequestBody
    },
      options);
    }
  
/**
 * format に基づいてテーブルをファイルにエクスポートするエンドポイント

対応形式：
- ``csv``     → CSV エクスポーター（separator / include_header が有効）
- ``excel``   → Excel エクスポーター（sheet_name / include_header が有効）
- ``parquet`` → Parquet エクスポーター

エクスポート成功後、出力先ディレクトリを
``last_opened_path`` としてメモリ上の設定に反映する。
ファイルへの保存はアプリ終了時に一括して行われる。

Parameters
----------
request : Request
    FastAPI のリクエストオブジェクト
body : ExportFileRequestBody
    リクエストボディ
tables_store : TablesStoreDep
    依存注入されたテーブルストア
settings_store : SettingsStoreDep
    依存注入された設定ストア

Returns
-------
JSONResponse
    処理結果
 * @summary Export File
 */
const exportFile = (
    exportFileRequestBody: ExportFileRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseExportFileResult>>,) => {
      return customInstance<SuccessResponseExportFileResult>(
      {url: `/api/data/export`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: exportFileRequestBody
    },
      options);
    }
  
/**
 * 信頼区間計算を行うエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : ConfidenceIntervalRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Confidence Interval
 */
const confidenceInterval = (
    confidenceIntervalRequestBody: ConfidenceIntervalRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseConfidenceIntervalResult>>,) => {
      return customInstance<SuccessResponseConfidenceIntervalResult>(
      {url: `/api/statistics/confidence-interval`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: confidenceIntervalRequestBody
    },
      options);
    }
  
/**
 * 記述統計を計算するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DescriptiveStatisticsRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Descriptive Statistics
 */
const descriptiveStatistics = (
    descriptiveStatisticsRequestBody: DescriptiveStatisticsRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseDescriptiveStatisticsResult>>,) => {
      return customInstance<SuccessResponseDescriptiveStatisticsResult>(
      {url: `/api/statistics/descriptive`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: descriptiveStatisticsRequestBody
    },
      options);
    }
  
/**
 * 相関係数テーブル作成を行うエンドポイント

指定されたテーブルの各列間の相関係数行列を計算し、
新しいテーブルとして保存します。

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateCorrelationTableRequestBody
    リクエストボディ
tables_store : TablesStoreDep
    テーブルストア依存性

Returns
-------
JSONResponse
    処理結果（新規作成されたテーブル名）
 * @summary Create Correlation Table
 */
const createCorrelationTable = (
    createCorrelationTableRequestBody: CreateCorrelationTableRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseCreateCorrelationTableResult>>,) => {
      return customInstance<SuccessResponseCreateCorrelationTableResult>(
      {url: `/api/statistics/create-correlation-table`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCorrelationTableRequestBody
    },
      options);
    }
  
/**
 * 統計的検定を実行するエンドポイント

t 検定・z 検定・F 検定（分散比検定 / ANOVA）を実行し、
検定統計量・p 値・自由度・信頼区間・効果量を返します。

Parameters
----------
request : Request
    FastAPI のリクエストオブジェクト
body : StatisticalTestRequestBody
    リクエストボディ
tables_store : TablesStoreDep
    テーブルストア依存性

Returns
-------
JSONResponse
    処理結果
 * @summary Statistical Test
 */
const statisticalTest = (
    statisticalTestRequestBody: StatisticalTestRequestBody,
 options?: SecondParameter<typeof customInstance<SuccessResponseStatisticalTestResult>>,) => {
      return customInstance<SuccessResponseStatisticalTestResult>(
      {url: `/api/statistics/test`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: statisticalTestRequestBody
    },
      options);
    }
  
/**
 * アプリケーション設定を取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト

Returns
-------
JSONResponse
    処理結果
 * @summary Get Settings
 */
const getSettings = (
    
 options?: SecondParameter<typeof customInstance<SuccessResponseGetSettingsResult>>,) => {
      return customInstance<SuccessResponseGetSettingsResult>(
      {url: `/api/settings`, method: 'GET'
    },
      options);
    }
  
/**
 * アプリケーション設定を更新するエンドポイント

指定されたフィールドのみを部分更新します。省略したフィールドは
現在の値を維持します。更新後の設定全体をレスポンスとして返します。

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : UpdateSettingsRequest
    更新するフィールドを含むリクエストボディ（すべて省略可能）
settings_store : SettingsStoreDep
    依存注入された設定ストア

Returns
-------
JSONResponse
    更新後の設定情報
 * @summary Update Settings
 */
const updateSettings = (
    updateSettingsRequest: UpdateSettingsRequest,
 options?: SecondParameter<typeof customInstance<SuccessResponseUpdateSettingsResult>>,) => {
      return customInstance<SuccessResponseUpdateSettingsResult>(
      {url: `/api/settings`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateSettingsRequest
    },
      options);
    }
  
/**
 * アプリ終了前クリーンアップエンドポイント

フロントエンドの CloseRequested ハンドラから呼び出される。
分析結果ファイルの削除と設定の保存を行う。

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
analysis_result_store : AnalysisResultStoreDep
    依存注入された分析結果ストア
settings_store : SettingsStoreDep
    依存注入された設定ストア

Returns
-------
JSONResponse
    処理結果
 * @summary Shutdown
 */
const shutdown = (
    
 options?: SecondParameter<typeof customInstance<SuccessResponseShutdownResult>>,) => {
      return customInstance<SuccessResponseShutdownResult>(
      {url: `/api/shutdown`, method: 'POST'
    },
      options);
    }
  
return {healthCheck,addDummyColumn,deleteColumn,renameColumn,addLagLeadColumn,addSimulationColumn,calculateColumn,duplicateColumn,transformColumn,getColumnList,sortColumns,castColumn,createJoinTable,createUnionTable,createSimulationDataTable,deleteTable,duplicateTable,renameTable,getTableList,clearTables,fetchDataToJson,fetchDataToArrow,inputCellData,filterSingleCondition,regression,getAllAnalysisResults,clearAllAnalysisResults,getAnalysisResult,deleteAnalysisResult,addDiagnosticColumns,outputResult,importFile,exportFile,confidenceInterval,descriptiveStatistics,createCorrelationTable,statisticalTest,getSettings,updateSettings,shutdown}};
export type HealthCheckResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['healthCheck']>>>
export type AddDummyColumnResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['addDummyColumn']>>>
export type DeleteColumnResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['deleteColumn']>>>
export type RenameColumnResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['renameColumn']>>>
export type AddLagLeadColumnResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['addLagLeadColumn']>>>
export type AddSimulationColumnResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['addSimulationColumn']>>>
export type CalculateColumnResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['calculateColumn']>>>
export type DuplicateColumnResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['duplicateColumn']>>>
export type TransformColumnResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['transformColumn']>>>
export type GetColumnListResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['getColumnList']>>>
export type SortColumnsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['sortColumns']>>>
export type CastColumnResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['castColumn']>>>
export type CreateJoinTableResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['createJoinTable']>>>
export type CreateUnionTableResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['createUnionTable']>>>
export type CreateSimulationDataTableResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['createSimulationDataTable']>>>
export type DeleteTableResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['deleteTable']>>>
export type DuplicateTableResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['duplicateTable']>>>
export type RenameTableResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['renameTable']>>>
export type GetTableListResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['getTableList']>>>
export type ClearTablesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['clearTables']>>>
export type FetchDataToJsonResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['fetchDataToJson']>>>
export type FetchDataToArrowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['fetchDataToArrow']>>>
export type InputCellDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['inputCellData']>>>
export type FilterSingleConditionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['filterSingleCondition']>>>
export type RegressionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['regression']>>>
export type GetAllAnalysisResultsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['getAllAnalysisResults']>>>
export type ClearAllAnalysisResultsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['clearAllAnalysisResults']>>>
export type GetAnalysisResultResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['getAnalysisResult']>>>
export type DeleteAnalysisResultResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['deleteAnalysisResult']>>>
export type AddDiagnosticColumnsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['addDiagnosticColumns']>>>
export type OutputResultResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['outputResult']>>>
export type ImportFileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['importFile']>>>
export type ExportFileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['exportFile']>>>
export type ConfidenceIntervalResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['confidenceInterval']>>>
export type DescriptiveStatisticsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['descriptiveStatistics']>>>
export type CreateCorrelationTableResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['createCorrelationTable']>>>
export type StatisticalTestResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['statisticalTest']>>>
export type GetSettingsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['getSettings']>>>
export type UpdateSettingsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['updateSettings']>>>
export type ShutdownResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEconomiconAppAPI>['shutdown']>>>
