/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddColumnRequest,
  AddDummyColumnRequest,
  AddLagLeadColumnRequest,
  AddSimulationColumnRequest,
  CalculateColumnRequest,
  ConfidenceIntervalRequest,
  CreateJoinTableRequest,
  CreateSimulationDataTableRequest,
  CreateTableRequest,
  CreateUnionTableRequest,
  DeleteColumnRequest,
  DeleteTableRequest,
  DescriptiveStatisticsRequest,
  DuplicateColumnRequest,
  DuplicateTableRequest,
  ExportCsvByPathRequest,
  ExportExcelByPathRequest,
  ExportParquetByPathRequest,
  FetchDataToArrowRequest,
  FetchDataToJsonRequest,
  FilterSingleConditionRequest,
  GetColumnListRequest,
  GetFilesRequest,
  ImportCsvByPathRequest,
  ImportExcelByPathRequest,
  ImportParquetByPathRequest,
  InputCellDataRequest,
  RegressionRequest,
  RenameColumnRequest,
  RenameTableRequest,
  SortColumnsRequest,
  SuccessResponseAddColumnResult,
  TransformColumnRequest
} from './model';

import { customInstance } from './mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getMyAPI = () => {
/**
 * ルートエンドポイント
 * @summary Root
 */
const root = (
    
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/`, method: 'GET'
    },
      options);
    }
  
/**
 * ヘルスチェック
 * @summary Health Check
 */
const healthCheck = (
    
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/health`, method: 'GET'
    },
      options);
    }
  
/**
 * カラムを追加するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : AddColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Add Column Endpoint
 */
const addColumnEndpoint = (
    addColumnRequest: AddColumnRequest,
 options?: SecondParameter<typeof customInstance<SuccessResponseAddColumnResult>>,) => {
      return customInstance<SuccessResponseAddColumnResult>(
      {url: `/api/column/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addColumnRequest
    },
      options);
    }
  
/**
 * ダミー変数カラムを追加するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : AddDummyColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Add Dummy Column Endpoint
 */
const addDummyColumnEndpoint = (
    addDummyColumnRequest: AddDummyColumnRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/column/add-dummy`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addDummyColumnRequest
    },
      options);
    }
  
/**
 * カラムを削除するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DeleteColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Delete Column Endpoint
 */
const deleteColumnEndpoint = (
    deleteColumnRequest: DeleteColumnRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/column/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteColumnRequest
    },
      options);
    }
  
/**
 * 列名変更エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : RenameColumnNameRequest
    リクエストボディ
    - tableName: テーブル名
    - oldColumnName: 旧列名
    - newColumnName: 新列名

Returns
-------
JSONResponse
    処理結果
 * @summary Rename Column Endpoint
 */
const renameColumnEndpoint = (
    renameColumnRequest: RenameColumnRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/column/rename`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: renameColumnRequest
    },
      options);
    }
  
/**
 * ラグ・リードカラムを追加するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : AddLagLeadColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Add Lag Lead Column Endpoint
 */
const addLagLeadColumnEndpoint = (
    addLagLeadColumnRequest: AddLagLeadColumnRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/column/add-lag-lead`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addLagLeadColumnRequest
    },
      options);
    }
  
/**
 * シミュレーションカラムを追加するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : AddSimulationColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Add Simulation Column Endpoint
 */
const addSimulationColumnEndpoint = (
    addSimulationColumnRequest: AddSimulationColumnRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/column/add-simulation`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addSimulationColumnRequest
    },
      options);
    }
  
/**
 * カラム計算を実行するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : StatisticsCalculateColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Calculate Column Endpoint
 */
const calculateColumnEndpoint = (
    calculateColumnRequest: CalculateColumnRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/column/calculate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: calculateColumnRequest
    },
      options);
    }
  
/**
 * カラムを複製するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DataDuplicateColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Duplicate Column Endpoint
 */
const duplicateColumnEndpoint = (
    duplicateColumnRequest: DuplicateColumnRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/column/duplicate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: duplicateColumnRequest
    },
      options);
    }
  
/**
 * 列の変換処理エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : TransformColumnRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Transform Column Endpoint
 */
const transformColumnEndpoint = (
    transformColumnRequest: TransformColumnRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/column/transform`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: transformColumnRequest
    },
      options);
    }
  
/**
 * カラムリストを取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : GetColumnListRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Get Column List Endpoint
 */
const getColumnListEndpoint = (
    getColumnListRequest: GetColumnListRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/column/get-list`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getColumnListRequest
    },
      options);
    }
  
/**
 * 列のソート処理エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : SortColumnsRequest
    リクエストボディ
    - tableName: テーブル名
    - sortColumns: ソート列情報

Returns
-------
JSONResponse
    処理結果
 * @summary Sort Columns Endpoint
 */
const sortColumnsEndpoint = (
    sortColumnsRequest: SortColumnsRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/column/sort`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sortColumnsRequest
    },
      options);
    }
  
/**
 * テーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Table Endpoint
 */
const createTableEndpoint = (
    createTableRequest: CreateTableRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/table/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTableRequest
    },
      options);
    }
  
/**
 * 結合テーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateJoinTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Join Table Endpoint
 */
const createJoinTableEndpoint = (
    createJoinTableRequest: CreateJoinTableRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/table/create-join`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createJoinTableRequest
    },
      options);
    }
  
/**
 * ユニオンテーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateUnionTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Union Table Endpoint
 */
const createUnionTableEndpoint = (
    createUnionTableRequest: CreateUnionTableRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/table/create-union`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUnionTableRequest
    },
      options);
    }
  
/**
 * シミュレーションデータテーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateSimulationDataTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Simulation Data Table Endpoint
 */
const createSimulationDataTableEndpoint = (
    createSimulationDataTableRequest: CreateSimulationDataTableRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/table/create-simulation-data`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSimulationDataTableRequest
    },
      options);
    }
  
/**
 * テーブルを削除するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DeleteTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Delete Table Endpoint
 */
const deleteTableEndpoint = (
    deleteTableRequest: DeleteTableRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/table/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteTableRequest
    },
      options);
    }
  
/**
 * テーブルを複製するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DuplicateTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Duplicate Table Endpoint
 */
const duplicateTableEndpoint = (
    duplicateTableRequest: DuplicateTableRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/table/duplicate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: duplicateTableRequest
    },
      options);
    }
  
/**
 * テーブル名変更エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : RenameTableRequest
    リクエストボディ
    - oldTableName: 旧テーブル名
    - newTableName: 新テーブル名

Returns
-------
JSONResponse
    処理結果
 * @summary Rename Table Endpoint
 */
const renameTableEndpoint = (
    renameTableRequest: RenameTableRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/table/rename`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: renameTableRequest
    },
      options);
    }
  
/**
 * テーブルリストを取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト

Returns
-------
JSONResponse
    処理結果
 * @summary Get Table List Endpoint
 */
const getTableListEndpoint = (
    
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/table/get-list`, method: 'GET'
    },
      options);
    }
  
/**
 * 全テーブルをクリアするエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト

Returns
-------
JSONResponse
    処理結果
 * @summary Clear Tables Endpoint
 */
const clearTablesEndpoint = (
    
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/table/clear-all`, method: 'DELETE'
    },
      options);
    }
  
/**
 * データをJSON形式で取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : FetchDataToJsonRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Fetch Data To Json Endpoint
 */
const fetchDataToJsonEndpoint = (
    fetchDataToJsonRequest: FetchDataToJsonRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/table/fetch-data-to-json`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: fetchDataToJsonRequest
    },
      options);
    }
  
/**
 * データをApache Arrow IPC形式で取得するエンドポイント

仮想スクロール用のチャンク取得API。
Apache Arrow IPC形式のバイナリデータ（Base64エンコード）を返します。

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : FetchDataToArrowRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果（Arrow IPC形式のBase64エンコードされたバイナリを含む）
 * @summary Fetch Data To Arrow Endpoint
 */
const fetchDataToArrowEndpoint = (
    fetchDataToArrowRequest: FetchDataToArrowRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/table/fetch-data-to-arrow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: fetchDataToArrowRequest
    },
      options);
    }
  
/**
 * セルデータ入力エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : InputCellDataRequest
    リクエストボディ
    - tableName: テーブル名
    - columnName: 列名
    - rowIndex: 行インデックス
    - newValue: 新しい値

Returns
-------
JSONResponse
    処理結果
 * @summary Input Cell Data Endpoint
 */
const inputCellDataEndpoint = (
    inputCellDataRequest: InputCellDataRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/table/input-cell-data`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: inputCellDataRequest
    },
      options);
    }
  
/**
 * 単一条件フィルタリングを実行するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : FilterSingleConditionRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Filter Single Condition Endpoint
 */
const filterSingleConditionEndpoint = (
    filterSingleConditionRequest: FilterSingleConditionRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/table/filter-single-condition`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filterSingleConditionRequest
    },
      options);
    }
  
/**
 * 統合回帰分析エンドポイント

typeフィールドに応じて適切な分析手法を選択し、実行します。

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : RegressionRequest
    統合回帰分析リクエスト
    - type: 分析タイプ (ols, logit, probit, tobit, fe, re, iv,
      feiv, lasso, ridge)
    - tableName: 対象テーブル名
    - dependentVariable: 被説明変数
    - explanatoryVariables: 説明変数のリスト
    - その他分析固有のパラメータ

Returns
-------
JSONResponse
    分析結果またはエラーメッセージ
 * @summary Regression Endpoint
 */
const regressionEndpoint = (
    regressionRequest: RegressionRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/analysis/regression`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: regressionRequest
    },
      options);
    }
  
/**
 * すべての分析結果のサマリーを取得

Returns
-------
JSONResponse
    分析結果のサマリーリスト
 * @summary Get All Analysis Results Endpoint
 */
const getAllAnalysisResultsEndpoint = (
    
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/analysis/results`, method: 'GET'
    },
      options);
    }
  
/**
 * すべての分析結果を削除

Returns
-------
JSONResponse
    削除成功メッセージ
 * @summary Clear All Analysis Results Endpoint
 */
const clearAllAnalysisResultsEndpoint = (
    
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/analysis/results`, method: 'DELETE'
    },
      options);
    }
  
/**
 * 指定されたIDの分析結果を取得

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
result_id : str
    結果のID

Returns
-------
JSONResponse
    分析結果の詳細
 * @summary Get Analysis Result Endpoint
 */
const getAnalysisResultEndpoint = (
    resultId: string,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/analysis/results/${resultId}`, method: 'GET'
    },
      options);
    }
  
/**
 * 指定されたIDの分析結果を削除

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
result_id : str
    削除する結果のID

Returns
-------
JSONResponse
    削除成功メッセージ
 * @summary Delete Analysis Result Endpoint
 */
const deleteAnalysisResultEndpoint = (
    resultId: string,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/analysis/results/${resultId}`, method: 'DELETE'
    },
      options);
    }
  
/**
 * パス指定でCSVファイルをインポートするエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : ImportCsvByPathRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Import Csv By Path Endpoint
 */
const importCsvByPathEndpoint = (
    importCsvByPathRequest: ImportCsvByPathRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/data/import-csv-by-path`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: importCsvByPathRequest
    },
      options);
    }
  
/**
 * EXCELファイルをパス指定でインポートしてテーブルを作成する

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : ImportExcelByPathRequest
    リクエストボディ
    - filePath: EXCELファイルのパス
    - tableName: 作成するテーブル名
    - sheetName: シート名（オプション）

Returns
-------
JSONResponse
    処理結果
 * @summary Import Excel By Path Endpoint
 */
const importExcelByPathEndpoint = (
    importExcelByPathRequest: ImportExcelByPathRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/data/import-excel-by-path`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: importExcelByPathRequest
    },
      options);
    }
  
/**
 * PARQUETファイルをパス指定でインポートしてテーブルを作成する

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : ImportParquetByPathRequest
    リクエストボディ
    - filePath: PARQUETファイルのパス
    - tableName: 作成するテーブル名

Returns
-------
JSONResponse
    処理結果
 * @summary Import Parquet By Path Endpoint
 */
const importParquetByPathEndpoint = (
    importParquetByPathRequest: ImportParquetByPathRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/data/import-parquet-by-path`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: importParquetByPathRequest
    },
      options);
    }
  
/**
 * テーブルをCSVファイルにパス指定でエクスポートするエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : ExportCsvByPathRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Export Csv By Path Endpoint
 */
const exportCsvByPathEndpoint = (
    exportCsvByPathRequest: ExportCsvByPathRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/data/export-csv-by-path`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: exportCsvByPathRequest
    },
      options);
    }
  
/**
 * テーブルをExcelファイルにパス指定でエクスポートするエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : ExportExcelByPathRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Export Excel By Path Endpoint
 */
const exportExcelByPathEndpoint = (
    exportExcelByPathRequest: ExportExcelByPathRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/data/export-excel-by-path`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: exportExcelByPathRequest
    },
      options);
    }
  
/**
 * テーブルをParquetファイルにパス指定でエクスポートするエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : ExportParquetByPathRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Export Parquet By Path Endpoint
 */
const exportParquetByPathEndpoint = (
    exportParquetByPathRequest: ExportParquetByPathRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/data/export-parquet-by-path`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: exportParquetByPathRequest
    },
      options);
    }
  
/**
 * 信頼区間計算を行うエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : ConfidenceIntervalRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Confidence Interval Endpoint
 */
const confidenceIntervalEndpoint = (
    confidenceIntervalRequest: ConfidenceIntervalRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/statistics/confidence-interval`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: confidenceIntervalRequest
    },
      options);
    }
  
/**
 * 記述統計を計算するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DescriptiveStatisticsRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Descriptive Statistics Endpoint
 */
const descriptiveStatisticsEndpoint = (
    descriptiveStatisticsRequest: DescriptiveStatisticsRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/statistics/descriptive`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: descriptiveStatisticsRequest
    },
      options);
    }
  
/**
 * ファイル一覧を取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : GetFilesRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Get Files Endpoint
 */
const getFilesEndpoint = (
    getFilesRequest: GetFilesRequest,
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/file/get-list`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getFilesRequest
    },
      options);
    }
  
/**
 * アプリケーション設定を取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト

Returns
-------
JSONResponse
    処理結果
 * @summary Get Settings Endpoint
 */
const getSettingsEndpoint = (
    
 options?: SecondParameter<typeof customInstance<unknown>>,) => {
      return customInstance<unknown>(
      {url: `/api/setting/get-settings`, method: 'GET'
    },
      options);
    }
  
return {root,healthCheck,addColumnEndpoint,addDummyColumnEndpoint,deleteColumnEndpoint,renameColumnEndpoint,addLagLeadColumnEndpoint,addSimulationColumnEndpoint,calculateColumnEndpoint,duplicateColumnEndpoint,transformColumnEndpoint,getColumnListEndpoint,sortColumnsEndpoint,createTableEndpoint,createJoinTableEndpoint,createUnionTableEndpoint,createSimulationDataTableEndpoint,deleteTableEndpoint,duplicateTableEndpoint,renameTableEndpoint,getTableListEndpoint,clearTablesEndpoint,fetchDataToJsonEndpoint,fetchDataToArrowEndpoint,inputCellDataEndpoint,filterSingleConditionEndpoint,regressionEndpoint,getAllAnalysisResultsEndpoint,clearAllAnalysisResultsEndpoint,getAnalysisResultEndpoint,deleteAnalysisResultEndpoint,importCsvByPathEndpoint,importExcelByPathEndpoint,importParquetByPathEndpoint,exportCsvByPathEndpoint,exportExcelByPathEndpoint,exportParquetByPathEndpoint,confidenceIntervalEndpoint,descriptiveStatisticsEndpoint,getFilesEndpoint,getSettingsEndpoint}};
export type RootResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['root']>>>
export type HealthCheckResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['healthCheck']>>>
export type AddColumnEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['addColumnEndpoint']>>>
export type AddDummyColumnEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['addDummyColumnEndpoint']>>>
export type DeleteColumnEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['deleteColumnEndpoint']>>>
export type RenameColumnEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['renameColumnEndpoint']>>>
export type AddLagLeadColumnEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['addLagLeadColumnEndpoint']>>>
export type AddSimulationColumnEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['addSimulationColumnEndpoint']>>>
export type CalculateColumnEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['calculateColumnEndpoint']>>>
export type DuplicateColumnEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['duplicateColumnEndpoint']>>>
export type TransformColumnEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['transformColumnEndpoint']>>>
export type GetColumnListEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['getColumnListEndpoint']>>>
export type SortColumnsEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['sortColumnsEndpoint']>>>
export type CreateTableEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['createTableEndpoint']>>>
export type CreateJoinTableEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['createJoinTableEndpoint']>>>
export type CreateUnionTableEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['createUnionTableEndpoint']>>>
export type CreateSimulationDataTableEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['createSimulationDataTableEndpoint']>>>
export type DeleteTableEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['deleteTableEndpoint']>>>
export type DuplicateTableEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['duplicateTableEndpoint']>>>
export type RenameTableEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['renameTableEndpoint']>>>
export type GetTableListEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['getTableListEndpoint']>>>
export type ClearTablesEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['clearTablesEndpoint']>>>
export type FetchDataToJsonEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['fetchDataToJsonEndpoint']>>>
export type FetchDataToArrowEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['fetchDataToArrowEndpoint']>>>
export type InputCellDataEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['inputCellDataEndpoint']>>>
export type FilterSingleConditionEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['filterSingleConditionEndpoint']>>>
export type RegressionEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['regressionEndpoint']>>>
export type GetAllAnalysisResultsEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['getAllAnalysisResultsEndpoint']>>>
export type ClearAllAnalysisResultsEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['clearAllAnalysisResultsEndpoint']>>>
export type GetAnalysisResultEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['getAnalysisResultEndpoint']>>>
export type DeleteAnalysisResultEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['deleteAnalysisResultEndpoint']>>>
export type ImportCsvByPathEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['importCsvByPathEndpoint']>>>
export type ImportExcelByPathEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['importExcelByPathEndpoint']>>>
export type ImportParquetByPathEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['importParquetByPathEndpoint']>>>
export type ExportCsvByPathEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['exportCsvByPathEndpoint']>>>
export type ExportExcelByPathEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['exportExcelByPathEndpoint']>>>
export type ExportParquetByPathEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['exportParquetByPathEndpoint']>>>
export type ConfidenceIntervalEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['confidenceIntervalEndpoint']>>>
export type DescriptiveStatisticsEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['descriptiveStatisticsEndpoint']>>>
export type GetFilesEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['getFilesEndpoint']>>>
export type GetSettingsEndpointResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMyAPI>['getSettingsEndpoint']>>>
