/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * テーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Table Endpoint
 */
export const createTableEndpointApiTableCreatePostBodyTableNameMax = 255;





export const CreateTableEndpointApiTableCreatePostBody = zod.object({
  "tableName": zod.string().min(1).max(createTableEndpointApiTableCreatePostBodyTableNameMax).describe('テーブル名'),
  "tableNumberOfRows": zod.number().min(1).describe('テーブルの行数'),
  "columnNames": zod.array(zod.string()).min(1).describe('カラム名のリスト')
}).describe('テーブル作成リクエスト')

export const CreateTableEndpointApiTableCreatePostResponse = zod.unknown()

/**
 * 結合テーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateJoinTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Join Table Endpoint
 */
export const createJoinTableEndpointApiTableCreateJoinPostBodyJoinTableNameMax = 255;

export const createJoinTableEndpointApiTableCreateJoinPostBodyLeftTableNameMax = 255;

export const createJoinTableEndpointApiTableCreateJoinPostBodyRightTableNameMax = 255;



export const createJoinTableEndpointApiTableCreateJoinPostBodyJoinTypeMax = 50;



export const CreateJoinTableEndpointApiTableCreateJoinPostBody = zod.object({
  "joinTableName": zod.string().min(1).max(createJoinTableEndpointApiTableCreateJoinPostBodyJoinTableNameMax).describe('結合後のテーブル名'),
  "leftTableName": zod.string().min(1).max(createJoinTableEndpointApiTableCreateJoinPostBodyLeftTableNameMax).describe('左側のテーブル名'),
  "rightTableName": zod.string().min(1).max(createJoinTableEndpointApiTableCreateJoinPostBodyRightTableNameMax).describe('右側のテーブル名'),
  "leftKeyColumnNames": zod.array(zod.string()).min(1).describe('左側の結合キーカラム名のリスト'),
  "rightKeyColumnNames": zod.array(zod.string()).min(1).describe('右側の結合キーカラム名のリスト'),
  "joinType": zod.string().min(1).max(createJoinTableEndpointApiTableCreateJoinPostBodyJoinTypeMax).describe('結合タイプ (inner, left, right, outer)')
}).describe('結合テーブル作成リクエスト')

export const CreateJoinTableEndpointApiTableCreateJoinPostResponse = zod.unknown()

/**
 * ユニオンテーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateUnionTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Union Table Endpoint
 */
export const createUnionTableEndpointApiTableCreateUnionPostBodyUnionTableNameMax = 255;




export const CreateUnionTableEndpointApiTableCreateUnionPostBody = zod.object({
  "unionTableName": zod.string().min(1).max(createUnionTableEndpointApiTableCreateUnionPostBodyUnionTableNameMax).describe('ユニオン後のテーブル名'),
  "tableNames": zod.array(zod.string()).min(1).describe('結合するテーブル名のリスト'),
  "columnNames": zod.array(zod.string()).optional().describe('対象カラム名のリスト')
}).describe('ユニオンテーブル作成リクエスト')

export const CreateUnionTableEndpointApiTableCreateUnionPostResponse = zod.unknown()

/**
 * シミュレーションデータテーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateSimulationDataTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Simulation Data Table Endpoint
 */
export const createSimulationDataTableEndpointApiTableCreateSimulationDataPostBodyTableNameMax = 255;





export const CreateSimulationDataTableEndpointApiTableCreateSimulationDataPostBody = zod.object({
  "tableName": zod.string().min(1).max(createSimulationDataTableEndpointApiTableCreateSimulationDataPostBodyTableNameMax).describe('テーブル名'),
  "tableNumberOfRows": zod.number().min(1).describe('テーブルの行数'),
  "columnSettings": zod.array(zod.record(zod.string(), zod.unknown())).min(1).describe('カラム設定のリスト')
}).describe('シミュレーションデータテーブル作成リクエスト')

export const CreateSimulationDataTableEndpointApiTableCreateSimulationDataPostResponse = zod.unknown()

/**
 * テーブルを削除するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DeleteTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Delete Table Endpoint
 */
export const deleteTableEndpointApiTableDeletePostBodyTableNameMax = 255;



export const DeleteTableEndpointApiTableDeletePostBody = zod.object({
  "tableName": zod.string().min(1).max(deleteTableEndpointApiTableDeletePostBodyTableNameMax).describe('テーブル名')
}).describe('テーブル削除リクエスト')

export const DeleteTableEndpointApiTableDeletePostResponse = zod.unknown()

/**
 * テーブルを複製するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DuplicateTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Duplicate Table Endpoint
 */
export const duplicateTableEndpointApiTableDuplicatePostBodyTableNameMax = 255;

export const duplicateTableEndpointApiTableDuplicatePostBodyNewTableNameMax = 255;



export const DuplicateTableEndpointApiTableDuplicatePostBody = zod.object({
  "tableName": zod.string().min(1).max(duplicateTableEndpointApiTableDuplicatePostBodyTableNameMax).describe('元のテーブル名'),
  "newTableName": zod.string().min(1).max(duplicateTableEndpointApiTableDuplicatePostBodyNewTableNameMax).describe('新しいテーブル名')
}).describe('テーブル複製リクエスト')

export const DuplicateTableEndpointApiTableDuplicatePostResponse = zod.unknown()

/**
 * テーブル名変更エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : RenameTableRequest
    リクエストボディ
    - oldTableName: 旧テーブル名
    - newTableName: 新テーブル名

Returns
-------
JSONResponse
    処理結果
 * @summary Rename Table Endpoint
 */
export const renameTableEndpointApiTableRenamePostBodyOldTableNameMax = 255;

export const renameTableEndpointApiTableRenamePostBodyNewTableNameMax = 255;



export const RenameTableEndpointApiTableRenamePostBody = zod.object({
  "oldTableName": zod.string().min(1).max(renameTableEndpointApiTableRenamePostBodyOldTableNameMax).describe('元のテーブル名'),
  "newTableName": zod.string().min(1).max(renameTableEndpointApiTableRenamePostBodyNewTableNameMax).describe('新しいテーブル名')
}).describe('テーブル名変更リクエスト')

export const RenameTableEndpointApiTableRenamePostResponse = zod.unknown()

/**
 * テーブルリストを取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト

Returns
-------
JSONResponse
    処理結果
 * @summary Get Table List Endpoint
 */
export const GetTableListEndpointApiTableGetListGetResponse = zod.unknown()

/**
 * 全テーブルをクリアするエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト

Returns
-------
JSONResponse
    処理結果
 * @summary Clear Tables Endpoint
 */
export const ClearTablesEndpointApiTableClearAllDeleteResponse = zod.unknown()

/**
 * データをJSON形式で取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : FetchDataToJsonRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Fetch Data To Json Endpoint
 */
export const fetchDataToJsonEndpointApiTableFetchDataToJsonPostBodyTableNameMax = 255;

export const fetchDataToJsonEndpointApiTableFetchDataToJsonPostBodyStartRowMin = 0;




export const FetchDataToJsonEndpointApiTableFetchDataToJsonPostBody = zod.object({
  "tableName": zod.string().min(1).max(fetchDataToJsonEndpointApiTableFetchDataToJsonPostBodyTableNameMax).describe('対象テーブル名'),
  "startRow": zod.number().min(fetchDataToJsonEndpointApiTableFetchDataToJsonPostBodyStartRowMin).describe('開始行番号'),
  "fetchRows": zod.number().min(1).describe('取得行数')
}).describe('データJSON取得リクエスト')

export const FetchDataToJsonEndpointApiTableFetchDataToJsonPostResponse = zod.unknown()

/**
 * データをApache Arrow IPC形式で取得するエンドポイント

仮想スクロール用のチャンク取得API。
Apache Arrow IPC形式のバイナリデータ（Base64エンコード）を返します。

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : FetchDataToArrowRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果（Arrow IPC形式のBase64エンコードされたバイナリを含む）
 * @summary Fetch Data To Arrow Endpoint
 */
export const fetchDataToArrowEndpointApiTableFetchDataToArrowPostBodyTableNameMax = 255;

export const fetchDataToArrowEndpointApiTableFetchDataToArrowPostBodyStartRowMin = 0;

export const fetchDataToArrowEndpointApiTableFetchDataToArrowPostBodyChunkSizeDefault = 500;
export const fetchDataToArrowEndpointApiTableFetchDataToArrowPostBodyChunkSizeMax = 10000;



export const FetchDataToArrowEndpointApiTableFetchDataToArrowPostBody = zod.object({
  "tableName": zod.string().min(1).max(fetchDataToArrowEndpointApiTableFetchDataToArrowPostBodyTableNameMax).describe('対象テーブル名'),
  "startRow": zod.number().min(fetchDataToArrowEndpointApiTableFetchDataToArrowPostBodyStartRowMin).describe('開始行番号'),
  "chunkSize": zod.number().min(1).max(fetchDataToArrowEndpointApiTableFetchDataToArrowPostBodyChunkSizeMax).default(fetchDataToArrowEndpointApiTableFetchDataToArrowPostBodyChunkSizeDefault).describe('チャンクサイズ（デフォルト500行）')
}).describe('データArrow取得リクエスト')

export const FetchDataToArrowEndpointApiTableFetchDataToArrowPostResponse = zod.unknown()

/**
 * セルデータ入力エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : InputCellDataRequest
    リクエストボディ
    - tableName: テーブル名
    - columnName: 列名
    - rowIndex: 行インデックス
    - newValue: 新しい値

Returns
-------
JSONResponse
    処理結果
 * @summary Input Cell Data Endpoint
 */
export const inputCellDataEndpointApiTableInputCellDataPostBodyTableNameMax = 255;

export const inputCellDataEndpointApiTableInputCellDataPostBodyColumnNameMax = 255;

export const inputCellDataEndpointApiTableInputCellDataPostBodyRowIndexMin = 0;



export const InputCellDataEndpointApiTableInputCellDataPostBody = zod.object({
  "tableName": zod.string().min(1).max(inputCellDataEndpointApiTableInputCellDataPostBodyTableNameMax).describe('テーブル名'),
  "columnName": zod.string().min(1).max(inputCellDataEndpointApiTableInputCellDataPostBodyColumnNameMax).describe('カラム名'),
  "rowIndex": zod.number().min(inputCellDataEndpointApiTableInputCellDataPostBodyRowIndexMin).describe('行インデックス'),
  "newValue": zod.unknown().describe('新しい入力値')
}).describe('セルデータ入力リクエスト')

export const InputCellDataEndpointApiTableInputCellDataPostResponse = zod.unknown()

/**
 * 単一条件フィルタリングを実行するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : FilterSingleConditionRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Filter Single Condition Endpoint
 */
export const filterSingleConditionEndpointApiTableFilterSingleConditionPostBodyTableNameMax = 255;

export const filterSingleConditionEndpointApiTableFilterSingleConditionPostBodyNewTableNameMax = 255;

export const filterSingleConditionEndpointApiTableFilterSingleConditionPostBodyColumnNameMax = 255;

export const filterSingleConditionEndpointApiTableFilterSingleConditionPostBodyConditionMax = 50;

export const filterSingleConditionEndpointApiTableFilterSingleConditionPostBodyIsCompareColumnMax = 10;



export const FilterSingleConditionEndpointApiTableFilterSingleConditionPostBody = zod.object({
  "tableName": zod.string().min(1).max(filterSingleConditionEndpointApiTableFilterSingleConditionPostBodyTableNameMax).describe('テーブル名'),
  "newTableName": zod.string().min(1).max(filterSingleConditionEndpointApiTableFilterSingleConditionPostBodyNewTableNameMax).describe('新しいテーブル名'),
  "columnName": zod.string().min(1).max(filterSingleConditionEndpointApiTableFilterSingleConditionPostBodyColumnNameMax).describe('対象カラム名'),
  "condition": zod.string().min(1).max(filterSingleConditionEndpointApiTableFilterSingleConditionPostBodyConditionMax).describe('条件'),
  "isCompareColumn": zod.string().min(1).max(filterSingleConditionEndpointApiTableFilterSingleConditionPostBodyIsCompareColumnMax).describe('比較対象がカラムかどうか'),
  "compareValue": zod.unknown().describe('比較値')
}).describe('単一条件フィルタリクエスト')

export const FilterSingleConditionEndpointApiTableFilterSingleConditionPostResponse = zod.unknown()

