/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Economicon API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * テーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateTableRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Table
 */
export const createTableBodyTableNameMax = 128;


export const createTableBodyTableNameRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');

export const createTableBodyColumnNamesItemMax = 128;


export const createTableBodyColumnNamesItemRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');

export const createTableBodyFilePathOneMax = 1024;

export const createTableBodyCsvHasHeaderDefault = true;export const createTableBodyCsvSeparatorDefault = `,`;
export const createTableBodyCsvSeparatorMax = 10;

export const createTableBodyCsvEncodingDefault = `utf8`;export const createTableBodyExcelSheetNameOneMax = 31;


export const createTableBodyExcelSheetNameOneRegExp = new RegExp('^[^\\\/\\\\\\?\\\*\\:\\[\\]]+$');


export const CreateTableBody = zod.object({
  "tableName": zod.string().min(1).max(createTableBodyTableNameMax).regex(createTableBodyTableNameRegExp).describe('作成するテーブルの名前。ワークスペース内に存在しない名前を指定してください。'),
  "rowCount": zod.union([zod.number().min(1),zod.null()]).optional().describe('テーブルの行数。file_path が指定されている場合は省略可能（None の場合はファイルの行数を使用）。file_path が省略されている場合は必須（1以上の整数）。'),
  "columnNames": zod.array(zod.string().min(1).max(createTableBodyColumnNamesItemMax).regex(createTableBodyColumnNamesItemRegExp).describe('新しいカラム名')).min(1).describe('テーブルに作成するカラム名のリスト'),
  "filePath": zod.union([zod.string().min(1).max(createTableBodyFilePathOneMax).describe('ファイルのパス'),zod.null()]).optional().describe('読み込むファイルのパス（CSV \/ Excel \/ Parquet）。省略時はすべての値が None の空テーブルを作成します。'),
  "csvHasHeader": zod.boolean().default(createTableBodyCsvHasHeaderDefault).describe('CSV ファイルにヘッダ行があるか。True: 1 行目をヘッダとして読み飛ばし、2 行目からをデータとする。False: 1 行目からデータとして読み込む。file_path が CSV の場合のみ有効。'),
  "csvSeparator": zod.string().min(1).max(createTableBodyCsvSeparatorMax).default(createTableBodyCsvSeparatorDefault).describe('CSV の区切り文字。file_path が CSV の場合のみ有効。'),
  "csvEncoding": zod.enum(['utf8', 'latin1', 'ascii', 'gbk', 'windows-1252', 'shift_jis']).default(createTableBodyCsvEncodingDefault).describe('CSV のエンコーディング。file_path が CSV の場合のみ有効。'),
  "excelSheetName": zod.union([zod.string().min(1).max(createTableBodyExcelSheetNameOneMax).regex(createTableBodyExcelSheetNameOneRegExp).describe('Excelのシート名（31文字以内、使用不可記号あり）'),zod.null()]).optional().describe('読み込むシート名。file_path が Excel の場合のみ有効。省略時は先頭シートを読み込みます。')
}).describe('テーブル作成リクエスト')

export const createTableResponseCodeDefault = `OK`;

export const CreateTableResponse = zod.object({
  "code": zod.string().default(createTableResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('操作対象または生成されたテーブル名')
}).describe('テーブル作成レスポンス')
})

/**
 * 結合テーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateJoinTableRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Join Table
 */
export const createJoinTableBodyJoinTableNameMax = 128;


export const createJoinTableBodyJoinTableNameRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');








export const CreateJoinTableBody = zod.object({
  "joinTableName": zod.string().min(1).max(createJoinTableBodyJoinTableNameMax).regex(createJoinTableBodyJoinTableNameRegExp).describe('結合後に作成される新しいテーブル名。ワークスペース内に存在しない名前を指定してください。'),
  "leftTableName": zod.string().min(1).describe('結合の左側テーブル名。ワークスペース内に存在するテーブル名を指定してください。'),
  "rightTableName": zod.string().min(1).describe('結合の右側テーブル名。ワークスペース内に存在するテーブル名を指定してください。'),
  "leftKeyColumnNames": zod.array(zod.string().min(1).describe('カラム名')).min(1).describe('左側テーブルの結合キーカラム名のリスト'),
  "rightKeyColumnNames": zod.array(zod.string().min(1).describe('カラム名')).min(1).describe('右側テーブルの結合キーカラム名のリスト'),
  "joinType": zod.enum(['inner', 'left', 'right', 'full']).optional()
}).describe('結合テーブル作成リクエスト')

export const createJoinTableResponseCodeDefault = `OK`;

export const CreateJoinTableResponse = zod.object({
  "code": zod.string().default(createJoinTableResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('操作対象または生成されたテーブル名')
}).describe('結合テーブル作成レスポンス')
})

/**
 * ユニオンテーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateUnionTableRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Union Table
 */
export const createUnionTableBodyUnionTableNameMax = 128;


export const createUnionTableBodyUnionTableNameRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');

export const createUnionTableBodyTableNamesMin = 2;





export const CreateUnionTableBody = zod.object({
  "unionTableName": zod.string().min(1).max(createUnionTableBodyUnionTableNameMax).regex(createUnionTableBodyUnionTableNameRegExp).describe('ユニオン後に作成される新しいテーブル名'),
  "tableNames": zod.array(zod.string().min(1).describe('テーブル名')).min(createUnionTableBodyTableNamesMin).describe('ユニオンするテーブル名のリスト（2テーブル以上）。ワークスペース内に存在するテーブル名を指定してください。'),
  "columnNames": zod.array(zod.string().min(1).describe('カラム名')).min(1).describe('ユニオンの対象とするカラム名のリスト。指定されたテーブルすべてに存在するカラム名を指定してください。')
}).describe('ユニオンテーブル作成リクエスト')

export const createUnionTableResponseCodeDefault = `OK`;

export const CreateUnionTableResponse = zod.object({
  "code": zod.string().default(createUnionTableResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('操作対象または生成されたテーブル名')
}).describe('ユニオンテーブル作成レスポンス')
})

/**
 * シミュレーションデータテーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateSimulationDataTableRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Simulation Data Table
 */
export const createSimulationDataTableBodyTableNameMax = 128;


export const createSimulationDataTableBodyTableNameRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');

export const createSimulationDataTableBodySimulationColumnsItemColumnNameMax = 128;


export const createSimulationDataTableBodySimulationColumnsItemColumnNameRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');
export const createSimulationDataTableBodySimulationColumnsItemDistributionOneTwoScaleExclusiveMin = 0;

export const createSimulationDataTableBodySimulationColumnsItemDistributionOneThreeScaleExclusiveMin = 0;

export const createSimulationDataTableBodySimulationColumnsItemDistributionOneFourShapeExclusiveMin = 0;

export const createSimulationDataTableBodySimulationColumnsItemDistributionOneFourScaleExclusiveMin = 0;

export const createSimulationDataTableBodySimulationColumnsItemDistributionOneFiveAExclusiveMin = 0;

export const createSimulationDataTableBodySimulationColumnsItemDistributionOneFiveBExclusiveMin = 0;

export const createSimulationDataTableBodySimulationColumnsItemDistributionOneSixAExclusiveMin = 0;

export const createSimulationDataTableBodySimulationColumnsItemDistributionOneSixScaleExclusiveMin = 0;

export const createSimulationDataTableBodySimulationColumnsItemDistributionOneSevenSigmaExclusiveMin = 0;

export const createSimulationDataTableBodySimulationColumnsItemDistributionOneEightNExclusiveMin = 0;

export const createSimulationDataTableBodySimulationColumnsItemDistributionOneEightPExclusiveMin = 0;
export const createSimulationDataTableBodySimulationColumnsItemDistributionOneEightPMax = 1;

export const createSimulationDataTableBodySimulationColumnsItemDistributionOneNinePExclusiveMin = 0;
export const createSimulationDataTableBodySimulationColumnsItemDistributionOneNinePMax = 1;

export const createSimulationDataTableBodySimulationColumnsItemDistributionOneOnezeroLamExclusiveMin = 0;

export const createSimulationDataTableBodySimulationColumnsItemDistributionOneOneonePExclusiveMin = 0;
export const createSimulationDataTableBodySimulationColumnsItemDistributionOneOneonePMax = 1;

export const createSimulationDataTableBodySimulationColumnsItemDistributionOneOnetwoNExclusiveMin = 0;

export const createSimulationDataTableBodySimulationColumnsItemDistributionOneOnetwoKExclusiveMin = 0;

export const createSimulationDataTableBodySimulationColumnsItemDistributionOneOnetwoNExclusiveMinOne = 0;




export const CreateSimulationDataTableBody = zod.object({
  "tableName": zod.string().min(1).max(createSimulationDataTableBodyTableNameMax).regex(createSimulationDataTableBodyTableNameRegExp).describe('作成するシミュレーションデータテーブルの名前。ワークスペース内に存在しない名前を指定してください。'),
  "rowCount": zod.number().min(1).describe('生成するテーブルの行数'),
  "simulationColumns": zod.array(zod.object({
  "columnName": zod.string().min(1).max(createSimulationDataTableBodySimulationColumnsItemColumnNameMax).regex(createSimulationDataTableBodySimulationColumnsItemColumnNameRegExp).describe('新しいカラム名'),
  "distribution": zod.union([zod.object({
  "type": zod.literal("uniform").describe('分布の種類'),
  "low": zod.number().describe('分布の下限'),
  "high": zod.number().describe('分布の上限')
}).describe('一様分布のパラメータ'),zod.object({
  "type": zod.literal("exponential").describe('分布の種類'),
  "scale": zod.number().gt(createSimulationDataTableBodySimulationColumnsItemDistributionOneTwoScaleExclusiveMin).describe('尺度パラメータ')
}).describe('指数分布のパラメータ'),zod.object({
  "type": zod.literal("normal").describe('分布の種類'),
  "loc": zod.number().describe('平均'),
  "scale": zod.number().gt(createSimulationDataTableBodySimulationColumnsItemDistributionOneThreeScaleExclusiveMin).describe('標準偏差')
}).describe('正規分布のパラメータ'),zod.object({
  "type": zod.literal("gamma").describe('分布の種類'),
  "shape": zod.number().gt(createSimulationDataTableBodySimulationColumnsItemDistributionOneFourShapeExclusiveMin).describe('形状パラメータ'),
  "scale": zod.number().gt(createSimulationDataTableBodySimulationColumnsItemDistributionOneFourScaleExclusiveMin).describe('尺度パラメータ')
}).describe('ガンマ分布のパラメータ'),zod.object({
  "type": zod.literal("beta").describe('分布の種類'),
  "a": zod.number().gt(createSimulationDataTableBodySimulationColumnsItemDistributionOneFiveAExclusiveMin).describe('形状パラメータa'),
  "b": zod.number().gt(createSimulationDataTableBodySimulationColumnsItemDistributionOneFiveBExclusiveMin).describe('形状パラメータb')
}).describe('ベータ分布のパラメータ'),zod.object({
  "type": zod.literal("weibull").describe('分布の種類'),
  "a": zod.number().gt(createSimulationDataTableBodySimulationColumnsItemDistributionOneSixAExclusiveMin).describe('形状パラメータ'),
  "scale": zod.number().gt(createSimulationDataTableBodySimulationColumnsItemDistributionOneSixScaleExclusiveMin).describe('尺度パラメータ')
}).describe('ワイブル分布のパラメータ'),zod.object({
  "type": zod.literal("lognormal").describe('分布の種類'),
  "mean": zod.number().describe('平均'),
  "sigma": zod.number().gt(createSimulationDataTableBodySimulationColumnsItemDistributionOneSevenSigmaExclusiveMin).describe('標準偏差')
}).describe('対数正規分布のパラメータ'),zod.object({
  "type": zod.literal("binomial").describe('分布の種類'),
  "n": zod.number().gt(createSimulationDataTableBodySimulationColumnsItemDistributionOneEightNExclusiveMin).describe('試行回数'),
  "p": zod.number().gt(createSimulationDataTableBodySimulationColumnsItemDistributionOneEightPExclusiveMin).max(createSimulationDataTableBodySimulationColumnsItemDistributionOneEightPMax).describe('成功確率')
}).describe('二項分布のパラメータ'),zod.object({
  "type": zod.literal("bernoulli").describe('分布の種類'),
  "p": zod.number().gt(createSimulationDataTableBodySimulationColumnsItemDistributionOneNinePExclusiveMin).max(createSimulationDataTableBodySimulationColumnsItemDistributionOneNinePMax).describe('成功確率')
}).describe('ベルヌーイ分布のパラメータ'),zod.object({
  "type": zod.literal("poisson").describe('分布の種類'),
  "lam": zod.number().gt(createSimulationDataTableBodySimulationColumnsItemDistributionOneOnezeroLamExclusiveMin).describe('発生率')
}).describe('ポアソン分布のパラメータ'),zod.object({
  "type": zod.literal("geometric").describe('分布の種類'),
  "p": zod.number().gt(createSimulationDataTableBodySimulationColumnsItemDistributionOneOneonePExclusiveMin).max(createSimulationDataTableBodySimulationColumnsItemDistributionOneOneonePMax).describe('成功確率')
}).describe('幾何分布のパラメータ'),zod.object({
  "type": zod.literal("hypergeometric").describe('分布の種類'),
  "N": zod.number().gt(createSimulationDataTableBodySimulationColumnsItemDistributionOneOnetwoNExclusiveMin).describe('母集団サイズ'),
  "K": zod.number().gt(createSimulationDataTableBodySimulationColumnsItemDistributionOneOnetwoKExclusiveMin).describe('成功要素数'),
  "n": zod.number().gt(createSimulationDataTableBodySimulationColumnsItemDistributionOneOnetwoNExclusiveMinOne).describe('標本サイズ')
}).describe('超幾何分布のパラメータ'),zod.object({
  "type": zod.literal("fixed").describe('分布の種類'),
  "value": zod.number().describe('固定値')
}).describe('固定値のパラメータ')]).describe('分布設定')
}).describe('新しい列名とその生成規則のペア。\n複数のAPI（列追加、シミュレーション設定等）で共通利用される。')).min(1).describe('シミュレーションカラムの設定リスト')
}).describe('シミュレーションデータテーブル作成リクエスト')

export const createSimulationDataTableResponseCodeDefault = `OK`;

export const CreateSimulationDataTableResponse = zod.object({
  "code": zod.string().default(createSimulationDataTableResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('操作対象または生成されたテーブル名')
}).describe('シミュレーションデータテーブル作成レスポンス')
})

/**
 * テーブルを削除するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DeleteTableRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Delete Table
 */



export const DeleteTableBody = zod.object({
  "tableName": zod.string().min(1).describe('削除するテーブル名。ワークスペースに存在するテーブルの中から指定してください。')
}).describe('テーブル削除リクエスト')

export const deleteTableResponseCodeDefault = `OK`;

export const DeleteTableResponse = zod.object({
  "code": zod.string().default(deleteTableResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('操作対象または生成されたテーブル名')
}).describe('テーブル削除レスポンス')
})

/**
 * テーブルを複製するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DuplicateTableRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Duplicate Table
 */

export const duplicateTableBodyNewTableNameMax = 128;


export const duplicateTableBodyNewTableNameRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');


export const DuplicateTableBody = zod.object({
  "tableName": zod.string().min(1).describe('複製元のテーブル名。ワークスペースに存在するテーブルの中から指定してください。'),
  "newTableName": zod.string().min(1).max(duplicateTableBodyNewTableNameMax).regex(duplicateTableBodyNewTableNameRegExp).describe('複製後の新しいテーブル名。ワークスペースに存在しない名前を指定してください。')
}).describe('テーブル複製リクエスト')

export const duplicateTableResponseCodeDefault = `OK`;

export const DuplicateTableResponse = zod.object({
  "code": zod.string().default(duplicateTableResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('操作対象または生成されたテーブル名')
}).describe('テーブル複製レスポンス')
})

/**
 * テーブル名変更エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : RenameTableRequestBody
    リクエストボディ
    - oldTableName: 旧テーブル名
    - newTableName: 新テーブル名

Returns
-------
JSONResponse
    処理結果
 * @summary Rename Table
 */

export const renameTableBodyNewTableNameMax = 128;


export const renameTableBodyNewTableNameRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');


export const RenameTableBody = zod.object({
  "oldTableName": zod.string().min(1).describe('変更前のテーブル名'),
  "newTableName": zod.string().min(1).max(renameTableBodyNewTableNameMax).regex(renameTableBodyNewTableNameRegExp).describe('変更後の新しいテーブル名')
}).describe('テーブル名変更リクエスト')

export const renameTableResponseCodeDefault = `OK`;

export const RenameTableResponse = zod.object({
  "code": zod.string().default(renameTableResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('操作対象または生成されたテーブル名')
}).describe('テーブル名変更レスポンス')
})

/**
 * テーブルリストを取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト

Returns
-------
JSONResponse
    処理結果
 * @summary Get Table List
 */
export const getTableListResponseCodeDefault = `OK`;

export const GetTableListResponse = zod.object({
  "code": zod.string().default(getTableListResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableNameList": zod.array(zod.string()).describe('ワークスペースに存在するテーブル名のリスト')
}).describe('テーブルリスト取得レスポンス')
})

/**
 * 全テーブルをクリアするエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト

Returns
-------
JSONResponse
    処理結果
 * @summary Clear Tables
 */
export const clearTablesResponseCodeDefault = `OK`;

export const ClearTablesResponse = zod.object({
  "code": zod.string().default(clearTablesResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({

}).describe('全テーブルクリアレスポンス（データなし）')
})

/**
 * データをJSON形式で取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : FetchDataToJsonRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Fetch Data To Json
 */

export const fetchDataToJsonBodyStartRowMin = 0;

export const fetchDataToJsonBodyFetchRowsDefault = 500;
export const fetchDataToJsonBodyFetchRowsMax = 10000;



export const FetchDataToJsonBody = zod.object({
  "tableName": zod.string().min(1).describe('データを取得するテーブル名。ワークスペースに存在するテーブルの中から指定してください。'),
  "startRow": zod.number().min(fetchDataToJsonBodyStartRowMin).describe('取得を開始する行番号（0始まり）'),
  "fetchRows": zod.number().min(1).max(fetchDataToJsonBodyFetchRowsMax).default(fetchDataToJsonBodyFetchRowsDefault).describe('取得する行数（1〜10000、デフォルト500）')
}).describe('データJSON取得リクエスト')

export const fetchDataToJsonResponseCodeDefault = `OK`;

export const FetchDataToJsonResponse = zod.object({
  "code": zod.string().default(fetchDataToJsonResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('データを取得したテーブル名'),
  "data": zod.string().describe('JSON 文字列形式のテーブルデータ'),
  "totalRows": zod.number().describe('テーブル全体の行数'),
  "startRow": zod.number().describe('取得開始行番号'),
  "endRow": zod.number().describe('取得終了行番号')
}).describe('テーブルデータ JSON 形式取得レスポンス')
})

/**
 * データをApache Arrow IPC形式で取得するエンドポイント

仮想スクロール用のチャンク取得API。
Apache Arrow IPC形式のバイナリデータ（Base64エンコード）を返します。

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : FetchDataToArrowRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果（Arrow IPC形式のBase64エンコードされたバイナリを含む）
 * @summary Fetch Data To Arrow
 */

export const fetchDataToArrowBodyStartRowMin = 0;

export const fetchDataToArrowBodyChunkSizeDefault = 500;
export const fetchDataToArrowBodyChunkSizeMax = 10000;



export const FetchDataToArrowBody = zod.object({
  "tableName": zod.string().min(1).describe('データを取得するテーブル名。ワークスペースに存在するテーブルの中から指定してください。'),
  "startRow": zod.number().min(fetchDataToArrowBodyStartRowMin).describe('取得を開始する行番号（0始まり）'),
  "chunkSize": zod.number().min(1).max(fetchDataToArrowBodyChunkSizeMax).default(fetchDataToArrowBodyChunkSizeDefault).describe('1リクエストで取得する行数（1〜10000、デフォルト500）')
}).describe('データArrow取得リクエスト')

export const FetchDataToArrowResponse = zod.unknown()

/**
 * セルデータ入力エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : InputCellDataRequestBody
    リクエストボディ
    - tableName: テーブル名
    - columnName: 列名
    - rowIndex: 行インデックス
    - newValue: 新しい値

Returns
-------
JSONResponse
    処理結果
 * @summary Input Cell Data
 */


export const inputCellDataBodyRowIndexMin = 0;



export const InputCellDataBody = zod.object({
  "tableName": zod.string().min(1).describe('セルデータを入力するテーブル名。ワークスペースに存在するテーブルの中から指定してください。'),
  "columnName": zod.string().min(1).describe('セルデータを入力するカラム名。ワークスペースに存在するテーブルの中から指定してください。'),
  "rowIndex": zod.number().min(inputCellDataBodyRowIndexMin).describe('更新するセルの行インデックス（0始まり）'),
  "newValue": zod.unknown().describe('セルに入力する新しい値。カラムのデータ型に合わせた値を指定してください。')
}).describe('セルデータ入力リクエスト')

export const inputCellDataResponseCodeDefault = `OK`;

export const InputCellDataResponse = zod.object({
  "code": zod.string().default(inputCellDataResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('操作対象または生成されたテーブル名')
}).describe('セルデータ入力レスポンス')
})

/**
 * 単一条件フィルタリングを実行するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : FilterSingleConditionRequestBody
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Filter Single Condition
 */

export const filterSingleConditionBodyNewTableNameMax = 128;


export const filterSingleConditionBodyNewTableNameRegExp = new RegExp('^[^\\x00-\\x1f\\x7f]+$');

export const filterSingleConditionBodyIsCompareColumnMax = 10;



export const FilterSingleConditionBody = zod.object({
  "tableName": zod.string().min(1).describe('フィルタ条件を適用するテーブル名。ワークスペースに存在するテーブルの中から指定してください。'),
  "newTableName": zod.string().min(1).max(filterSingleConditionBodyNewTableNameMax).regex(filterSingleConditionBodyNewTableNameRegExp).describe('フィルタ結果を格納する新しいテーブル名。ワークスペースに存在しない名前を指定してください。'),
  "columnName": zod.string().min(1).describe('フィルタ条件を適用するカラム名。ワークスペースに存在するテーブルの中から指定してください。'),
  "condition": zod.enum(['equals', 'notEquals', 'greaterThan', 'lessThan', 'greaterThanOrEquals', 'lessThanOrEquals']),
  "isCompareColumn": zod.string().min(1).max(filterSingleConditionBodyIsCompareColumnMax).describe('比較対象がカラムかどうか。\"true\": compareValue をカラム名として解釈、\"false\": 定数値として解釈。'),
  "compareValue": zod.unknown().describe('比較する値またはカラム名。isCompareColumn が \"true\" の場合はカラム名を指定。')
}).describe('単一条件フィルタリクエスト')

export const filterSingleConditionResponseCodeDefault = `OK`;

export const FilterSingleConditionResponse = zod.object({
  "code": zod.string().default(filterSingleConditionResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "tableName": zod.string().describe('操作対象または生成されたテーブル名')
}).describe('単一条件フィルタレスポンス')
})

