/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * テーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Table Endpoint
 */
export const createTableEndpointBodyTableNameMax = 255;





export const CreateTableEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(createTableEndpointBodyTableNameMax).describe('テーブル名'),
  "tableNumberOfRows": zod.number().min(1).describe('テーブルの行数'),
  "columnNames": zod.array(zod.string()).min(1).describe('カラム名のリスト')
}).describe('テーブル作成リクエスト')

export const CreateTableEndpointResponse = zod.unknown()

/**
 * 結合テーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateJoinTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Join Table Endpoint
 */
export const createJoinTableEndpointBodyJoinTableNameMax = 255;

export const createJoinTableEndpointBodyLeftTableNameMax = 255;

export const createJoinTableEndpointBodyRightTableNameMax = 255;



export const createJoinTableEndpointBodyJoinTypeMax = 50;



export const CreateJoinTableEndpointBody = zod.object({
  "joinTableName": zod.string().min(1).max(createJoinTableEndpointBodyJoinTableNameMax).describe('結合後のテーブル名'),
  "leftTableName": zod.string().min(1).max(createJoinTableEndpointBodyLeftTableNameMax).describe('左側のテーブル名'),
  "rightTableName": zod.string().min(1).max(createJoinTableEndpointBodyRightTableNameMax).describe('右側のテーブル名'),
  "leftKeyColumnNames": zod.array(zod.string()).min(1).describe('左側の結合キーカラム名のリスト'),
  "rightKeyColumnNames": zod.array(zod.string()).min(1).describe('右側の結合キーカラム名のリスト'),
  "joinType": zod.string().min(1).max(createJoinTableEndpointBodyJoinTypeMax).describe('結合タイプ (inner, left, right, outer)')
}).describe('結合テーブル作成リクエスト')

export const CreateJoinTableEndpointResponse = zod.unknown()

/**
 * ユニオンテーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateUnionTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Union Table Endpoint
 */
export const createUnionTableEndpointBodyUnionTableNameMax = 255;




export const CreateUnionTableEndpointBody = zod.object({
  "unionTableName": zod.string().min(1).max(createUnionTableEndpointBodyUnionTableNameMax).describe('ユニオン後のテーブル名'),
  "tableNames": zod.array(zod.string()).min(1).describe('結合するテーブル名のリスト'),
  "columnNames": zod.array(zod.string()).optional().describe('対象カラム名のリスト')
}).describe('ユニオンテーブル作成リクエスト')

export const CreateUnionTableEndpointResponse = zod.unknown()

/**
 * シミュレーションデータテーブルを作成するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : CreateSimulationDataTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Create Simulation Data Table Endpoint
 */
export const createSimulationDataTableEndpointBodyTableNameMax = 255;





export const CreateSimulationDataTableEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(createSimulationDataTableEndpointBodyTableNameMax).describe('テーブル名'),
  "tableNumberOfRows": zod.number().min(1).describe('テーブルの行数'),
  "columnSettings": zod.array(zod.record(zod.string(), zod.unknown())).min(1).describe('カラム設定のリスト')
}).describe('シミュレーションデータテーブル作成リクエスト')

export const CreateSimulationDataTableEndpointResponse = zod.unknown()

/**
 * テーブルを削除するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DeleteTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Delete Table Endpoint
 */
export const deleteTableEndpointBodyTableNameMax = 255;



export const DeleteTableEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(deleteTableEndpointBodyTableNameMax).describe('テーブル名')
}).describe('テーブル削除リクエスト')

export const DeleteTableEndpointResponse = zod.unknown()

/**
 * テーブルを複製するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : DuplicateTableRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Duplicate Table Endpoint
 */
export const duplicateTableEndpointBodyTableNameMax = 255;

export const duplicateTableEndpointBodyNewTableNameMax = 255;



export const DuplicateTableEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(duplicateTableEndpointBodyTableNameMax).describe('元のテーブル名'),
  "newTableName": zod.string().min(1).max(duplicateTableEndpointBodyNewTableNameMax).describe('新しいテーブル名')
}).describe('テーブル複製リクエスト')

export const DuplicateTableEndpointResponse = zod.unknown()

/**
 * テーブル名変更エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : RenameTableRequest
    リクエストボディ
    - oldTableName: 旧テーブル名
    - newTableName: 新テーブル名

Returns
-------
JSONResponse
    処理結果
 * @summary Rename Table Endpoint
 */
export const renameTableEndpointBodyOldTableNameMax = 255;

export const renameTableEndpointBodyNewTableNameMax = 255;



export const RenameTableEndpointBody = zod.object({
  "oldTableName": zod.string().min(1).max(renameTableEndpointBodyOldTableNameMax).describe('元のテーブル名'),
  "newTableName": zod.string().min(1).max(renameTableEndpointBodyNewTableNameMax).describe('新しいテーブル名')
}).describe('テーブル名変更リクエスト')

export const RenameTableEndpointResponse = zod.unknown()

/**
 * テーブルリストを取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト

Returns
-------
JSONResponse
    処理結果
 * @summary Get Table List Endpoint
 */
export const GetTableListEndpointResponse = zod.unknown()

/**
 * 全テーブルをクリアするエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト

Returns
-------
JSONResponse
    処理結果
 * @summary Clear Tables Endpoint
 */
export const ClearTablesEndpointResponse = zod.unknown()

/**
 * データをJSON形式で取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : FetchDataToJsonRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Fetch Data To Json Endpoint
 */
export const fetchDataToJsonEndpointBodyTableNameMax = 255;

export const fetchDataToJsonEndpointBodyStartRowMin = 0;




export const FetchDataToJsonEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(fetchDataToJsonEndpointBodyTableNameMax).describe('対象テーブル名'),
  "startRow": zod.number().min(fetchDataToJsonEndpointBodyStartRowMin).describe('開始行番号'),
  "fetchRows": zod.number().min(1).describe('取得行数')
}).describe('データJSON取得リクエスト')

export const FetchDataToJsonEndpointResponse = zod.unknown()

/**
 * データをApache Arrow IPC形式で取得するエンドポイント

仮想スクロール用のチャンク取得API。
Apache Arrow IPC形式のバイナリデータ（Base64エンコード）を返します。

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : FetchDataToArrowRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果（Arrow IPC形式のBase64エンコードされたバイナリを含む）
 * @summary Fetch Data To Arrow Endpoint
 */
export const fetchDataToArrowEndpointBodyTableNameMax = 255;

export const fetchDataToArrowEndpointBodyStartRowMin = 0;

export const fetchDataToArrowEndpointBodyChunkSizeDefault = 500;
export const fetchDataToArrowEndpointBodyChunkSizeMax = 10000;



export const FetchDataToArrowEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(fetchDataToArrowEndpointBodyTableNameMax).describe('対象テーブル名'),
  "startRow": zod.number().min(fetchDataToArrowEndpointBodyStartRowMin).describe('開始行番号'),
  "chunkSize": zod.number().min(1).max(fetchDataToArrowEndpointBodyChunkSizeMax).default(fetchDataToArrowEndpointBodyChunkSizeDefault).describe('チャンクサイズ（デフォルト500行）')
}).describe('データArrow取得リクエスト')

export const FetchDataToArrowEndpointResponse = zod.unknown()

/**
 * セルデータ入力エンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : InputCellDataRequest
    リクエストボディ
    - tableName: テーブル名
    - columnName: 列名
    - rowIndex: 行インデックス
    - newValue: 新しい値

Returns
-------
JSONResponse
    処理結果
 * @summary Input Cell Data Endpoint
 */
export const inputCellDataEndpointBodyTableNameMax = 255;

export const inputCellDataEndpointBodyColumnNameMax = 255;

export const inputCellDataEndpointBodyRowIndexMin = 0;



export const InputCellDataEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(inputCellDataEndpointBodyTableNameMax).describe('テーブル名'),
  "columnName": zod.string().min(1).max(inputCellDataEndpointBodyColumnNameMax).describe('カラム名'),
  "rowIndex": zod.number().min(inputCellDataEndpointBodyRowIndexMin).describe('行インデックス'),
  "newValue": zod.unknown().describe('新しい入力値')
}).describe('セルデータ入力リクエスト')

export const InputCellDataEndpointResponse = zod.unknown()

/**
 * 単一条件フィルタリングを実行するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : FilterSingleConditionRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Filter Single Condition Endpoint
 */
export const filterSingleConditionEndpointBodyTableNameMax = 255;

export const filterSingleConditionEndpointBodyNewTableNameMax = 255;

export const filterSingleConditionEndpointBodyColumnNameMax = 255;

export const filterSingleConditionEndpointBodyConditionMax = 50;

export const filterSingleConditionEndpointBodyIsCompareColumnMax = 10;



export const FilterSingleConditionEndpointBody = zod.object({
  "tableName": zod.string().min(1).max(filterSingleConditionEndpointBodyTableNameMax).describe('テーブル名'),
  "newTableName": zod.string().min(1).max(filterSingleConditionEndpointBodyNewTableNameMax).describe('新しいテーブル名'),
  "columnName": zod.string().min(1).max(filterSingleConditionEndpointBodyColumnNameMax).describe('対象カラム名'),
  "condition": zod.string().min(1).max(filterSingleConditionEndpointBodyConditionMax).describe('条件'),
  "isCompareColumn": zod.string().min(1).max(filterSingleConditionEndpointBodyIsCompareColumnMax).describe('比較対象がカラムかどうか'),
  "compareValue": zod.unknown().describe('比較値')
}).describe('単一条件フィルタリクエスト')

export const FilterSingleConditionEndpointResponse = zod.unknown()

