from enum import Enum


class ErrorCode(str, Enum):
    """エラーコード定義"""

    # Columns関連
    ADD_COLUMN_PROCESS_ERROR = "ADD_COLUMN_PROCESS_ERROR"
    CSV_FILE_PATH_NOT_SPECIFIED = "CSV_FILE_PATH_NOT_SPECIFIED"
    EMPTY_CSV_FILE = "EMPTY_CSV_FILE"
    NO_COLUMNS_IN_CSV_FILE = "NO_COLUMNS_IN_CSV_FILE"
    ROW_COUNT_MISMATCH = "ROW_COUNT_MISMATCH"
    CSV_PROCESSING_ERROR = "CSV_PROCESSING_ERROR"
    SORT_COLUMNS_PROCESS_ERROR = "SORT_COLUMNS_PROCESS_ERROR"
    DUPLICATE_COLUMN_PROCESS_ERROR = "DUPLICATE_COLUMN_PROCESS_ERROR"
    RENAME_COLUMN_PROCESS_ERROR = "RENAME_COLUMN_PROCESS_ERROR"
    DELETE_COLUMN_PROCESS_ERROR = "DELETE_COLUMN_PROCESS_ERROR"
    GET_COLUMN_LIST_PROCESS_ERROR = "GET_COLUMN_LIST_PROCESS_ERROR"
    CALCULATION_EXPRESSION_ERROR = "CALCULATION_EXPRESSION_ERROR"
    CALCULATE_COLUMN_PROCESS_ERROR = "CALCULATE_COLUMN_PROCESS_ERROR"
    TRANSFORM_METHOD_ERROR = "TRANSFORM_METHOD_ERROR"
    TRANSFORM_COLUMN_PROCESS_ERROR = "TRANSFORM_COLUMN_PROCESS_ERROR"
    ADD_SIMULATION_COLUMN_PROCESS_ERROR = "ADD_SIMULATION_COLUMN_PROCESS_ERROR"
    ADD_DUMMY_COLUMN_PROCESS_ERROR = "ADD_DUMMY_COLUMN_PROCESS_ERROR"
    ADD_LAG_LEAD_COLUMN_PROCESS_ERROR = "ADD_LAG_LEAD_COLUMN_PROCESS_ERROR"
