from enum import StrEnum


class ErrorCode(StrEnum):
    """エラーコード定義"""

    # Columns関連
    ADD_COLUMN_PROCESS_ERROR = "ADD_COLUMN_PROCESS_ERROR"
    CSV_FILE_PATH_NOT_SPECIFIED = "CSV_FILE_PATH_NOT_SPECIFIED"
    EMPTY_CSV_FILE = "EMPTY_CSV_FILE"
    NO_COLUMNS_IN_CSV_FILE = "NO_COLUMNS_IN_CSV_FILE"
    ROW_COUNT_MISMATCH = "ROW_COUNT_MISMATCH"
    CSV_PROCESSING_ERROR = "CSV_PROCESSING_ERROR"
    SORT_COLUMNS_PROCESS_ERROR = "SORT_COLUMNS_PROCESS_ERROR"
    DUPLICATE_COLUMN_PROCESS_ERROR = "DUPLICATE_COLUMN_PROCESS_ERROR"
    RENAME_COLUMN_PROCESS_ERROR = "RENAME_COLUMN_PROCESS_ERROR"
    DELETE_COLUMN_PROCESS_ERROR = "DELETE_COLUMN_PROCESS_ERROR"
    GET_COLUMN_LIST_PROCESS_ERROR = "GET_COLUMN_LIST_PROCESS_ERROR"
    CALCULATION_EXPRESSION_ERROR = "CALCULATION_EXPRESSION_ERROR"
    CALCULATE_COLUMN_PROCESS_ERROR = "CALCULATE_COLUMN_PROCESS_ERROR"
    TRANSFORM_METHOD_ERROR = "TRANSFORM_METHOD_ERROR"
    TRANSFORM_COLUMN_PROCESS_ERROR = "TRANSFORM_COLUMN_PROCESS_ERROR"
    ADD_SIMULATION_COLUMN_PROCESS_ERROR = "ADD_SIMULATION_COLUMN_PROCESS_ERROR"
    ADD_DUMMY_COLUMN_PROCESS_ERROR = "ADD_DUMMY_COLUMN_PROCESS_ERROR"
    ADD_LAG_LEAD_COLUMN_PROCESS_ERROR = "ADD_LAG_LEAD_COLUMN_PROCESS_ERROR"

    # Data I/O関連
    UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"
    EXCEL_IMPORT_ERROR = "EXCEL_IMPORT_ERROR"
    EXCEL_EXPORT_ERROR = "EXCEL_EXPORT_ERROR"
    CSV_IMPORT_ERROR = "CSV_IMPORT_ERROR"
    PARQUET_IMPORT_ERROR = "PARQUET_IMPORT_ERROR"
    PARQUET_EXPORT_ERROR = "PARQUET_EXPORT_ERROR"
    TABLE_NOT_FOUND = "TABLE_NOT_FOUND"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    CSV_EXPORT_ERROR = "CSV_EXPORT_ERROR"

    # Regressions関連
    GET_ALL_RESULTS_ERROR = "GET_ALL_RESULTS_ERROR"
    RESULT_ID_REQUIRED = "RESULT_ID_REQUIRED"
    GET_ANALYSIS_RESULT_ERROR = "GET_ANALYSIS_RESULT_ERROR"
    DELETE_ANALYSIS_RESULT_ERROR = "DELETE_ANALYSIS_RESULT_ERROR"
    CLEAR_ALL_ANALYSIS_RESULTS_ERROR = "CLEAR_ALL_ANALYSIS_RESULTS_ERROR"
    REGRESSION_PROCESS_ERROR = "REGRESSION_PROCESS_ERROR"
    MISSING_VALUES_FOUND = "MISSING_VALUES_FOUND"
    NO_VALID_OBSERVATIONS = "NO_VALID_OBSERVATIONS"
    MODEL_FILE_NOT_FOUND = "MODEL_FILE_NOT_FOUND"
    MODEL_KEY_MISMATCH = "MODEL_KEY_MISMATCH"
    ADD_DIAGNOSTIC_COLUMNS_PROCESS_ERROR = (
        "ADD_DIAGNOSTIC_COLUMNS_PROCESS_ERROR"
    )
    MODEL_TYPE_NOT_SUPPORTED = "MODEL_TYPE_NOT_SUPPORTED"

    # Statistics関連
    CONFIDENCE_INTERVAL_ERROR = "CONFIDENCE_INTERVAL_ERROR"
    INVALID_PROPORTION_DATA = "INVALID_PROPORTION_DATA"
    DESCRIPTIVE_STATISTICS_ERROR = "DESCRIPTIVE_STATISTICS_ERROR"

    # Tables関連
    CLEAR_TABLES_ERROR = "CLEAR_TABLES_ERROR"
    JOIN_TABLE_CREATION_ERROR = "JOIN_TABLE_CREATION_ERROR"
    UNION_TABLE_CREATION_ERROR = "UNION_TABLE_CREATION_ERROR"
    CREATE_TABLE_ERROR = "CREATE_TABLE_ERROR"
    COLUMN_COUNT_MISMATCH = "COLUMN_COUNT_MISMATCH"
    TABLE_DUPLICATION_ERROR = "TABLE_DUPLICATION_ERROR"
    TABLE_DELETION_ERROR = "TABLE_DELETION_ERROR"
    FETCH_DATA_TO_ARROW_ERROR = "FETCH_DATA_TO_ARROW_ERROR"
    FETCH_DATA_TO_JSON_ERROR = "FETCH_DATA_TO_JSON_ERROR"
    CREATE_SIMULATION_DATA_TABLE_ERROR = "CREATE_SIMULATION_DATA_TABLE_ERROR"
    INVALID_CONDITION_ERROR = "INVALID_CONDITION_ERROR"
    FILTER_SINGLE_CONDITION_PROCESS_ERROR = (
        "FILTER_SINGLE_CONDITION_PROCESS_ERROR"
    )
    GET_TABLE_LIST_ERROR = "GET_TABLE_LIST_ERROR"
    INPUT_CELL_DATA_PROCESS_ERROR = "INPUT_CELL_DATA_PROCESS_ERROR"
    TABLE_RENAME_ERROR = "TABLE_RENAME_ERROR"

    # Validation関連
    VALIDATION_ERROR = "VALIDATION_ERROR"
    PATH_NOT_FOUND = "PATH_NOT_FOUND"
    NOT_A_FILE = "NOT_A_FILE"
    NOT_A_DIRECTORY = "NOT_A_DIRECTORY"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    EMPTY_FILE = "EMPTY_FILE"
    DATA_NOT_FOUND = "DATA_NOT_FOUND"
    DATA_ALREADY_EXISTS = "DATA_ALREADY_EXISTS"
    INVALID_DTYPE = "INVALID_DTYPE"
    ROW_OUT_OF_RANGE = "ROW_OUT_OF_RANGE"

    # Settings関連
    GET_SETTINGS_ERROR = "GET_SETTINGS_ERROR"
