/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.2.0
 */
import * as zod from 'zod';


/**
 * アプリケーション設定を取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト

Returns
-------
JSONResponse
    処理結果
 * @summary Get Settings
 */
export const GetSettingsHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})

export const getSettingsResponseCodeDefault = `OK`;

export const GetSettingsResponse = zod.object({
  "code": zod.string().default(getSettingsResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "language": zod.string().describe('アプリケーションの表示言語（ja: 日本語, en: 英語）'),
  "lastOpenedPath": zod.string().describe('最後に開いたフォルダパス'),
  "theme": zod.string().describe('アプリケーションのテーマ（light \/ dark）'),
  "encoding": zod.string().describe('ファイルエンコーディング'),
  "logPath": zod.string().describe('ログファイルの出力先パス')
}).describe('処理結果')
})

/**
 * アプリケーション設定を更新するエンドポイント

指定されたフィールドのみを部分更新します。省略したフィールドは
現在の値を維持します。更新後の設定全体をレスポンスとして返します。

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : UpdateSettingsRequest
    更新するフィールドを含むリクエストボディ（すべて省略可能）
settings_store : SettingsStoreDep
    依存注入された設定ストア

Returns
-------
JSONResponse
    更新後の設定情報
 * @summary Update Settings
 */
export const UpdateSettingsHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})

export const updateSettingsBodyLanguageOneRegExp = new RegExp('^(ja|en)$');
export const updateSettingsBodyThemeOneRegExp = new RegExp('^(light|dark)$');


export const UpdateSettingsBody = zod.object({
  "language": zod.union([zod.string().regex(updateSettingsBodyLanguageOneRegExp),zod.null()]).optional().describe('表示言語。\'ja\' または \'en\' のみ許可。'),
  "theme": zod.union([zod.string().regex(updateSettingsBodyThemeOneRegExp),zod.null()]).optional().describe('テーマ。\'light\' または \'dark\' のみ許可。'),
  "encoding": zod.union([zod.string(),zod.null()]).optional().describe('ファイルエンコーディング'),
  "logPath": zod.union([zod.string(),zod.null()]).optional().describe('ログファイルの出力先パス')
}).describe('アプリケーション設定更新リクエスト（すべてのフィールドが省略可能）')

export const updateSettingsResponseCodeDefault = `OK`;

export const UpdateSettingsResponse = zod.object({
  "code": zod.string().default(updateSettingsResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "language": zod.string().describe('アプリケーションの表示言語（ja: 日本語, en: 英語）'),
  "lastOpenedPath": zod.string().describe('最後に開いたフォルダパス'),
  "theme": zod.string().describe('アプリケーションのテーマ（light \/ dark）'),
  "encoding": zod.string().describe('ファイルエンコーディング'),
  "logPath": zod.string().describe('ログファイルの出力先パス')
}).describe('処理結果')
})

