/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Economicon App API
 * OpenAPI spec version: 0.4.0
 */
import * as zod from 'zod';


/**
 * 信頼区間シミュレーション

M 回サンプリングを行い、各試行の信頼区間と
真の値との包含関係を返す。
 * @summary Confidence Interval Sim
 */
export const ConfidenceIntervalSimHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})

export const confidenceIntervalSimBodyCiTypeDefault = `mean`;
export const confidenceIntervalSimBodyTrialsDefault = 100;
export const confidenceIntervalSimBodyTrialsMin = 10;
export const confidenceIntervalSimBodyTrialsMax = 2000;

export const confidenceIntervalSimBodySampleSizeDefault = 30;
export const confidenceIntervalSimBodySampleSizeMin = 5;
export const confidenceIntervalSimBodySampleSizeMax = 500;

export const confidenceIntervalSimBodyConfidenceLevelDefault = 0.95;
export const confidenceIntervalSimBodyTrueMeanDefault = 0;
export const confidenceIntervalSimBodyTrueMeanMin = -100;
export const confidenceIntervalSimBodyTrueMeanMax = 100;

export const confidenceIntervalSimBodyTrueVarianceDefault = 1;
export const confidenceIntervalSimBodyTrueVarianceMin = 0.01;
export const confidenceIntervalSimBodyTrueVarianceMax = 100;



export const ConfidenceIntervalSimBody = zod.object({
  "ciType": zod.enum(['mean', 'variance']).default(confidenceIntervalSimBodyCiTypeDefault),
  "trials": zod.number().min(confidenceIntervalSimBodyTrialsMin).max(confidenceIntervalSimBodyTrialsMax).default(confidenceIntervalSimBodyTrialsDefault).describe('シミュレーション試行回数'),
  "sampleSize": zod.number().min(confidenceIntervalSimBodySampleSizeMin).max(confidenceIntervalSimBodySampleSizeMax).default(confidenceIntervalSimBodySampleSizeDefault).describe('各試行のサンプルサイズ'),
  "confidenceLevel": zod.number().default(confidenceIntervalSimBodyConfidenceLevelDefault).describe('信頼水準（0.90 \/ 0.95 \/ 0.99）'),
  "trueMean": zod.number().min(confidenceIntervalSimBodyTrueMeanMin).max(confidenceIntervalSimBodyTrueMeanMax).default(confidenceIntervalSimBodyTrueMeanDefault).describe('母平均の真の値'),
  "trueVariance": zod.number().min(confidenceIntervalSimBodyTrueVarianceMin).max(confidenceIntervalSimBodyTrueVarianceMax).default(confidenceIntervalSimBodyTrueVarianceDefault).describe('母分散の真の値')
}).describe('信頼区間シミュレーションリクエスト')

export const confidenceIntervalSimResponseCodeDefault = `OK`;

export const ConfidenceIntervalSimResponse = zod.object({
  "code": zod.string().default(confidenceIntervalSimResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "trueValue": zod.number().describe('真の値'),
  "confidenceLevel": zod.number().describe('信頼水準'),
  "intervals": zod.array(zod.object({
  "lower": zod.number().describe('信頼区間下限'),
  "upper": zod.number().describe('信頼区間上限'),
  "containsTrue": zod.boolean().describe('真の値を含むか否か')
}).describe('信頼区間の境界値と包含フラグ')).describe('各試行の信頼区間リスト')
}).describe('処理結果')
})

/**
 * 漸近正規性シミュレーション

同一パラメータで num_simulations 回 OLS を行い、
β̂ の標本分布と漸近分布の理論値を返す。
 * @summary Asymptotic Normality
 */
export const AsymptoticNormalityHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})

export const asymptoticNormalityBodySampleSizeDefault = 100;
export const asymptoticNormalityBodyNumSimulationsDefault = 1000;
export const asymptoticNormalityBodyNumSimulationsMin = 10;
export const asymptoticNormalityBodyNumSimulationsMax = 2000;

export const asymptoticNormalityBodyTrueBetaDefault = 1;
export const asymptoticNormalityBodyTrueBetaMin = -3;
export const asymptoticNormalityBodyTrueBetaMax = 3;

export const asymptoticNormalityBodyErrorVarianceDefault = 1;
export const asymptoticNormalityBodyErrorVarianceMin = 0.1;
export const asymptoticNormalityBodyErrorVarianceMax = 10;

export const asymptoticNormalityBodyErrorTypeDefault = `normal`;
export const asymptoticNormalityBodyEndogeneityStrengthDefault = 1;
export const asymptoticNormalityBodyEndogeneityStrengthMin = 0.1;
export const asymptoticNormalityBodyEndogeneityStrengthMax = 3;

export const asymptoticNormalityBodyXDistributionXMeanDefault = 0;
export const asymptoticNormalityBodyXDistributionXMeanMin = -10;
export const asymptoticNormalityBodyXDistributionXMeanMax = 10;

export const asymptoticNormalityBodyXDistributionXVarianceDefault = 1;
export const asymptoticNormalityBodyXDistributionXVarianceMin = 0.1;
export const asymptoticNormalityBodyXDistributionXVarianceMax = 10;



export const AsymptoticNormalityBody = zod.object({
  "sampleSize": zod.union([zod.literal(10),zod.literal(20),zod.literal(30),zod.literal(50),zod.literal(100),zod.literal(1000)]).default(asymptoticNormalityBodySampleSizeDefault),
  "numSimulations": zod.number().min(asymptoticNormalityBodyNumSimulationsMin).max(asymptoticNormalityBodyNumSimulationsMax).default(asymptoticNormalityBodyNumSimulationsDefault).describe('OLS の反復シミュレーション回数'),
  "trueBeta": zod.number().min(asymptoticNormalityBodyTrueBetaMin).max(asymptoticNormalityBodyTrueBetaMax).default(asymptoticNormalityBodyTrueBetaDefault).describe('真の傾きパラメータ'),
  "errorVariance": zod.number().min(asymptoticNormalityBodyErrorVarianceMin).max(asymptoticNormalityBodyErrorVarianceMax).default(asymptoticNormalityBodyErrorVarianceDefault).describe('誤差の分散'),
  "errorType": zod.enum(['normal', 'cauchy', 'endogenous']).default(asymptoticNormalityBodyErrorTypeDefault),
  "endogeneityStrength": zod.number().min(asymptoticNormalityBodyEndogeneityStrengthMin).max(asymptoticNormalityBodyEndogeneityStrengthMax).default(asymptoticNormalityBodyEndogeneityStrengthDefault).describe('内生性の強さ（γ）: endogenous 時のみ有効'),
  "xDistribution": zod.object({
  "xMean": zod.number().min(asymptoticNormalityBodyXDistributionXMeanMin).max(asymptoticNormalityBodyXDistributionXMeanMax).default(asymptoticNormalityBodyXDistributionXMeanDefault).describe('説明変数 x の母平均'),
  "xVariance": zod.number().min(asymptoticNormalityBodyXDistributionXVarianceMin).max(asymptoticNormalityBodyXDistributionXVarianceMax).default(asymptoticNormalityBodyXDistributionXVarianceDefault).describe('説明変数 x の母分散')
}).optional().describe('説明変数 x の母集団分布パラメータ')
}).describe('漸近正規性シミュレーションリクエスト')

export const asymptoticNormalityResponseCodeDefault = `OK`;

export const AsymptoticNormalityResponse = zod.object({
  "code": zod.string().default(asymptoticNormalityResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "betaEstimates": zod.array(zod.number()).describe('OLS β̂ の標本リスト'),
  "trueBeta": zod.number().describe('真の傾きパラメータ'),
  "isAsymptoticallyNormal": zod.boolean().describe('漸近正規性が成立するか否か'),
  "asymptoticMean": zod.union([zod.number(),zod.null()]).describe('漸近分布の平均（コーシー時は None）'),
  "asymptoticVariance": zod.union([zod.number(),zod.null()]).describe('漸近分布の分散（コーシー時は None）')
}).describe('処理結果')
})

/**
 * 一致性シミュレーション

n=2 から n_max まで逐次 OLS を行い、
サンプルサイズ増加に伴う β̂ の収束軌跡を返す。
 * @summary Consistency
 */
export const ConsistencyHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})

export const consistencyBodyNMaxDefault = 500;
export const consistencyBodyNMaxMin = 50;
export const consistencyBodyNMaxMax = 5000;

export const consistencyBodyTrueBetaDefault = 1;
export const consistencyBodyTrueBetaMin = -3;
export const consistencyBodyTrueBetaMax = 3;

export const consistencyBodyErrorVarianceDefault = 1;
export const consistencyBodyErrorVarianceMin = 0.1;
export const consistencyBodyErrorVarianceMax = 10;

export const consistencyBodyEndogenousDefault = false;
export const consistencyBodyEndogeneityStrengthDefault = 1;
export const consistencyBodyEndogeneityStrengthMin = 0.1;
export const consistencyBodyEndogeneityStrengthMax = 3;

export const consistencyBodyXDistributionXMeanDefault = 0;
export const consistencyBodyXDistributionXMeanMin = -10;
export const consistencyBodyXDistributionXMeanMax = 10;

export const consistencyBodyXDistributionXVarianceDefault = 1;
export const consistencyBodyXDistributionXVarianceMin = 0.1;
export const consistencyBodyXDistributionXVarianceMax = 10;



export const ConsistencyBody = zod.object({
  "nMax": zod.number().min(consistencyBodyNMaxMin).max(consistencyBodyNMaxMax).default(consistencyBodyNMaxDefault).describe('サンプルサイズの上限'),
  "trueBeta": zod.number().min(consistencyBodyTrueBetaMin).max(consistencyBodyTrueBetaMax).default(consistencyBodyTrueBetaDefault).describe('真の傾きパラメータ'),
  "errorVariance": zod.number().min(consistencyBodyErrorVarianceMin).max(consistencyBodyErrorVarianceMax).default(consistencyBodyErrorVarianceDefault).describe('誤差の分散'),
  "endogenous": zod.boolean().default(consistencyBodyEndogenousDefault).describe('内生性あり (True) \/ 外生性成立 (False)'),
  "endogeneityStrength": zod.number().min(consistencyBodyEndogeneityStrengthMin).max(consistencyBodyEndogeneityStrengthMax).default(consistencyBodyEndogeneityStrengthDefault).describe('内生性の強さ（γ）: endogenous=True 時のみ有効'),
  "xDistribution": zod.object({
  "xMean": zod.number().min(consistencyBodyXDistributionXMeanMin).max(consistencyBodyXDistributionXMeanMax).default(consistencyBodyXDistributionXMeanDefault).describe('説明変数 x の母平均'),
  "xVariance": zod.number().min(consistencyBodyXDistributionXVarianceMin).max(consistencyBodyXDistributionXVarianceMax).default(consistencyBodyXDistributionXVarianceDefault).describe('説明変数 x の母分散')
}).optional().describe('説明変数 x の母集団分布パラメータ')
}).describe('一致性シミュレーションリクエスト')

export const consistencyResponseCodeDefault = `OK`;

export const ConsistencyResponse = zod.object({
  "code": zod.string().default(consistencyResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "nValues": zod.array(zod.number()).describe('各推定に使用したサンプルサイズのリスト'),
  "betaEstimates": zod.array(zod.number()).describe('各 n における OLS β̂ のリスト'),
  "trueBeta": zod.number().describe('真の傾きパラメータ'),
  "probabilityLimit": zod.number().describe('確率極限（外生性: β, 内生性: β + γ\/2）')
}).describe('処理結果')
})

/**
 * 不偏性シミュレーション

同一母集団から num_trials 回独立にサンプリングして
OLS を行い、β̂ の標本分布を返す。
 * @summary Unbiasedness
 */
export const UnbiasednessHeader = zod.object({
  "X-Auth-Token": zod.string().optional().describe('Tauri 起動時に生成された認証トークン')
})

export const unbiasednessBodyNumTrialsDefault = 200;
export const unbiasednessBodyNumTrialsMin = 10;
export const unbiasednessBodyNumTrialsMax = 2000;

export const unbiasednessBodySampleSizeDefault = 50;
export const unbiasednessBodySampleSizeMin = 5;
export const unbiasednessBodySampleSizeMax = 500;

export const unbiasednessBodyTrueBetaDefault = 1;
export const unbiasednessBodyTrueBetaMin = -3;
export const unbiasednessBodyTrueBetaMax = 3;

export const unbiasednessBodyErrorVarianceDefault = 1;
export const unbiasednessBodyErrorVarianceMin = 0.1;
export const unbiasednessBodyErrorVarianceMax = 10;

export const unbiasednessBodyXDistributionXMeanDefault = 0;
export const unbiasednessBodyXDistributionXMeanMin = -10;
export const unbiasednessBodyXDistributionXMeanMax = 10;

export const unbiasednessBodyXDistributionXVarianceDefault = 1;
export const unbiasednessBodyXDistributionXVarianceMin = 0.1;
export const unbiasednessBodyXDistributionXVarianceMax = 10;



export const UnbiasednessBody = zod.object({
  "numTrials": zod.number().min(unbiasednessBodyNumTrialsMin).max(unbiasednessBodyNumTrialsMax).default(unbiasednessBodyNumTrialsDefault).describe('OLS の反復試行回数'),
  "sampleSize": zod.number().min(unbiasednessBodySampleSizeMin).max(unbiasednessBodySampleSizeMax).default(unbiasednessBodySampleSizeDefault).describe('各試行のサンプルサイズ'),
  "trueBeta": zod.number().min(unbiasednessBodyTrueBetaMin).max(unbiasednessBodyTrueBetaMax).default(unbiasednessBodyTrueBetaDefault).describe('真の傾きパラメータ'),
  "errorVariance": zod.number().min(unbiasednessBodyErrorVarianceMin).max(unbiasednessBodyErrorVarianceMax).default(unbiasednessBodyErrorVarianceDefault).describe('誤差の分散'),
  "xDistribution": zod.object({
  "xMean": zod.number().min(unbiasednessBodyXDistributionXMeanMin).max(unbiasednessBodyXDistributionXMeanMax).default(unbiasednessBodyXDistributionXMeanDefault).describe('説明変数 x の母平均'),
  "xVariance": zod.number().min(unbiasednessBodyXDistributionXVarianceMin).max(unbiasednessBodyXDistributionXVarianceMax).default(unbiasednessBodyXDistributionXVarianceDefault).describe('説明変数 x の母分散')
}).optional().describe('説明変数 x の母集団分布パラメータ')
}).describe('不偏性シミュレーションリクエスト')

export const unbiasednessResponseCodeDefault = `OK`;

export const UnbiasednessResponse = zod.object({
  "code": zod.string().default(unbiasednessResponseCodeDefault).describe('レスポンスコード'),
  "result": zod.object({
  "betaEstimates": zod.array(zod.number()).describe('各試行の OLS β̂ リスト'),
  "trueBeta": zod.number().describe('真の傾きパラメータ')
}).describe('処理結果')
})

