/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * ファイル一覧を取得するエンドポイント

Parameters
----------
request : Request
    FastAPIのリクエストオブジェクト
body : GetFilesRequest
    リクエストボディ

Returns
-------
JSONResponse
    処理結果
 * @summary Get Files Endpoint
 */
export const getFilesEndpointApiFileGetListPostBodyDirectoryPathMax = 1024;



export const GetFilesEndpointApiFileGetListPostBody = zod.object({
  "directoryPath": zod.string().min(1).max(getFilesEndpointApiFileGetListPostBodyDirectoryPathMax).describe('対象ディレクトリパス')
}).describe('ファイル一覧取得リクエスト')

export const GetFilesEndpointApiFileGetListPostResponse = zod.unknown()

